static/Makefile
This part was failing on the jenkins job:
=> Make the hash_files target non interactive

deb/debian-jessie/Dockerfile.amd64, deb/debian-jessie/Dockerfile.armhf, deb/debian-stretch/Dockerfile.amd64, deb/debian-stretch/Dockerfile.armhf, deb/debian-wheezy/Dockerfile.amd64, deb/debian-wheezy/Dockerfile.armhf, deb/ubuntu-trusty/Dockerfile.amd64, deb/ubuntu-trusty/Dockerfile.armhf, deb/ubuntu-xenial/Dockerfile.amd64, deb/ubuntu-xenial/Dockerfile.armhf, deb/ubuntu-xenial/Dockerfile.s390x, deb/ubuntu-yakkety/Dockerfile.amd64, deb/ubuntu-yakkety/Dockerfile.armhf, deb/ubuntu-yakkety/Dockerfile.s390x, deb/ubuntu-zesty/Dockerfile.amd64, deb/ubuntu-zesty/Dockerfile.armhf, deb/ubuntu-zesty/Dockerfile.s390x, rpm/fedora-24/Dockerfile.x86_64, rpm/fedora-25/Dockerfile.x86_64
Update GO version in accordance with https://github.com/moby/moby/commit/0c7c900e9e66335a6bd486be008af43ae83a5a37
=> Update GO_VERSION to 1.8.3

deb/Makefile, rpm/Makefile
Just need interactive in order to cancel docker runs.
=> no need for tty

rpm/centos-7/docker-ce.spec, rpm/fedora-24/docker-ce.spec, rpm/fedora-25/docker-ce.spec
These are replaced by `container-selinux` on fedora-25 and centos-7.
Marking these packages as obsolete makes the installation process a bit
smoother, otherwise the user will have to manually uninstall the older
packages to install the new one.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
=> Mark docker-*-selinux pkgs as obsolete

rpm/centos-7/docker-ce.spec, rpm/fedora-24/docker-ce.spec, rpm/fedora-25/docker-ce.spec
Since we pull from multiple components to build docker-ce now it makes sense to have all of the related files associated with each component packaged into RPMS.
This will prefix all files that were previously included in the RPM with the component from which they originate.
End result will look like so:
=> Prefixes documentation files per component

deb/common/control
Without this PR, docker-ce and docker-engine deb packages will be installed on the system at the same time.
=> also have deb pkg conflict docker-engine

rpm/centos-7/docker-ce.spec, rpm/fedora-24/docker-ce.spec, rpm/fedora-25/docker-ce.spec
Addresses issue moby/moby#33688: Container can not start after docker engine upgrade from 17.03.1-ce to 17.06.0-ce-rc3
This PR will stop the docker service if it is running in an upgrade scenario (docker service is never started on a fresh install as per RPM behaviour conventions). It will then restart the service after the new files are installed so that the new daemon is used to launch the service.
For reference, RPM spec file scriptlet ordering https://fedoraproject.org/wiki/Packaging:Scriptlets
To build a centos rpm:
```
$ make -C rpm ENGINE_DIR=/path/to/engine/code CLI_DIR=/path/to/cli/code centos-7 # rpm will be in rpm/rpmbuild
```
=> restart docker service if needed for rpm upgrade

deb/common/docker-ce.bash-completion, deb/common/docker-ce.install, rpm/centos-7/docker-ce.spec, rpm/fedora-24/docker-ce.spec, rpm/fedora-25/docker-ce.spec
The completion scripts have been moved to the docker/cli repository, so should be taken from that directory.
Note that the docker/docker-ce repository is currently in a mixed state; these two pull requests should be included there;
https://github.com/docker/cli/pull/189
https://github.com/moby/moby/pull/33665
ping @tiborvass @andrewhsu PTAL
=> Fix paths for completion scripts

static/Makefile
Without this PR, `clean` target would fail if `build` dir not found.
=> check if build dir exists before chown

deb/ubuntu-yakkety/Dockerfile.s390x
Adds the seccomp buildtag for ubuntu-yakkety on s390x
Note: s390x requires libseccomp-dev 2.3.1 at the moment which is only available
only yakkety and later. This change is also consistent with the s390x yakkety
deb dockerfile in moby/moby.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>
=> [s390x] add seccomp buildtag for ubuntu-yakkety

deb/ubuntu-xenial/Dockerfile.aarch64, detect_alpine_image
=> Add ubuntu-xenial aarch64 Dockerfile

deb/common/rules
manpage generation was failing for docker cli when being run under
aarch64: 
https://ci.qa.aws.dckr.io/job/docker/job/release-packaging/view/change-requests/job/PR-41/5/execution/node/360/log/
The way to remedy this is to compile the cli and the manpages while in
the GOPATH so that dependencies found in the vendor folder are
discovered by the go build tools.
=> Have docker cli be compiled in GOPATH

deb/common/rules
Tried out make -C in this scenario and it did not seem to function
correctly, changed to cd.
Remedies issues found in #36 #11 
=> Change make -C to a cd command for manpage generation

Makefile, deb/Makefile, deb/raspbian-jessie/Dockerfile.armv7l, deb/raspbian-stretch/Dockerfile.armv7l
This PR adds build steps to create DEB packages for Raspbian and for all Raspberry Pi models including the ARMv6 Pi Zero, Pi Zero W or old Raspberry Pi (1) model A/B.
I'm now running 17.07.0-dev on my Raspberry Pi Zero W.
I kept the names of the Dockerfiles at `Dockerfile.armv7l` so someone can build them on eg. Scaleway servers.
The only difference to the debian-jessie/Dockerfile.armv7l is using a different base image with Raspbian installed as well as setting `ENV GOARM 6` to create Pi Zero compatible binaries.
Picture of a small wireless Docker host:
It would be great if https://download.docker.com/linux/raspbian/ could be populated with these raspbian deb packages to have Docker CE 17.06 available for Raspberry Pi projects.
=> Add Raspbian deb packages

deb/build-deb
`build-deb` would not propagate any errors it happened to have causing false positives in test runs of package building.
This PR remedies some errors experienced with errors now being raised up through the script.
* dev version naming now relies on system time instead of git commit time due to the `engine` directory not containing any git information
* `-v` was removed from dpkg-buildpackage (it was actually setting `version` when I thought it had originally set `verbose`)
CC @andrewhsu @thaJeztah
=> Tell build-deb to throw up errors

rpm/fedora-26/docker-ce.spec
Leftover from #41,
Fedora 26 does not build successfully without removing these lines.
CC @andrewhsu
=> Removes telemetry mentions from Fedora 26

deb/ubuntu-xenial/Dockerfile.ppc64le, detect_alpine_image
Adds ubuntu-xenial as a make deb target for ppc64le.
I've tested this with 17.06, but can't get a successful build with
the upstream cli repo because of https://github.com/docker/for-linux/issues/54.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>
=> [ppc64le] add deb support for ubuntu-xenial

deb/ubuntu-zesty/Dockerfile.ppc64le
Don't mind the version, it's from [moby/moby](https://github.com/moby/moby/blob/master/VERSION) master
=> Adds ppc64le builds for ubuntu zesty

deb/common/docker-ce.install
these examples are not nescessary for day-to-day use of docker, so don't have to be included in the packages.
=> remove desktop-integration contrib from .deb

deb/debian-jessie/Dockerfile.armv7l, deb/debian-jessie/Dockerfile.x86_64, deb/debian-wheezy/Dockerfile.x86_64, deb/raspbian-jessie/Dockerfile.armv7l
For jessie and wheezy flavors of distros. Some dep seems to have changed
from before.
Creating packages have failures like:
```
Package libudev was not found in the pkg-config search path.
Perhaps you should add the directory containing `libudev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libudev', required by 'devmapper', not found
pkg-config: exit status 1
debian/rules:14: recipe for target 'override_dh_auto_build' failed
```
=> added libudev-dev pkg as build requirement

rpm/centos-7/docker-ce.spec, rpm/fedora-25/docker-ce.spec, rpm/fedora-26/docker-ce.spec
We haven't been updating it, seems like a waste to just track releases
through it.
=> Remove RPM changelog

deb/ubuntu-xenial/Dockerfile.aarch64, detect_alpine_image
The "aarch64" images on Docker Hub are deprecated in favor of the "arm64v8" images.
@seemethere @tianon PTAL :heart:
=> Switch aarch64 images to arm64v8

deb/ubuntu-trusty/Dockerfile.armv7l
Was getting 404's with the old one, consider this one temporary until
canonical fixes their stuff.
Related:
https://bugs.launchpad.net/cloud-images/+bug/1711735
=> Switches ubuntu trusty mirror to one that works

deb/debian-buster/Dockerfile.armv7l, deb/debian-buster/Dockerfile.x86_64, deb/debian-jessie/Dockerfile.armv7l, deb/debian-jessie/Dockerfile.x86_64, deb/debian-stretch/Dockerfile.armv7l, deb/debian-stretch/Dockerfile.x86_64, deb/debian-wheezy/Dockerfile.x86_64, deb/raspbian-jessie/Dockerfile.armv7l, deb/raspbian-stretch/Dockerfile.armv7l, deb/ubuntu-trusty/Dockerfile.armv7l, deb/ubuntu-trusty/Dockerfile.x86_64, deb/ubuntu-xenial/Dockerfile.aarch64, deb/ubuntu-xenial/Dockerfile.armv7l, deb/ubuntu-xenial/Dockerfile.ppc64le, deb/ubuntu-xenial/Dockerfile.s390x, deb/ubuntu-xenial/Dockerfile.x86_64, deb/ubuntu-zesty/Dockerfile.armv7l, deb/ubuntu-zesty/Dockerfile.ppc64le, deb/ubuntu-zesty/Dockerfile.s390x, deb/ubuntu-zesty/Dockerfile.x86_64, rpm/centos-7/Dockerfile.x86_64, rpm/fedora-25/Dockerfile.x86_64, rpm/fedora-26/Dockerfile.x86_64
Bumps the Go version used to 1.8.4, which contains
security fixes; https://groups.google.com/forum/#!topic/golang-announce/1hZYiemnkdE
ping @seemethere @andrewhsu
=> Bump Go to 1.8.4

deb/Makefile, deb/ubuntu-artful/Dockerfile.armv7l, deb/ubuntu-artful/Dockerfile.ppc64le, deb/ubuntu-artful/Dockerfile.s390x, deb/ubuntu-artful/Dockerfile.x86_64
=> Add Ubuntu 17.10, Artful

Makefile, rpm/Makefile, rpm/fedora-27/Dockerfile.x86_64, rpm/fedora-27/docker-ce.spec
Fedora 27 has hit GA! https://fedoramagazine.org/announcing-fedora-27/
Relies on: https://github.com/docker-library/official-images/pull/3708
Relates to: 
* https://github.com/docker/for-linux/issues/143
* https://github.com/docker/docker-install/issues/40
**NOTE**: The next release this is eligible for is `17.12.0-ce`
=> Adds packaging for Fedora 27

Jenkinsfile
We were missing testing in this repo, this adds basic tests for our core 3 functionalities:
* Building deb packages
* Building RPM packges
* Building static binaries
=> Adds initial Jenkinsfile

deb/debian-buster/Dockerfile.armv7l, deb/debian-buster/Dockerfile.x86_64, deb/debian-jessie/Dockerfile.armv7l, deb/debian-jessie/Dockerfile.x86_64, deb/debian-stretch/Dockerfile.armv7l, deb/debian-stretch/Dockerfile.x86_64, deb/debian-wheezy/Dockerfile.x86_64, deb/raspbian-jessie/Dockerfile.armv7l, deb/raspbian-stretch/Dockerfile.armv7l, deb/ubuntu-artful/Dockerfile.armv7l, deb/ubuntu-artful/Dockerfile.ppc64le, deb/ubuntu-artful/Dockerfile.s390x, deb/ubuntu-artful/Dockerfile.x86_64, deb/ubuntu-trusty/Dockerfile.armv7l, deb/ubuntu-trusty/Dockerfile.x86_64, deb/ubuntu-xenial/Dockerfile.aarch64, deb/ubuntu-xenial/Dockerfile.armv7l, deb/ubuntu-xenial/Dockerfile.ppc64le, deb/ubuntu-xenial/Dockerfile.s390x, deb/ubuntu-xenial/Dockerfile.x86_64, deb/ubuntu-zesty/Dockerfile.armv7l, deb/ubuntu-zesty/Dockerfile.ppc64le, deb/ubuntu-zesty/Dockerfile.s390x, deb/ubuntu-zesty/Dockerfile.x86_64, rpm/centos-7/Dockerfile.x86_64, rpm/fedora-25/Dockerfile.x86_64, rpm/fedora-26/Dockerfile.x86_64, rpm/fedora-27/Dockerfile.x86_64
now that the other components of docker-ce are using golang 1.9.2 and expecting 1.9.2-specific stuff like `sync.Map`
=> use golang 1.9.2

Jenkinsfile
Setting to something that will not be confused with a version number
that will ever be released. Also, this is required for the deb packages
to build properly.
=> set VERSION when building packages

Jenkinsfile
Seems `docker-edge` was removed as label on jenkins.dockerproject.org.
This removes that label and just puts the x86_64 label
ping @psftw
=> Change label to one that actually exists

deb/debian-jessie/Dockerfile.aarch64
Failed out otherwise:
```
---> Making bundle: dynbinary (in bundles/dynbinary)
Building: bundles/dynbinary-daemon/dockerd-17.09.0-dev
Package libudev was not found in the pkg-config search path.
```
=> Adds libudev-dev to jessie aarch64 build

rpm/fedora-27/docker-ce.spec
Relates to an upgrade in `rpm` to `14.4.0`, where missing build-ids now
cause builds to self-terminate. May be needed in other distros if/when
the `rpm` package is updated in those repos.
=> Do not terminate on missing build-ids

static/Makefile
VERSION file does not exist anymore for moby/moby so we need to
compensate
=> Pass VERSION to engine static builds

rpm/gen-rpm-ver
Such as  "17.09.1-ce-dev". The generation now will produce "17.09.1.ce-dev" rpm version. This version will cause rpm build error. Replace all "-" in version will resolve this problem.
🐼
=> replace all '-' in version when generate rpm version

rpm/centos-7/Dockerfile.aarch64, rpm/fedora-25/Dockerfile.aarch64, rpm/fedora-26/Dockerfile.aarch64, rpm/fedora-27/Dockerfile.aarch64
Like [#25](https://github.com/docker/docker-ce-packaging/pull/25) and [#35](https://github.com/docker/docker-ce-packaging/pull/35), this PR extends aarch64 support with RPMs builds.
I'm currently using the rpm package on fedora 27 with RPi 3.
=> Aarch64 rpm support 

rpm/gen-rpm-ver
-dev was being removed, per legacy code, but we'd like to add it back
into the naming so that deb / rpm packages will look mostly the same
when compiled with a `-dev` version.
RPMS end up looking like:
`docker-ce-18.02.0.ce-0.0.dev.git20180120.170357.0.fa4fb35.el7.centos.x86_64.rpm`
=> Add dev portion to RPM package version

deb/common/control, rpm/centos-7/docker-ce.spec, rpm/fedora-26/docker-ce.spec, rpm/fedora-27/docker-ce.spec
This change is in response to https://github.com/moby/moby/pull/35697
It adds pigz to the recommended binaries that should be installed with
docker-ce.
Signed-off-by: Sargun Dhillon <sargun@sargun.me>
=> Add pigz to recommended packages

deb/common/rules, rpm/fedora-26/docker-ce.spec, rpm/fedora-27/docker-ce.spec
This fixes running Docker Engine under limited number of processes (https://github.com/docker/for-linux/issues/73). It was supposedly fixed for deb packaged, but the fix was/is not working. For Fedora, it was never fixed.
See https://github.com/docker/for-linux/issues/73 and https://github.com/docker/docker-ee/pull/164 for more details
=> Uncomment TasksMax=unlimited for recent distros

static/Makefile, static/gen-static-ver
Adds git date plus git commit sha to static builds if the version being
built for is a development version, taken from `rpm/gen-rpm-ver`
Output is similar to: `docker-18.02.0-ce-dev-20180120.170357-fa4fb35.tgz`
=> Static Dev builds should include date and sha

deb/Makefile, deb/build-deb, deb/gen-deb-ver
Dev builds for debian packages previously had system time inserted into
their packaging names while both static and rpm builds instead had the
git commit time.
This commit remedies that by pushing the generation of the debian
package version into a separate script to mirror what is being done in
static and rpm builds.
To give you an idea of what it looks like take the following examples:
```
❯ ./gen-deb-ver ~/work/docker-ce/components/engine/ $(cat ~/work/docker-ce/VERSION)
18.03.0~ce~dev~git20180202.170651.0.e232737
```
```
❯ ./gen-rpm-ver ~/work/docker-ce/components/engine $(cat ~/work/docker-ce/VERSION)
18.03.0.ce 0.0.dev.git20180202.170651.0.e232737 e232737
```
```
❯ ./gen-static-ver ~/work/docker-ce/components/engine/ $(cat ~/work/docker-ce/VERSION) …
```
=> Re-add Git Commit time to deb dev builds

deb/debian-buster/Dockerfile.armv7l, deb/debian-buster/Dockerfile.x86_64, deb/debian-jessie/Dockerfile.aarch64, deb/debian-jessie/Dockerfile.armv7l, deb/debian-jessie/Dockerfile.x86_64, deb/debian-stretch/Dockerfile.aarch64, deb/debian-stretch/Dockerfile.armv7l, deb/debian-stretch/Dockerfile.x86_64, deb/debian-wheezy/Dockerfile.x86_64, deb/raspbian-jessie/Dockerfile.armv7l, deb/raspbian-stretch/Dockerfile.armv7l, deb/ubuntu-artful/Dockerfile.armv7l, deb/ubuntu-artful/Dockerfile.ppc64le, deb/ubuntu-artful/Dockerfile.s390x, deb/ubuntu-artful/Dockerfile.x86_64, deb/ubuntu-trusty/Dockerfile.armv7l, deb/ubuntu-trusty/Dockerfile.x86_64, deb/ubuntu-xenial/Dockerfile.aarch64, deb/ubuntu-xenial/Dockerfile.armv7l, deb/ubuntu-xenial/Dockerfile.ppc64le, deb/ubuntu-xenial/Dockerfile.s390x, deb/ubuntu-xenial/Dockerfile.x86_64, rpm/centos-7/Dockerfile.aarch64, rpm/centos-7/Dockerfile.x86_64, rpm/fedora-26/Dockerfile.aarch64, rpm/fedora-26/Dockerfile.x86_64, rpm/fedora-27/Dockerfile.aarch64, rpm/fedora-27/Dockerfile.x86_64
This fixes a vulnerability in `go get` (CVE-2018-6574, http://golang.org/issue/23672),
but shouldn't really affect our code, but it's good to keep in sync.
ping @andrewhsu @seemethere ~we need to test the Windows builds with this, as it looks like this may break them: https://github.com/moby/moby/pull/36243#issuecomment-364017854~
stuff works now for windows with the fix in docker/cli: https://github.com/docker/cli/pull/868
=> Bump Golang to 1.9.4

rpm/centos-7/docker-ce.spec
Adds a requirement to check for a minimum version of `libseccomp` for CentOS 7.
As reported by users in:
* https://github.com/moby/moby/issues/35906
=> Add libseccomp requirement for CentOS 7

Makefile
Zesty is EOL and doesn't even have a subdirectory in the `deb` directory of this repo. There's no need to have it as a default.
Signed-off-by: Corbin <corbin.coleman@docker.com>
=> Remove ubuntu-zesty from the default DOCKER_BUILD_PKGS in Makefile

deb/build-deb, rpm/centos-7/docker-ce.spec, rpm/fedora-26/docker-ce.spec, rpm/fedora-27/docker-ce.spec
Binary installation was broken after the
hack/dockerfile/install-binaries script was removed in https://github.com/moby/moby/pull/36336
This remedies that.
=> Fixes binary installation

deb/build-deb, rpm/centos-7/docker-ce.spec, rpm/fedora-26/docker-ce.spec, rpm/fedora-27/docker-ce.spec
Scripts were changed around to do static by default, this changes so
that we have "dynamic" inserted where it needs to be inserted
Relies on https://github.com/moby/moby/pull/36518
=> Use new 'dynamic' args in install.sh

deb/Makefile, deb/build-deb
This refactors a large portion of `deb/Makefile` to make it easier to edit the run /build commands.
This also makes it so that `epoch` can be passed as a make variable and changed at the package building step allowing us to be a bit more flexible if/when the epoch needs to be changed.
=> Refactor epoch to be a passable variable for debian packaging

deb/gen-deb-ver, rpm/gen-rpm-ver
Enables the usage of a new versioning scheme for test builds:
```
* tp   -> Technical Previews
* beta -> Beta Releases
* rc   -> Release Candidates
* ga   -> General Availability Releases
```
This PR fixes the versioning order for both `deb` and `rpm` packages
when it relates to the new versioning scheme (which may or may not be
used).
<details>
<summary>gen-rpm-ver</summary>
```
❯ for version in "tp1" "beta2" "rc3" ""; do echo -n "18.01.0-ce-$version: "; ./gen-rpm-ver ~/work/docker-ce/ "18.01.0-ce-$version"; done
18.01.0-ce-tp1: 18.01.0.ce 0.1.tp1 0b63fed
18.01.0-ce-beta2: 18.01.0.ce 1.2.beta2 0b63fed
18.01.0-ce-rc3: 18.01.0.ce 2.3.rc3 0b63fed
18.01.0-ce-: 18.01.0.ce. 3 0b63fed
```
</details>
<details>
<summary>gen-deb-ver</summary>
```
❯ for version in "tp1" "beta2" "rc3" ""; do echo -n …
```
=> Enable new test versioning scheme

deb/gen-deb-ver
Found a bug where a number was being appended to the nightly dev builds
package name causing the latest packages not to be considered as the
latest packages by the package manager.
This makes it so that the number is not included on dev builds.
=> Don't append number when doing a dev build

deb/Makefile, deb/ubuntu-bionic/Dockerfile.armv7l, deb/ubuntu-bionic/Dockerfile.ppc64le, deb/ubuntu-bionic/Dockerfile.s390x, deb/ubuntu-bionic/Dockerfile.x86_64
Ubuntu Bionic (18.04) isn't scheduled to release until [April 26th](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule) but Docker images are already up on Hub so we should get ahead of the curve when it comes to building the packages in our nightly pipeline.
=> Add building code for Ubuntu Bionic (18.04) LTS

deb/ubuntu-bionic/Dockerfile.aarch64
Missed `aarch64` when I did #97.
=> Add Ubuntu 18.04 arm64 builds

rpm/Makefile, rpm/fedora-28/Dockerfile.aarch64, rpm/fedora-28/Dockerfile.x86_64, rpm/fedora-28/docker-ce.spec
Fedora 28 isn't currently scheduled to release until [May 8, 2018](https://fedoraproject.org/wiki/Releases/28/Schedule) but let's get ahead of the curve since the Docker images are already up on Docker Hub.
Builds for this ~are currently~were failing due to a bug in the pinned version of `containerd` as shown in https://github.com/containerd/btrfs/issues/15:
```
🇩 bin/containerd
vendor/github.com/containerd/btrfs/btrfs.go:103: constant 18446744073709551616 overflows C.__u64
vendor/github.com/containerd/btrfs/btrfs.go:104: constant 18446744073709551616 overflows C.__u64
vendor/github.com/containerd/btrfs/btrfs.go:105: constant 18446744073709551616 overflows C.__u64
make: *** [Makefile:133: bin/containerd] Error 2
```
To get this we would just need to update to `containerd` v1.0.3 as seen …
=> Add packaging code for Fedora 28

deb/ubuntu-xenial/Dockerfile.s390x
For Xenial on s390x, we initially refrained from using seccomp buildtags as there has been a bug in the libseccomp2 version that was in 16.04.
However, libseccomp2 for Xenial is now on a level which does not have any restrictions anymore. (That is also true for all other s390x distributions).
Therefore, keep in sync with the rest of the world and use libseccomp for xenial.
=> use seccomp for xenial

deb/Makefile, rpm/Makefile
Experimental features are no longer a build-time option, and can be enabled at runtime.
ping @seemethere @vdemeester I think these were no longer needed, but perhaps I missed something 😅
=> Remove "experimental" env-vars

Makefile
The hardcoded values make it so that we have to update this everytime we
add/subtract something which is sometimes followed/not followed.
This makes it so that we no longer have to update this.
=> Make DOCKER_BUILD_PKGS reflective

rpm/centos-7/docker-ce.spec
The pigz binary is used to improve performance when pulling images, but is not available in the default CentOS package repositories.
Given that RPM's don't have a "recommends" option, it's better to remove it as a requirement for now, instead of failing to install for some users.
relates to https://github.com/moby/moby/pull/35697
fixes https://github.com/docker/for-linux/issues/299
=> Remove pigz requirement for CentOS

deb/debian-buster/Dockerfile.aarch64, deb/debian-buster/Dockerfile.armv7l, deb/debian-buster/Dockerfile.x86_64
btrfs-tools is being deprecated in favor of btrfs-progs, will only
matter for debian versions >= buster
=> btrfs-tools -> btrfs-progs

deb/debian-buster/Dockerfile.aarch64, deb/debian-buster/Dockerfile.armv7l, deb/debian-buster/Dockerfile.x86_64
`btrfs-progs` doesn't actually contain the files we need, since we only
need the headers for btrfs, which `libbtrfs-dev` now provides.
=> Remove btrfs-progs in favor of libbtrfs-dev

deb/Makefile, deb/gen-deb-ver, rpm/Makefile, rpm/centos-7/docker-ce.spec, rpm/fedora-27/docker-ce.spec, rpm/fedora-28/docker-ce.spec, rpm/gen-rpm-ver, static/gen-static-ver
Switches dev versioning from being based on a set version like
`18.06.0-dev` to being based purely on the git commit timestamp / git
commit sha.
This should give us a bit more flexibility in terms of nightlies not
being tied to specific versions.
Versioning will now look like this:
`0.${gitTimestamp}~${gitCommit}`
The prefixed `0.` is so that it will not *ever* get sorted above actual versions,
although it should never be in a position to be put in the same channel as actual
versions. 🤷‍♂️ 
<details>
<summary> Partial output of `docker version` </summary>
```
Client:
Version:      0.20180706.170746~23d14578b4
API version:  1.38
Go version:   go1.10.3
Git commit:   23d14578b4
Built:        Fri Jul  6 17:26:29 2018
OS/Arch:      linux/amd64
Experimental: false
```
</details>
Signed-off-by: …
=> Change dev versioning to be purely git based

static/gen-static-ver
`.deb` and `.rpm` package dev version schemes are prefixed with a `0.` why not static tgz's as well. 🤷‍♂️ 
=> Add a `0.` to be more consistent with dev version

deb/gen-deb-ver, rpm/gen-rpm-ver, static/gen-static-ver
tilde doesn't play nice with docker images so to be uniform let's
replace the tilde with a dash
=> `~` -> `-` for dev versions

image/Makefile
For the Q3 release the names will be refined slightly, and "ce" will no
longer be used - it's now just the docker engine, with "community" or
"enterprise" at the end if disambiguation is needed.
=> Switch image name on hub

Makefile
The engine component was being deleted on the call to clean. 
This is problematic because the clean target is called prior to building the engine image, and the engine is needed for building. 
This fixes that problem.
=> Don't delete the engine when cleaning

deb/common/rules, rpm/centos-7/docker-ce.spec, rpm/fedora-27/docker-ce.spec, rpm/fedora-28/docker-ce.spec
To accommodate for changes in https://github.com/docker/engine/pull/21
=> [18.06] add PRODUCT=docker env var when building engine

Makefile
The static version variable was copied from Makefile/image, so it needed to be updated.
=> Fix static version variable

rpm/Makefile, rpm/centos-7/Dockerfile.aarch64, rpm/centos-7/Dockerfile.x86_64, rpm/centos-7/docker-ce.spec, rpm/fedora-27/Dockerfile.aarch64, rpm/fedora-27/Dockerfile.x86_64, rpm/fedora-27/docker-ce.spec, rpm/fedora-28/Dockerfile.aarch64, rpm/fedora-28/Dockerfile.x86_64, rpm/fedora-28/docker-ce.spec
Refactor building of RPMs to multi-stage `Dockerfile`. Also moved the build deps into the spec file and reduced to just the packages used to build docker-ce. Had to hard-code the `Epoch` in the spec file to get `yum-builddep` to work.
Reduced build times from 6'30" to 5'04" and reduced the RPM build image size from 1.5G to 1.1G.
No functionality change in the final RPM produced.
Before:
```
$ time make -C components/packaging DOCKER_BUILD_PKGS=fedora-28 rpm
...
Wrote: /root/rpmbuild/SRPMS/docker-ce-0.0.0.20180810123659.af7228d929-0.fc28.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/docker-ce-0.0.0.20180810123659.af7228d929-0.fc28.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/docker-ce-debugsource-0.0.0.20180810123659.af7228d929-0.fc28.x86_64.rpm
Wrote: …
```
=> refactor building of RPMs to multi-stage

.gitignore, common/dockerd.json, containerd.mk, deb/Makefile, image/Makefile, rpm/Makefile, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec, rpm/centos-7/Dockerfile.aarch64, rpm/centos-7/Dockerfile.x86_64, rpm/fedora-27/Dockerfile.aarch64, rpm/fedora-27/Dockerfile.x86_64, rpm/fedora-28/Dockerfile.aarch64, rpm/fedora-28/Dockerfile.x86_64, systemd/docker.service
Splits out the docker-ce package and docker-ce-cli package into their
own things.
Includes functionality for running dockerd as a host process that's managed by containerd.
Dependencies include:
* containerd.io package (not yet released, soon though...)
* [containerd-proxy](https://github.com/crosbymichael/containerd-proxy)
* [containerd-shim-process](https://hub.docker.com/r/docker/containerd-shim-process/) (available as a hub image)
Still TODO: (as in stuff for other PR's)
* Offline installation support (will need a way to dump engine images to oci compliant tar balls)
* Not hardcoding the engine image in the `dockerd.json` 
* Not pointing to Seemethere's org (engine image)
~Still TODO: need to have a cleanup on the dependencies for the
Dockerfiles~ This is done
~NOTE: this relies on …
=> Add RPM packaging for 18.09.x

deb/Makefile, deb/debian-buster/Dockerfile, deb/debian-jessie/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-jessie/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-trusty/Dockerfile, deb/ubuntu-xenial/Dockerfile, rpm/Makefile
Allows us to switch out debian files and rpm specs on the fly and also
gives us an out to have ARCH specific dockerfiles if we need them for
RPM's. The same strategy can be used for DEB's if need be
Going to merge on green.
=> Add some changes to make things more configurable

deb/Makefile, rpm/Makefile
Was reporting 404's using the old url for some reason, might have to
refactor this in the future to just use a git clone...
=> Make the curl for containerd-proxy more resilient

common/dockerd.json, deb/Makefile, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-ce.spec
Builds the `engine.tar` as an image that `containerd` can actually use
=> Do offline bundles for engine installs

Makefile, image/Dockerfile.engine, image/Makefile, static/Makefile
This will report a fixed string for community engines
Related to https://github.com/moby/moby/pull/37612
=> Set up default product license for community engines

common/dockerd.json
Should rely on list in the daemon
=> Remove overlay as the default storage driver

common/dockerd.json
Should rely on list in the daemon
(cherry picked from commit 605758124d0750c14d24bfb1ebcf77d102591f4a)
=> [18.09] Remove overlay as the default storage driver

containerd.mk
Without this PR, unable to detect an active `containerd.io` package:
```
$ systemctl status containerd | head -3
● containerd.service - containerd container runtime
Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2018-08-22 23:44:45 UTC; 6h ago
$ make -pn -f containerd.mk | grep -e ^CONTAINERD_SOCK
make: *** No targets.  Stop.
CONTAINERD_SOCK := /var/run/docker/containerd/docker-containerd.sock
```
With this PR, allows proper detection:
```
$ make -pn -f containerd.mk | grep -e ^CONTAINERD_SOCK
make: *** No targets.  Stop.
CONTAINERD_SOCK := /var/run/containerd/containerd.sock
```
=> [master] use systemctl is-active to check for containerd

common/dockerd.json, deb/Makefile, rpm/Makefile
This should make it easier to change downstream builds
to change the scope.
=> [18.09] Make engine scope a build time setting

deb/Makefile
This will probably need to be forward ported into Master as well.
=> [18.09] Bump the epoch from 2 to 3 for deb packages

containerd.mk
Cherry Picked with: 
```
git cherry-pick eea6967f5de4835800349b1bcf2b81de8fd92207
```
Forward port of https://github.com/docker/docker-ce-packaging/pull/162
=> [master] [Forward Port] update containerd proxy commit to afca176

Makefile
This encodes the platform as "Docker Engine - Community"
for community engines
=> [18.09] Expose the platform string for community builds

deb/common/control
While testing on older ubuntu images we discovered
we do depend on a newer version of libseccomp2.
=> [18.09] Add explicit dependency for libseccomp2

rpm/SPECS/docker-ce.spec
so docker-ce can work on systems with selinux enabled
=> [18.09] add requires container-selinux to spec

rpm/SPECS/docker-ce.spec
porting of #173
cherry pick of e4b1c10a no conflicts
```
$ git cherry-pick -s -x e4b1c10a
[mse ca02ff0] add requires container-selinux to spec
Date: Wed Aug 29 04:23:49 2018 +0000
1 file changed, 1 insertion(+)
```
=> [master] add requires container-selinux to spec

image/Dockerfile.engine
This adds the standardized OCI labels for our image so downstream tools
will be able to inspect/extract these mechanically.
Reference: https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys
=> Add standard OCI labels

systemd/docker.service
The new systemd unit file was missing various options; this PR is porting those options. I wasn't sure if all options should be set in the new situation, so I included each change in a separate commit, keeping the original upstream commit message where applicable;
- ~bump open files (original PR: https://github.com/moby/moby/pull/4455)~
- skipped in favor of https://github.com/moby/moby/pull/24307
- no limit on core size (original PR: https://github.com/moby/moby/pull/10598)
- contrib: systemd: set Limit* to infinity (original PR: https://github.com/moby/moby/pull/24307 / https://github.com/moby/moby/pull/24555)
- docker.service: don't limit tasks (original PR: https://github.com/moby/moby/pull/21491)
- we may need a variation of https://github.com/moby/moby/pull/21628 to comment this for …
=> Update new systemd unit file with changes from upstream

deb/build-deb
It's generally bad-form to generate two identically named package files
that are actually different, so we should name our packages based on
the distro and version, not just the distro.
If this works out, we should cherry-pick over to 18.09
=> Change deb package filenames to be unique

containerd.mk
backport:
* #186 Update proxy commit for shutdown timeouts
no conflicts
```
$ git cherry-pick -s -x 7941c69
[to 61d98f8] Update proxy commit for shutdown timeouts
Author: Michael Crosby <crosbymichael@gmail.com>
Date: Wed Sep 5 18:17:48 2018 -0400
1 file changed, 1 insertion(+), 1 deletion(-)
```
=> [18.09] Update proxy commit for shutdown timeouts

systemd/docker.service
Cherry pick of #179 
```
❯ git cherry-pick -x -s da69663b9ccd72d95ec60007ef707d82a35324fa 68e15413dce8d6e8f428ac286641a9482d30aabc 82fe96733f551d36018c3840cf21d813807e9b76 e134e666a585b1f13e9e5e371dd93e5ce04a4b34 d736ae9da7401f58
2469fa7e943adde9f2163024 3e1b508e5f70b35869d9c8417d3b65a141820af9 2c2bfea5d009fb884f5c61b62e3c85bd88e7909e
```
Cherry pick was *clean*
The new systemd unit file was missing various options; this PR is porting those options. I wasn't sure if all options should be set in the new situation, so I included each change in a separate commit, keeping the original upstream commit message where applicable;
- ~bump open files (original PR: https://github.com/moby/moby/pull/4455)~
- skipped in favor of https://github.com/moby/moby/pull/24307
- no limit on core size (original …
=> [18.09] Update new systemd unit file with changes from upstream

deb/common/control
Was running into issues where the `docker-ce-cli` installation was being stopped by a `docker-ce-cli` trying to overwrite files from `docker-ce` <= 18.06.
This should remedy that.
=> Fix docker-ce-cli replacing files

deb/Makefile, deb/common/control, deb/common/rules, deb/debian-buster/Dockerfile, deb/debian-jessie/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-jessie/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-trusty/Dockerfile, deb/ubuntu-xenial/Dockerfile, rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/centos-7/Dockerfile, rpm/fedora-27/Dockerfile, rpm/fedora-28/Dockerfile, systemd/docker.service
Removes the need for the offline installer to install the shim process
and instead installs the shim process as part of the packaging.
May be easier in the future to just package the shim process on it's own
but that'll come after this 18.09 release
=> Remove offline installer to install shim-process

deb/Makefile, deb/common/control, deb/common/rules, deb/debian-buster/Dockerfile, deb/debian-jessie/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-jessie/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-trusty/Dockerfile, deb/ubuntu-xenial/Dockerfile, rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/centos-7/Dockerfile, rpm/fedora-27/Dockerfile, rpm/fedora-28/Dockerfile, systemd/docker.service
Cherry pick of #191 was **clean**
Removes the need for the offline installer to install the shim process
and instead installs the shim process as part of the packaging.
May be easier in the future to just package the shim process on it's own
but that'll come after this 18.09 release
(cherry picked from commit f8bd366d58f8bdf8a82b9a033353ca5bf4eda948)
=> [18.09] Remove offline installer to install shim-process

deb/Makefile, image/Makefile, rpm/Makefile
Backport of https://github.com/docker/docker-ce-packaging/pull/196
Brought the changes in with 
```
git cherry-pick -s -x eba0ed1f3497ebf25666d96c73c71fde9de98b50
git cherry-pick -s -x 8a4744f48aa13bea0b4e9174165be4add0a5a42f
```
=> [18.09] move tar targets

image/Makefile
This is set in a top-level makefile, but apparently
isn't getting passed all the way through as expected.
Forward port of #199 
(cherry picked from commit a5ad5471419cb2a0935148f891c5ada8b13b4779)
=> Wire up the platform string properly

containerd.mk
Includes fixes related to upgrade cycles
(cherry picked from commit 83a20d53f14adcd2bcc9e932435aa66b6e056afa)
=> [18.09] Bump proxy to 35c543b

deb/gen-deb-ver
Should generate correct bits whether or not the suffix is present.
Working example:
```
❯ for version in 18.09.1-ce 18.09.1 18.09.1-ce-rc1 18.09.1-rc1; do echo "$ ./gen-deb-ver . $version"; ./gen-deb-ver . "$version"; echo; done
$ ./gen-deb-ver . 18.09.1-ce
18.09.1~ce~3 18.09.1-ce
$ ./gen-deb-ver . 18.09.1
18.09.1~3 18.09.1
$ ./gen-deb-ver . 18.09.1-ce-rc1
18.09.1~ce~2.1.rc1 18.09.1-ce-rc1
$ ./gen-deb-ver . 18.09.1-rc1
18.09.1~2.1.rc1 18.09.1-rc1
```
=> Remove need for SUFFIX in gen-deb-ver

image/Makefile
Not sure why were including them in the first place but there's that.
=> Do not include arch tag in image builds

image/Makefile
Backport of #201 
Cherry pick was **clean**
(cherry picked from commit f7b0d0742e4b23e3442ce78cbc0d4c190929eb96)
=> [18.09] Remove the arch in the image tag

image/Dockerfile.engine
osusergo build tag is needed for better chances to have
a proper static binary when Go >= 1.11 is used, and is
harmless otherwise.
seccomp build tag is needed so the resulting dockerd binary
has seccomp support.
=> [master] image/Dockerfile: add osusergo, seccomp tags

image/Dockerfile.engine
osusergo build tag is needed for better chances to have
a proper static binary when Go >= 1.11 is used, and is
harmless otherwise.
seccomp build tag is needed so the resulting dockerd binary
has seccomp support.
=> [18.09] image/Dockerfile: add osusergo, seccomp tags

systemd/docker.service
iptables is sometimes placed in `/usr/sbin`
=> Add `/usr/sbin` to our path variable for systemd

.gitignore, image/Dockerfile.engine-dm, image/Makefile, rpm/Makefile
devicemapper cannot be enabled on a statically compiled binary so we
dynamically compile it on a rhel based distribution in order to enable
devicemapper usage.
=> Add native rpm compilation for devicemapper

.gitignore, image/Dockerfile.engine-dm, image/Makefile, rpm/Makefile
devicemapper cannot be enabled on a statically compiled binary so we
dynamically compile it on a rhel based distribution in order to enable
devicemapper usage.
Cherry pick of #215 
(cherry picked from commit 7cb8d358947974abae3e3c346b09523904030609)
=> [18.09] Add native rpm compilation for devicemapper

deb/Makefile
This reverts commit 6c5b7fcb956871f7a44e1a478ad9450f9df4bed1. https://github.com/docker/docker-ce-packaging/pull/167
=> [18.09] revert "Specify suffix for DEB_VERSION"

README.md
backport https://github.com/docker/docker-ce-packaging/pull/177 to minimize the diff between the 18.09 branch and master
(cherry picked from commit f0212649020ad5a1b0ca17c61ab500992ac981b4)
=> [18.09] backport Update outdated Fedora versions

systemd/docker.service
Set the PATH to what appears to be the standard on latest Ubuntu (18.04)
and Debian (9), fixing the following two issues:
1. PATH did not contain /bin (leading to ContainerTop/ps not working
on newer distros, among the other things).
2. $PATH can't be specified in Environment directives in .service files.
While at it, also:
3. Remove the comment about RPM as it looks misleading on deb-based
systems.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
=> [master] systemd/docker.service: fix PATH

deb/common/control
backport of https://github.com/docker/docker-ce-packaging/pull/224 for 18.09
```
git checkout -b 18.09_update_package_description upstream/18.09
git cherry-pick -s -S -x a4df8fe1f86f38ad935862eb188b6fc234d22793
git cherry-pick -s -S -x 1a3379642fb37457d0249ae99385d17ddc85a6af
```
=> [18.09] backport update package description

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec, rpm/centos-7/docker-ce.spec, rpm/fedora-27/docker-ce.spec, rpm/fedora-28/docker-ce.spec
Follow up to https://github.com/docker/docker-ce-packaging/pull/225
These files are currently only in the 18.09 branch, so this patch, in addition to other changes that were only done in the 18.09 branch, will have to be ported to master as well
=> [18.09] more updates to package description

image/Makefile
Cherry-pick of https://github.com/docker/docker-ce-packaging/pull/233
With 
```
git cherry-pick -s -x 206d61f29d1722ae3e319e22a4c5c88d1baf6e13
```
(cherry picked from commit 206d61f29d1722ae3e319e22a4c5c88d1baf6e13)
=> [18.09] Make -dm image based not tag based

deb/Makefile, deb/common/control, deb/common/docker-ce.postinst, deb/common/docker-ce.prerm, deb/common/rules, deb/debian-buster/Dockerfile, deb/debian-jessie/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-jessie/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-trusty/Dockerfile, deb/ubuntu-xenial/Dockerfile, image/Dockerfile.engine, image/Dockerfile.engine-dm, image/Makefile, rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/centos-7/Dockerfile, rpm/fedora-27/Dockerfile, rpm/fedora-28/Dockerfile, systemd/docker.service
* Switches the build process to utilize the engine image to download binaries to be installed as part of the package
* Removes `containerd-proxy` and `containerd-shim-process` as dependencies for the packaging
* Removes extra containerd flags in the systemd unit file (this will actually brick installations with these new packages until the defaults are changed in upstream `moby/moby`)
* Adds a breadcrumb file that contains metadata over what image was used for the binaries that are being installed with the package
=> Use image artifacts as daemon and dependencies

deb/Makefile
Cherry-pick of https://github.com/docker/docker-ce-packaging/pull/236
With 
```
git cherry-pick -s -x 024e366bd36799b24a1b8f4666de62208fb7d9a5
```
=> [18.09] epoch bump

systemd/docker.service
Backport of #239 
Cherry pick was clean
(cherry picked from commit 9eac27f0ee2d02355ecdeea243d2607d633c0b0b)
=> [18.09] Remove Environment, not needed anymore

deb/common/control
Backport of #243, cherry pick was **clean**
Epoch needs to be included in the Replaces / Breaks sections
(cherry picked from commit f6a3e274b4892f8f501e1191a73d8b8935a56aa5)
=> [18.09] Fix debian package upgrade scenarios

image/Makefile
This should ensure we don't produce builds without a valid "Built:"
field in the the version payload.
=> Make sure buildtime is always set

Makefile
This encodes the platform as "Docker Engine - Community"
for community engines
Cherry-pick #165 to master
=> Expose the platform string for community builds

deb/common/control
Nightly builds wouldn't install correctly since our versioning scheme
for nightly builds is 0.0.0~ and 0 < 18.
Should be backwards compatible with 18.09 builds so there's no need to
actually backport this to 18.09.
=> Change replaces/breaks to have compat with nightly

systemd/docker.service
Backport https://github.com/docker/docker-ce-packaging/pull/249 for 18.09. This was a regression introduced in https://github.com/docker/docker-ce-packaging/pull/131
```
git checkout -b 18.09_backport_notify upstream/18.09
git cherry-pick -s -S -x 221b152fde996db4c7571c37f8b934db7f5dda49
git push -u origin
```
=> [18.09 backport] Restore `Type=notify` in Systemd unit

rpm/Makefile, rpm/fedora-29/Dockerfile
Fedora 29 isn't scheduled to GA until [23-10-2018](https://fedoraproject.org/wiki/Releases/29/Schedule) but let's get ahead of the curve and start building this in our nightly pipelines.
Relates to https://github.com/docker/for-linux/issues/430
=> Add initial scripts for Fedora 29

deb/Makefile, deb/ubuntu-cosmic/Dockerfile
Cosmic isn't scheduled for GA until [October 18, 2018](https://wiki.ubuntu.com/Releases) but let's go ahead and add the scripts to get ahead of the curve.
~Biggest change is a shift from `btrfs-tools` -> `libbtrfs-dev`, which was already done for Debian Buster here https://github.com/docker/docker-ce-packaging/pull/113~
=> Add initial scripts for Ubuntu Cosmic (18.10)

rpm/Makefile, rpm/fedora-29/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/212 for 18.09
Relates to https://github.com/docker/for-linux/issues/430
Like https://github.com/docker/docker-ce-packaging/pull/255, probably will be for 18.09.1
```
git checkout -b 18.09_backport_fedora29 upstream/18.09
git cherry-pick -s -S -x 42f5f2f4384f1699fbe55746d53718016cd6fb87
```
=> [18.09 backport] Add initial scripts for Fedora 29

deb/Makefile, deb/ubuntu-cosmic/Dockerfile
Backport of https://github.com/docker/docker-ce-packaging/pull/121 for 18.09
```
git checkout -b 18.09_backport_cosmic upstream/18.09
git cherry-pick -s -S -x 3228c358954810ad1664dbf1d96c7e55655e8850
```
=> [18.09 backport] Add initial scripts for Ubuntu Cosmic (18.10)

deb/Makefile, deb/common/rules, systemd/00-socket-activation.conf, systemd/docker.service, systemd/docker.socket
Re-adds the docker.socket file for debian based distributions.
Closes https://github.com/moby/moby/issues/38119
Utilizes a `systemd` drop in file to have socket activation only for debian based distributions.
=> Add the docker.socket back in

deb/Makefile, deb/common/rules, systemd/00-socket-activation.conf, systemd/docker.service, systemd/docker.socket
Re-adds the docker.socket file for debian based distributions.
This is a backport of #257 
(cherry picked from commit 69bd2eea398e0396c24f97d0697f9befd0f2464e)
=> [18.09] Add the docker.socket back in

rpm/SPECS/docker-ce.spec
This requirement was originally added in 86f76496ce33bd6eff1737348bc44add4723ddd2 (https://github.com/docker/docker-ce-packaging/pull/75), but got removed in the migration to the new image-based packaging.
Commit f2ceca98823548e401c6cca125b7057df28c4892 (https://github.com/docker/docker-ce-packaging/pull/172) added this requirement back for `.deb` packages, but did not include the same changes for RPMs.
This patch adds back the requirement for RPM packages as well.
=> [18.09] Add libseccomp requirement for rpm packages

rpm/SPECS/docker-ce.spec
During the migration to "image based builds", some dependencies were removed.
This patch brings back those dependencies.
=> [18.09] Add back requirements that were removed in the migration

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
The RPM packages list containerd as a hard dependency. While having containerd installed allows certain features (e.g., allow you to run `docker engine activate`), this should not be a requirement for installing the Docker CLI, as it limits the use of this package for situations where the CLI is installed to connect to a remote daemon.
This patch removes the containerd dependency from the RPM packages (the deb packages don't have this dependency, so no change is needed in those packages)
=> Remove containerd dependency from CLI

deb/common/control
Forward-port of https://github.com/docker/docker-ce-packaging/pull/172 to master
Minor conflict because https://github.com/docker/docker-ce-packaging/pull/210 was merged in a different order, but trivial to fix;
```patch
diff --cc deb/common/control
index b2b566e,f49bde0..0000000
--- a/deb/common/control
+++ b/deb/common/control
@@@ -16,8 -15,8 +16,13 @@@ Vcs-Git: git://github.com/docker/docker
Package: docker-ce
Architecture: linux-any
++<<<<<<< HEAD
+Depends: docker-ce-cli, containerd.io, iptables, ${shlibs:Depends}
+Recommends: aufs-tools,
++=======
+ Depends: docker-ce-cli, containerd.io, iptables, libseccomp2 (>= 2.3.0), ${shlibs:Depends}
+ Recommends: abufs-tools,
++>>>>>>> f2ceca9... Add explicit dependency for libseccomp2
ca-certificates,
cgroupfs-mount | cgroup-lite,
git,
``` …
=> [master] Add explicit dependency for libseccomp2

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
backport of https://github.com/docker/docker-ce-packaging/pull/268 for 18.09
The RPM packages list containerd as a hard dependency. While having containerd installed allows certain features (e.g., allow you to run `docker engine activate`), this should not be a requirement for installing the Docker CLI, as it limits the use of this package for situations where the CLI is installed to connect to a remote daemon.
This patch removes the containerd dependency from the RPM packages (the deb packages don't have this dependency, so no change is needed in those packages)
For reference; I checked if the `.deb` packages also had this requirement, but they don't seem to;
```bash
curl -o docker.deb https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce-cli_18.09.0~3-0~ubuntu …
```
=> [18.09 backport] Remove containerd dependency from CLI

rpm/SPECS/docker-ce-cli.spec
The CLI package does not provide the functionality of the "selinux" and "engine" packages (it does _conflict_ with older engine packages though).
This removes the "obsoletes" from the CLI package, as the Engine package already obsoletes the other ones.
=> Remove obsolete "selinux" and "engine" packages from CLI rpm

deb/Makefile, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-ce.spec, systemd/00-socket-activation.conf, systemd/docker.service
Removes the systemd drop-in unit file for socket activation and instead
prefers socket activation by default for both RHEL based and DEBIAN
based distributions.
Socket activation for RHEL based distributions was tested on CentOS 7 and Fedora 28.
=> Add socket activation for RHEL based distributions

deb/Makefile, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-ce.spec, systemd/00-socket-activation.conf, systemd/docker.service
Removes the systemd drop-in unit file for socket activation and instead
prefers socket activation by default for both RHEL based and DEBIAN
based distributions.
Socket activation for RHEL based distributions was tested on CentOS 7 and Fedora 28.
(cherry picked from commit 91c85cd38197b9d92d5b3e8a1b577d3178d73fcc)
=> [18.09] Add socket activation for RHEL based distributions

systemd/docker.service
Without this the docker.socket would not start by default when starting
the docker.service leading to failures to start.
Closes https://github.com/docker/for-linux/issues/509
=> Add docker.socket requirement for docker.service

rpm/fedora-27/docker-ce.spec, rpm/fedora-28/docker-ce.spec
backport of https://github.com/docker/docker-ce-packaging/pull/259 for 18.09. Cherry-pick was clean
These were leftovers from https://github.com/docker/docker-ce-packaging/pull/41, and were removed from Fedora 26 in https://github.com/docker/docker-ce-packaging/pull/42, but still present in Fedora 27, 28
Note that these files can probably be removed altogether, but I'm looking at some differences between the old and new ones, so I'll do that in a follow up
=> [18.09 backport] Remove remnants from telemetry plugin from Fedora 27, 28

rpm/SPECS/docker-ce-cli.spec
Backport of https://github.com/docker/docker-ce-packaging/pull/270 for 18.09
The CLI package does not provide the functionality of the
"selinux" and "engine" packages (it does _conflict_ with
older engine packages though).
This removes the "obsoletes" from the CLI package, as the
Engine package already obsoletes the other ones.
(cherry picked from commit d4e1ddb963a43ff9f0a06e4ed1b37307c8f26a17)
=> [18.09 backport] Remove obsolete "selinux" and "engine" packages from CLI rpm

deb/common/docker-ce.docker.default, deb/common/docker-ce.docker.init, deb/common/docker-ce.docker.upstart, deb/common/docker-ce.prerm, deb/common/rules
Support was removed in 662e248f680eb49a9951a8b34125506b8f82dfed.  The removal breaks usage on Debian derivatives that do not use `systemd` (see https://github.com/docker/for-linux/issues/482).
=> Restore SysVinit and Upstart support

deb/common/docker-ce.docker.default, deb/common/docker-ce.docker.init, deb/common/docker-ce.docker.upstart, deb/common/docker-ce.prerm, deb/common/rules
Cherry picked from #286 
This was removed in 662e248f680eb49a9951a8b34125506b8f82dfed.  The
removal breaks usage on Debian derivatives that do not use systemd
(see https://github.com/docker/for-linux/issues/482).
cc @paddy-hack
(cherry picked from commit 196c4028288ad241f52201d0f171c251ed13b98f)
=> [master] Restore SysVinit and Upstart support

Jenkinsfile
We don't produce packages for these anymore so there's no real use in testing them anymore.
=> [master] Remove s390x and ppc64le from the testing matrix

rpm/SPECS/docker-ce.spec
Forward-porting https://github.com/docker/docker-ce-packaging/pull/266 to master
This requirement was originally added in 86f76496ce33bd6eff1737348bc44add4723ddd2,
but got removed in the migration to the new image-based packaging.
Commit f2ceca98823548e401c6cca125b7057df28c4892 added this requirement
back for `.deb` packages, but did not include the same changes for
RPMs.
This patch adds back the requirement for RPM packages as well.
=> [master] Add libseccomp requirement for rpm packages

deb/common/control, rpm/SPECS/docker-ce.spec
Hardcodes the requirement for containerd.io to be greater than or equal to 1.2.2
=> Require a containerd.io version >= 1.2.2

deb/common/control, rpm/SPECS/docker-ce.spec
Reverts docker/docker-ce-packaging#289
Had a talk with @thaJeztah and @seemethere about this and worked out that we ought to have containerd.io as part of the install and upgrade process of the docker-ce engine explicitly for the admin who installs this. Documentation will be updated to reflect this expectation.
=> Revert "Require a containerd.io version >= 1.2.2"

systemd/docker.service
backport of #297 for 18.09
fixes https://github.com/docker/for-linux/issues/556 for 18.09
containerd is now running as a separate service, and should no longer be started as a managed child-process of dockerd.
The dockerd service already specifies that it should be started `After` the containerd.service, but there is still a race condition, where containerd is started, but its socket is not yet created.
In that situation, `dockerd` detects that the containerd socket is missing, and will start a new instance of containerd (as a managed child-process), which causes live-restore to fail.
This patch explicitly sets the `--containerd` daemon option. If this option is set, `dockerd` will not start a new instance of containerd.
=> [18.09 backport] systemd: set --containerd socket patch to prevent race-condition

systemd/docker.service
containerd is now running as a separate service, and should no longer be started as a managed child-process of dockerd.
The dockerd service already specifies that it should be started `After` the containerd.service, but there is still a race condition, where containerd is started, but its socket is not yet created.
In that situation, `dockerd` detects that the containerd socket is missing, and will start a new instance of containerd (as a managed child-process), which causes live-restore to fail.
This patch explicitly sets the `--containerd` daemon option. If this option is set, `dockerd` will not start a new instance of containerd.
fixes https://github.com/docker/for-linux/issues/556
=> systemd: set --containerd socket patch to prevent race-condition

rpm/SPECS/docker-ce.spec
forward-port https://github.com/docker/docker-ce-packaging/pull/267 to master.
Some conflicts, but trivial to address
```patch
diff --cc rpm/SPECS/docker-ce.spec
index e35faa9,23fabe8..0000000
--- a/rpm/SPECS/docker-ce.spec
+++ b/rpm/SPECS/docker-ce.spec
@@@ -16,10 -15,16 +16,20 @@@ Packager: Docker <support@docker.com
Requires: docker-ce-cli
Requires: container-selinux >= 2.9
+Requires: libseccomp >= 2.3
Requires: systemd-units
Requires: iptables
++<<<<<<< HEAD
++=======
+ Requires: libcgroup
+ # Should be required as well by docker-ce-cli but let's just be thorough
++>>>>>>> a6ff66f... Add back requirements that were removed in the migration
Requires: containerd.io
+ Requires: tar
+ Requires: xz
+ 
+ # Resolves: rhbz#1165615
+ Requires: device-mapper-libs >= 1.02.90-1
BuildRequires: …
```
=> [master] Add back requirements that were removed in the migration

systemd/docker.service
Backport of https://github.com/docker/docker-ce-packaging/pull/290 for the 18.09 branch. Relates to / addresses https://github.com/docker/for-linux/issues/556
ping @corbin-coleman @seemethere 
(but still in favor of setting the `--containerd` option 😉 )
=> [18.09 backport] Start docker.service after containerd.service

static/Makefile
`STATIC_VERSION` is used to denote development builds as well.
=> [master] Switch all VERSIONS to be STATIC_VERSION

rpm/Makefile, rpm/fedora-30/Dockerfile
Relates to https://github.com/docker/for-linux/issues/600
From the original issue (cc @jhford)
> Fedora has officially branched Version 30 today and might have a beta release on March 26.
> 
> I'm filing this issue to hopefully put this task on the radar, so that there might be a repository set up in time for the Fedora 30 release on April30
> 
> Release Schedule: https://fedoraproject.org/wiki/Releases/30/Schedule#Key_Milestones
=> [master] [TAR-480] Add Fedora 30, make fedora builds more generic

Jenkinsfile
This commit ensures that we test the correct branches of Docker
when making packaging changes.
(cherry picked from commit 1ef9fb3f0b2b8016b50c6c71f2d14bea16faff35)
=> [18.09] [TAR-465] Jenkinsfile: Test the correct branch

deb/Makefile, deb/common/rules, plugins/.common, plugins/app.installer, rpm/Makefile, rpm/SPECS/docker-ce-cli.spec
Adds the base functionality for providing cli-plugins in our packaging.
Adding a plugin is pretty straightforward:
1. Create a bash script in the root directory `plugins` with the extension `.installer`
2. Have the `.installer` script implement a `build` and `install_plugin` function (those are pretty self explanatory)
3. Have the `.installer` script `source "$(dirname "$0")/.common` at the beginning of the script
4. Have the `.installer` script call `build_or_install` at the end of its script
=> [TAR-352] Add initial basis for cli-plugins (docker/app)

plugins/.common, plugins/app.installer, static/Makefile, static/scripts/build-mac-cli-plugins
There was a demand so we're filling it, should now be included in the mac binaries tgz we release.
Basically adds an extra function to the `*.installer` scripts like so:
```shell
build_mac() {
}
```
- docker-app
=> [master] [TAR-552] Add function to build docker/app as mac binary

static/Makefile
Automated builds were failing because the of the `tty` flag being present.
=> [master] Remove tty flag for mac plugin builds

deb/Makefile, deb/build-deb, deb/common/control, deb/common/docker-ce.postinst, deb/common/docker-ce.prerm, deb/common/rules, deb/debian-buster/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-cosmic/Dockerfile, deb/ubuntu-disco/Dockerfile, deb/ubuntu-xenial/Dockerfile, rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/centos-7/Dockerfile, rpm/fedora-27/Dockerfile, rpm/fedora-28/Dockerfile, rpm/fedora-29/Dockerfile, rpm/fedora-30/Dockerfile
Basically a reverse of #223.
Should hopefully resolve issues:
* https://github.com/moby/moby/issues/38175
* https://github.com/docker/for-linux/issues/452
Tested with `docker engine activate` and `docker engine update`, which work as expected.
cc @andrewhsu @thaJeztah
=> [master] [TAR-610] [TAR-611] Build the daemon as part of the package building process

deb/Makefile
Without this builds will actually fail unless you specify an actual `ENGINE_DIR` make variable.
=> [TAR-618] Re-add an ENGINE_DIR var to Makefile

deb/Makefile, rpm/Makefile
Add the PLATFORM environment variable to the deb and rpm builds to have "Docker Engine - Community" in `docker version` output:
before:
```
Client:
Version:           19.03.0-beta1
API version:       1.40
Go version:        go1.12.1
Git commit:        
Built:             Mon Apr  8 10:55:21 2019
OS/Arch:           linux/amd64
Experimental:      false
Server:
Engine:
Version:          19.03.0-beta1
API version:      1.40 (minimum version 1.12)
Go version:       go1.12.1
Git commit:       62240a9677
Built:            Mon Apr  8 11:00:13 2019
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.2.5
GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc:
Version:          1.0.0-rc6+dev
GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30 …
```
=> Add PLATFORM to deb and rpm builds

deb/Makefile, rpm/Makefile
Backport of #318 for 18.09.x
Add PLATFORM to deb and rpm builds
=> [18.09] Add PLATFORM to deb and rpm builds

plugins/buildx.installer
~Depends on https://github.com/tonistiigi/buildx/pull/40~
To make sure we can consume `buildx` as part of nightly builds
=> [TAR-698] Add buildx as a plugin we build

plugins/app.installer
backport #327
```
$ git cherry-pick -s -x 5134bad
[app dd85ec9] Bump docker app to v0.8.0-beta2
Author: Silvin Lubecki <silvin.lubecki@docker.com>
Date: Fri Apr 26 14:27:17 2019 +0200
1 file changed, 1 insertion(+), 1 deletion(-)
```
=> [19.03] Bump docker app to v0.8.0-beta2

rpm/SPECS/docker-ce.spec
This takes some of the changes from the downstream EE packaging scripts to bring the specs more in line.
- systemd-units -> systemd (taken from `8bb1f0a7a395dfd979cd410b26ef47e55433de32`)
- some wording changes (taken from `a8c522a7c22c34dc354e91941377a4aadc3ddc4c`)
Remove the pre and posttrans, they weren't useful
On some distros we were encountering errors where `$1` was not being populated
for the 'pre' and 'posttrans' rpm macros, upon closer inspection it
isn't exactly clear why the pre and posttrans macro scripts were exactly
useful since the `%systemd_postun_with_restart` does exactly what those
scripts were doing.
I've tidied up the systemd macros to use `docker.service` instead of
`docker` which seems to function as we'd expect.
taken from downstream commit …
=> Sync RPM Spec with downstream EE packaging

rpm/SPECS/docker-ce.spec
version 2.9 is really old; this sets the same minimal version as is used for the containerd.io package
=> require container-selinux >= 2.74

deb/Makefile, deb/raspbian-buster/Dockerfile
This PR adds a docker file for raspbian buster and modifies the makefile to include it.  I followed the same format in the makefile as was used for raspbian-stretch and debian-buster
=> Add Raspbian buster

deb/raspbian-buster/Dockerfile, deb/raspbian-stretch/Dockerfile
When I added the raspbian buster Dockerfile yesterday I realized that the resin base Docker images are deprecated.  Balena has published a new base image to dockerhub under balenalib/rpi-raspbian which at first glance appears to be a more up to date rpi-raspbian image.  
This repo has a buster build available as balenalib/rpi-raspbian:buster so I modified the raspbian buster dockerfile to use it.  I also updated the raspbian stretch dockerfile to use balenalib/rpi-raspbian:stretch.
=> switched docker build image to balenalib/rpi-raspbian

deb/debian-buster/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-cosmic/Dockerfile, deb/ubuntu-xenial/Dockerfile, rpm/centos-7/Dockerfile, rpm/fedora-27/Dockerfile, rpm/fedora-28/Dockerfile, rpm/fedora-29/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/316 for 18.09
cherry-pick wasn't clean because ubuntu disco, and fedora 30 is not in the 18.09 branch;
```
deleted by us:   deb/ubuntu-disco/Dockerfile
deleted by us:   rpm/fedora-30/Dockerfile
```
=> [18.09 backport] Remove the pkcs11 tag, was a holdover from cli

deb/ubuntu-cosmic/Dockerfile, deb/ubuntu-disco/Dockerfile
Alternative approach for https://github.com/docker/docker-ce-packaging/pull/343 
closes https://github.com/docker/docker-ce-packaging/pull/343
fixes docker/for-linux#639
The dh_installman script calls "man" and captures its output to convert manpages
to utf8:
https://github.com/Debian/debhelper/blob/8523120dccaf5666425109da228b7e1778f15e8b/dh_installman#L298-L316
however, on minimized Ubuntu systems, man is overridden by a script that outputs
a warning message ("This  system  has been minimized by removing packages and
content ..").
As a result, all man-pages were be overwritten by that message.
This patch restores the actual `man` command before building to
work around this issue.
=> TAR-875 Fix man-pages showing "minimized" message (alternative)

deb/common/control, rpm/SPECS/docker-ce.spec
forward-port https://github.com/docker/docker-ce-packaging/commit/06b649e2b07f74a94f3dbbcb233e13177a76a929 to master (was only in the 18.09 branch)
=> [master] Bump containerd.io dep >= 1.2.2-3 (CVE-2019-5736)

deb/common/control, rpm/SPECS/docker-ce.spec
forward-port https://github.com/docker/docker-ce-packaging/commit/06b649e2b07f74a94f3dbbcb233e13177a76a929 to 19.03 (was only in the 18.09 branch)
=> [19.03 port] Bump containerd.io dep >= 1.2.2-3 (CVE-2019-5736)

rpm/SPECS/docker-ce.spec
backport of https://github.com/docker/docker-ce-packaging/pull/345 for 19.03
version 2.9 is really old; this sets the same minimal version
as is used for the containerd.io package
=> [19.03 backport] require container-selinux >= 2.74

rpm/SPECS/docker-ce.spec
backport of https://github.com/docker/docker-ce-packaging/pull/347 for 19.03
This takes some of the changes from the downstream EE packaging scripts to bring the specs more in line.
- systemd-units -> systemd (taken from `8bb1f0a7a395dfd979cd410b26ef47e55433de32`)
- some wording changes (taken from `a8c522a7c22c34dc354e91941377a4aadc3ddc4c`)
Remove the pre and posttrans, they weren't useful
On some distros we were encountering errors where `$1` was not being populated
for the 'pre' and 'posttrans' rpm macros, upon closer inspection it
isn't exactly clear why the pre and posttrans macro scripts were exactly
useful since the `%systemd_postun_with_restart` does exactly what those
scripts were doing.
I've tidied up the systemd macros to use `docker.service` instead of
`docker` which seems to …
=> [19.03 backport] Sync RPM Spec with downstream EE packaging

Jenkinsfile, Makefile, deb/Makefile, rpm/Makefile
1. A symbol `%` is not working as expected in `PHONY` targets, so
e.g. `fedora-30` or `ubuntu-cosmic` were not being rebuild each time,
because `fedora-30` and `ubuntu-cosmic` directories exists.
The fix is to explicitly mark every distro target as phony.
This also has the nice side effect of bash completion
working as it should!
2. Remove code duplication for making packages for different distros.
3. Add missing ubuntu releases (cosmic and disco).
Instead of dynamically getting list of distros to build for,
rely on the corresponding targets in sub-Makefiles. This also
ensures that deb/Makefile and rpm/Makefile will have up-to-date
list of distros included.
This also fixes the following bug:
> $ make deb
> for p in raspbian-stretch ubuntu-bionic ubuntu-disco ubuntu-xenial …
=> Assorted improvements to Makefiles

deb/ubuntu-cosmic/Dockerfile, deb/ubuntu-disco/Dockerfile
Backport of #350 to 19.03. Clean cherry-pick, no issues.
Original description follows.
----
The dh_installman script calls "man" and captures its output to convert manpages
to utf8:
https://github.com/Debian/debhelper/blob/8523120dccaf5666425109da228b7e1778f15e8b/dh_installman#L298-L316
however, on minimized Ubuntu systems, man is overridden by a script that outputs
a warning message ("This  system  has been minimized by removing packages and
content ..").
As a result, all man-pages were be overwritten by that message.
This patch restores the actual `man` command before building to
work around this issue.
addresses docker/for-linux#639
(cherry picked from commit e52fa49844d16d16b771fdbf59cb7434bbb5536e)
=> [19.03 backport] TAR-875 Fix man-pages showing "minimized" message

deb/raspbian-stretch/Dockerfile
equivalent of https://github.com/docker/docker-ce-packaging/pull/356 for 19.03
=> [19.03] switch to balenalib/rpi-raspbian because resin/rpi-raspbian is deprecated

deb/raspbian-stretch/Dockerfile
equivalent of https://github.com/docker/docker-ce-packaging/pull/356 for 18.09
=> [18.09] switch to balenalib/rpi-raspbian because resin/rpi-raspbian is deprecated

rpm/Makefile, rpm/fedora-31/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/344 for 19.03
=> [19.03 backport][TAR-849] ADDED Dockerfile for fedora-31

deb/Makefile, deb/raspbian-buster/Dockerfile, deb/raspbian-stretch/Dockerfile
Backport of;
- revert https://github.com/docker/docker-ce-packaging/pull/360 ([19.03] switch to balenalib/rpi-raspbian because resin/rpi-raspbian is deprecated) to get a clean cherry-pick
- https://github.com/docker/docker-ce-packaging/pull/349 Add Raspbian buster
- https://github.com/docker/docker-ce-packaging/pull/356 switched docker build image to balenalib/rpi-raspbian
=> [19.03 backport] Add Raspbian buster

rpm/SPECS/docker-ce.spec
backport of https://github.com/docker/docker-ce-packaging/pull/345 for 18.09
version 2.9 is really old; this sets the same minimal version
as is used for the containerd.io package
=> [18.09 backport] require container-selinux >= 2.74

static/Makefile
The GOLANG _VERSION for the cli got changed based on this commit here: https://github.com/docker/cli/commit/8560f9e8cdada7a31145bea97c43c6cefb228dc1
This would cause a failure when building with these dockerfiles.  This change fixes and gets the correct golang version
Signed-off-by: zelahi <elahi.zuhayr@gmail.com>
=> FIXED retrieving GO_VERSION from the CLI dir

static/Makefile
After https://github.com/docker/cli/pull/2044 was merged in we need to change the logic that actually grabs the `GO_VERSION` from the cli repository.
Originally cherry picked from #368 
(cherry picked from commit 0df1091054f7749b6913d312b1d9a1fdefeddcc4)
=> [19.03] [TAR-1031] FIX pathing issue with cli dir

plugins/buildx.installer
Commit 9a5aabdaff9061343a6a28e809c14164dd04f39f (https://github.com/docker/docker-ce-packaging/pull/326) removed the fixed version for this plugin, and changed it to install from "master", which made the build non-reproducible.
This patch pins the plugin to a specific tag/release again, but allow overriding by setting the `BUILDX_COMMIT` env-var.
Note that there are changes in master that are not yet in the v0.3.0 release, so we may want to review those and check if a new release should be tagged; https://github.com/docker/buildx/compare/v0.3.0...master
=> Pin buildx plugin to v0.3.0, and allow overriding

rpm/SPECS/docker-ce.spec
Noticed this failing in internal e2e tests on CentOS:
```
sudo docker engine activate --license /tmp/docker.lic
unable to determine the installed engine version. Specify which engine image to update with --engine-image: open /var/lib/docker-engine/distribution_based_engine.json: no such file or directory
```
Looks lik 09b3ac888d8d6ab625e56a458f6bd6f72b1ba0c2 (https://github.com/docker/docker-ce-packaging/pull/244) changed the name of this file from `distribution_based_engine-ce.json` to `distribution_based_engine.json` (without `-ce` suffix) for the `.deb` packages, but did not update the RPM packages accordingly.
=> RPM spec: remove -ce suffix from distribution_based_engine JSON

deb/Makefile, rpm/Makefile
Used the realpath to get the plugins directory instead of `readlink -e`, since `readlink` was not working on mac os x
Signed-off-by: Zuhayr Elahi <elahi.zuhayr@gmail.com>
=> [master] realpath for plugins directory

plugins/buildx.installer
(cherry picked from commit 41dfc516cd50f570d6184aaad05b4efd4b04f4c3)
#387 is the master equivalent
=> [19.03 backport] plugins: pin buildx to v0.3.1

deb/common/control
To remedy issues found for users not running `amd64`, ex: https://github.com/raspberrypi/linux/issues/3021
=> deb: Only recommend aufs-tools on amd64

.unir.yml
I'm leaving Docker Inc. so it'd probably be best to remove me from the
automerge capabilities. I've also taken the liberty to remove other old
maintainers.
=> unir: Remove old maintainers, add new ones

deb/Makefile
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
=> Add build target for ubuntu-eoan

deb/Makefile, rpm/Makefile
Looks like these were left behind in https://github.com/docker/docker-ce-packaging/pull/411
relates to https://github.com/docker/cli/issues/2213
=> Remove some remnants related to image-based builds

Jenkinsfile
This caused CI to build the engine from master, which has some changes that makes building on this branch fail.
this should help https://github.com/docker/docker-ce-packaging/pull/419 pass
=> [19.03] Jenkinsfile: fix image-based engine using wrong branch

.gitignore, deb/Makefile, rpm/Makefile
follow- up to:
- https://github.com/docker/docker-ce-packaging/pull/411 Remove image-based build (for docker engine activate)
- https://github.com/docker/docker-ce-packaging/pull/420 Remove some remnants related to image-based builds
relates to https://github.com/docker/cli/pull/2207 
relates to https://github.com/docker/cli/issues/2213
=> Remove more remnants from image-based engine

static/Makefile
Related to https://github.com/docker/cli/pull/2362
=> Fix windows exe extension not added by docker/cli cross build scripts.

deb/common/rules
This variable was added in 09b3ac888d8d6ab625e56a458f6bd6f72b1ba0c2 (https://github.com/docker/docker-ce-packaging/pull/314) but appears to be unused.
=> deb: remove unused DOCKER_GOPATH variable

LICENSE
This repository was missing a license, but since it's been created mostly from bits of `github.com/docker/docker`, I figured that license was probably appropriate for this top-level (since the individual vendored directories should have their `LICENSE` files intact anyhow).
A quick `diff` to show that it's 100% identical:
```console
$ diff -u \
<(curl -fsSL 'https://github.com/docker/docker/raw/master/LICENSE') \
<(curl -fsSL 'https://github.com/tianon/docker-ce-packaging/raw/license/LICENSE')
$ 
```
See also https://github.com/docker/docker-ce/pull/103. :+1:
=> Add LICENSE (copy of docker/docker's Apache-2.0 file)

Makefile, deb/Makefile, deb/build-deb, deb/gen-deb-ver, rpm/Makefile, rpm/gen-rpm-ver, static/Makefile, static/gen-static-ver, static/hash_files, static/scripts/build-cli-plugins
opening as draft to see if I broke anything so far; I'll update the description later
=> more cleaning up

systemd/docker.socket
PartOf deactivates the socket whenever the service get deactivated.
The socket unit however should be active nevertheless, so that the
docker service can be started again through socket activation.
Based on the original patch in upstream moby/moby by Max Harmathy (https://github.com/moby/moby/pull/37470).
Fixes https://github.com/moby/moby/issues/37468
=> Don't disable socket activation when stopping docker service

README.md
Noticed that we don't list Ubuntu 19.10 in the README but we do build packages for it.
=> Update README to include Ubuntu 19.10

rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/centos-8/Dockerfile
- Enable PowerTools repo
- Disable building btrfs, which is no longer supported on
CentOS/RHEL
=> Fix CentOS 8 build

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
From the [RPM mailinglist][1]:
> `$RPM_BUILD_ROOT` is the official, supported, mechanism for getting the
> value of the configured build root in a build scriptlet.
>
> `%{buildroot}` may be changed in the future w/o warning. Not that I'm planning
> on that, but you've been warned.
The built-in macros for paths all have a leading slash, so removing slashes that were manually added before them.
Use the [built-in macros][2] and env-vars for some paths:
- Use `%{_libexecdir}` macro, instead of `/usr/libexec`
- Use `%{_datadir}` instead of `/usr/share`
- Use `%{_specsdir}` instead of `/root/rpmbuild/SPECS`
- Use `$RPM_BUILD_DIR` instead of `/root/rpmbuild/BUILD`
- Use `$RPM_SOURCE_DIR` instead of `/root/rpmbuild/SOURCES`
[1]: https://www.redhat.com/archives/rpm-list/2002-July/msg00121.html …
=> rpm: various fixes and clean-ups

rpm/centos-7/Dockerfile, rpm/centos-8/Dockerfile
This repository is only specified in the aarch64 (arm64) images,
and therefore was not caught in CI.
Bringing back the fix that was previously there, to prevent failures:
#9 [stage-1 4/6] RUN yum-builddep -y /root/rpmbuild/SPECS/*.spec
#9 0.982 Loaded plugins: fastestmirror, ovl
#9 1.177 Enabling base-source repository
#9 1.177 Enabling extras-source repository
#9 1.178 Enabling updates-source repository
#9 1.179 Loading mirror speeds from cached hostfile
#9 1.181  * base: d36uatko69830t.cloudfront.net
#9 1.182  * extras: d36uatko69830t.cloudfront.net
#9 1.182  * updates: d36uatko69830t.cloudfront.net
#9 2.272 http://vault.centos.org/altarch/7/extras/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
#9 2.272 Trying other mirror.
#9 2.273 To address this issue please refer …
=> CentOS: fix failing repository on aarch64 (arm64)

rpm/SPECS/docker-ce.spec
devicemapper is now an optional configuration, so we shouldn't make it a required dependency.
=> rpm: remove devicemapper requirement

Jenkinsfile, README.md, deb/Makefile, deb/ubuntu-focal/Dockerfile
carry of https://github.com/docker/docker-ce-packaging/pull/443
closes https://github.com/docker/docker-ce-packaging/pull/443
=> Add Ubuntu 20.04 Focal Fossa

plugins/buildx.installer
this should help with building older versions of the plugin with Go 1.13
=> [master] plugins/buildx: force go modules to use vendor mode

Makefile
to address https://github.com/docker/docker-ce-packaging/pull/433#issuecomment-613427895
we should have a look why this target is in the main makefile, and why we don't use `make -C static clean` (e.g.)
=> Makefile: chown engine dir during cleanup

rpm/SPECS/docker-ce.spec
cherry-pick of https://github.com/docker/docker-ce-packaging/pull/410 for master
add optional requirement for nftables on RHEL8+ derivatives
(cherry picked from commit cfc7f43d3ed851510b3cd994145a322499aa3767)
=> [master] RHEL8 iptables build fix (#410)

Jenkinsfile
extracted from https://github.com/docker/docker-ce-packaging/pull/457
The release branches have moved back to the upstream docker/docker
repository, so we should use that as source instead of the docker/engine
fork (and rely on it being synced with upstream)
=> [master] Jenkinsfile: use docker/docker instead of docker/engine

deb/debian-buster/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-buster/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-disco/Dockerfile, deb/ubuntu-eoan/Dockerfile, deb/ubuntu-xenial/Dockerfile
This was needed for Ubuntu 20.04, but doesn't hurt to use for other versions as well.
=> [master] deb: use DEBIAN_FRONTEND=noninteractive for all dockerfiles

deb/debian-buster/Dockerfile, deb/debian-stretch/Dockerfile, deb/raspbian-buster/Dockerfile, deb/raspbian-stretch/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-disco/Dockerfile, deb/ubuntu-eoan/Dockerfile, deb/ubuntu-xenial/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/468 to keep the diff with master smaller
This was needed for Ubuntu 20.04, but doesn't hurt to use
for other versions as well.
=> [19.03 backport] deb: use DEBIAN_FRONTEND=noninteractive for all dockerfiles

static/Makefile
containerd-shim-runc-v2 is used in cgroup v2 mode
=> static: add containerd-shim-runc-v2

static/Makefile
dockerd-rootless-setuptool.sh was added to Moby in https://github.com/moby/moby/pull/40950
=> docker-rootless-extras: add dockerd-rootless-setuptool.sh

deb/common/control
Quoting from https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends (as a refresher/context):
> `Recommends`
> > This declares a strong, but not absolute, dependency.
> >
> > The `Recommends` field should list packages that would be found together with this one in all but unusual installations.
>
> `Suggests`
> > This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.
My justification for this change, given that context, is that `aufs` hasn't been the default graph driver for …
=> Downgrade "aufs-tools" and "cgroupfs-mount" to "Suggests"

.gitignore, Jenkinsfile, Makefile, common.mk, deb/Makefile, deb/README.md, rpm/Makefile, rpm/README.md, static/Makefile
Various changes in this PR:
- remove the VERSION from the Jenkinsfile, as it was just to set a default (which is already defined in the Makefile)
- use upstream https://github.com/docker/docker (https://github.com/moby/moby) repository to fetch the source, and add Makefile variables to allow overriding the repository and reference (branch/tag/commit) to build from
- Add `DOCKER_CLI_REPO`, `DOCKER_ENGINE_REPO`, `REF`, `DOCKER_CLI_REF` and `DOCKER_ENGINE_REF` make variables to allow overriding the repository and  reference to build from.
- if an `ENGINE_DIR` or `CLI_DIR` is specified, copy the source instead of cloning (to keep the source in a fixed location)
=> [master] fetch source from upstream docker/docker repository

deb/common/control, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-ce-rootless-extras.spec, rpm/SPECS/docker-ce.spec
```console
$ dpkg -c ./docker-ce-rootless-extras_0.0.0-20200611183532-31822ff745-0~ubuntu-eoan_amd64.deb
drwxr-xr-x root/root         0 2020-06-12 15:55 ./
drwxr-xr-x root/root         0 2020-06-12 15:55 ./usr/
drwxr-xr-x root/root         0 2020-06-12 15:55 ./usr/bin/
-rwxr-xr-x root/root     11724 2020-06-12 15:55 ./usr/bin/dockerd-rootless-setuptool.sh
-rwxr-xr-x root/root      3138 2020-06-12 15:55 ./usr/bin/dockerd-rootless.sh
-rwxr-xr-x root/root  15741392 2020-06-12 15:55 ./usr/bin/rootlesskit
-rwxr-xr-x root/root   9344264 2020-06-12 15:55 ./usr/bin/rootlesskit-docker-proxy
drwxr-xr-x root/root         0 2020-06-12 15:55 ./usr/share/
drwxr-xr-x root/root         0 2020-06-12 15:55 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-06-12 15:55 …
```
=> Add docker-ce-rootless-extras deb & rpm

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
I'm trying to integrate docker-ce directly to a customized fedora live-image.
Currently it fails as shadow-utils (which provides groupadd) gets installed after docker-ce-cli.
BTW:
This might have to be fixed for deb packages too.
I've noticed that in deb the docker-ce creates the docker group.
Wouldn't that be correct for rpm too?
=> docker-ce-cli lacks dependency to groupadd

deb/common/control, deb/common/rules
Debian did not have AppArmor available until Debian 7 "Wheezy", and not have it enabled by _default_ until Debian 10 "Buster". The packaging scripts did not add AppArmor as recommended dependency for that reason (https://github.com/moby/moby/commit/eee1efcfd6c46dbdc5da02ca12722e399a56bb12 / https://github.com/moby/moby/pull/12111).
Now that Debian 10 "Buster" is the current stable, and older releases reached EOL, we can remove the special handling for Debian/Ubuntu, and unconditionally add apparmor as a recommended dependency.
Fixes https://github.com/docker/for-linux/issues/974
=> [master] deb: add apparmor as "recommends" on Debian as well

systemd/docker.service
See: https://github.com/moby/moby/pull/41297
By adding multi-user.target to the After list on the unit file, we get rid of a dependency chain that forces multi-user.target (and therefore a graphical desktop) to wait for network-online.target. This sped up my boot sequence by 9 seconds, while maintaining the same functionality.
=> systemd: add multi-user.target to After list

deb/common/control
follow-up to https://github.com/docker/docker-ce-packaging/pull/487 https://github.com/docker/docker-ce-packaging/pull/487#discussion_r459638558
Formatted the file with the `wrap-and-sort` script, but kept the comments that are in the file (which are stripped by the wrap-and-sort script); https://manpages.debian.org/buster/devscripts/wrap-and-sort.1.en.html
=> [master] deb: format deb/common/control with wrap-and-sort

plugins/buildx.installer
Some features of buildx may still be "experimental" / non-final, but we can call those out individually if needed.
This change removes the requirement to enable "experimental" mode in the cli configuration file, so that it's easier for users to try buildx.
=> plugins: don't require "experimental" for buildx

Makefile, scripts/checkout.sh
follow up to https://github.com/docker/docker-ce-packaging/pull/457
Before this change:
make clean
time make checkout
git clone -q "https://github.com/docker/cli.git" src/github.com/docker/cli
git clone -q "https://github.com/docker/docker.git" src/github.com/docker/docker
69.16 real        15.69 user         9.69 sys
After this change:
make clean
time make checkout
...
From https://github.com/docker/docker
* branch            HEAD       -> FETCH_HEAD
git -C src/github.com/docker/docker checkout -q FETCH_HEAD
14.73 real         1.35 user         2.37 sys
=> [master] Makefile: use shallow clone

plugins/buildx.installer
full diff: https://github.com/docker/buildx/compare/v0.4.1...v0.4.2
- bake: fix parsing json config with hcl v2
- bake: update go-cty to pull in more stdlib funcs
- bake: ensure --builder is wired from root options
- build: support cacheonly exporter
- build: improve error checking on load
- build: remove warning for multi-platform iidfile
=> [master] plugins: update buildx to v0.4.2

deb/debian-buster/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-xenial/Dockerfile
mk-build-deps does not seem to be updating the cache by itself, and
because of that may be installing packages using an outdated package index
if the previous layer is in the build-cache:
#6 [stage-1 2/8] RUN apt-get update && apt-get install -y curl devscripts e...
#6 CACHED
#8 [stage-1 3/8] COPY common /root/build-deb/debian
#8 CACHED
#9 [stage-1 4/8] RUN mk-build-deps -t "apt-get -o Debug::pkgProblemResolver...
=> [master] deb: update apt cache before running mk-build-deps

plugins/buildx.installer
cherry-picks of:
- https://github.com/docker/docker-ce-packaging/pull/439 [master] Bump buildx to master to check if it builds on the CI
- https://github.com/docker/docker-ce-packaging/pull/460 [master] buildx: use v0.4.1
- https://github.com/docker/docker-ce-packaging/pull/495 [master] plugins: update buildx to v0.4.2
=> [19.03 backport] bump buildx to v0.4.2

deb/common/control, rpm/SPECS/docker-ce.spec
Relates to https://github.com/moby/moby/pull/41210
The engine now defaults to the "io.containerd.runc.v2" shim, which is only available in containerd v1.3.0 and up.
Opening as draft, because no containerd.io v1.3.x packages are available yet, so verification will likely fail
=> [master] Update minimum containerd.io version to v1.3.0

deb/Makefile, rpm/Makefile
Similar PR is opened in docker-ce  - https://github.com/docker/docker-ce/pull/659
Objective is to allow docker-ce-packaging to build/troubleshoot for specific distros from top directory.
e.g.-
for rpm- RHEL_RELEASES= CENTOS_RELEASES= FEDORA_RELEASES=centos-8 make rpm
for deb- RASPBIAN_VERSIONS= UBUNTU_VERSIONS= DEBIAN_VERSIONS=ubuntu-xenial make deb
Signed-off-by: Alok Kumar <alok232549@gmail.com>
=> To allow build for selective distros from top directory

deb/Makefile, rpm/Makefile
backport of https://github.com/docker/docker-ce-packaging/pull/500
cherry-pick wasn't clean because default distros differ in this branch, but easy to resolve
e.g.-
for rpm- RHEL_RELEASES= CENTOS_RELEASES= FEDORA_RELEASES=centos-8 make rpm
for deb- RASPBIAN_VERSIONS= UBUNTU_VERSIONS= DEBIAN_VERSIONS=ubuntu-xenial make deb
=> [19.03 backport] To allow build for selective distros from top directory.

static/Makefile
Follow-up to the discussion in https://github.com/docker/docker-ce-packaging/pull/465#issuecomment-706133455.
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
(cherry picked from commit 912015018bf457c02afd87723fb8a7e42fee9a2f)
=> [19.03 backport] static: add containerd-shim-runc-v2

deb/common/control, rpm/SPECS/docker-ce.spec
Docker v20.10 ships with containerd.io v1.4.x, so setting the minimum required version to v1.4.1 (current containerd.io release), as we won't test / support older versions of containerd (and runc).
relates to https://github.com/moby/moby/pull/40982, https://github.com/moby/moby/pull/41450
relates to https://github.com/moby/moby/pull/41563
=> [master] Update minimum containerd.io version to v1.4.1

systemd/docker.service
dockerd currently sets the oom-score-adjust itself. This functionality was added when we did not yet run dockerd as a systemd service. Now that we do, it's better to instead have systemd handle this.
=> systemd: set OOMScoreAdjust for dockerd

deb/Makefile, deb/ubuntu-groovy/Dockerfile
Hi folks,
I am posting this to see what I can do to encourage `docker-ce` to be packaged and ready for use when Ubuntu 20.10 "Groovy Gorilla" is released (which will be [22 October](https://discourse.ubuntu.com/t/groovy-gorilla-release-schedule/15531)).
Apologies if posting this PR isn't the right way to do so. There are no issues enabled for this repository, so this was the only real way to reach out.
Please note that this is not building at the moment, owing to an error which has something to do with constructing man pages?
If interested, please see the full output of my `make ubuntu-groovy` run below (the relevant portion is at the very end):
<details>
```console
% make ubuntu-groovy              
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine …
```
=> Add Ubuntu 20.10 "Groovy Gorilla"

systemd/docker.service
carries https://github.com/docker/docker-ce-packaging/pull/365
closes https://github.com/docker/docker-ce-packaging/pull/365
fixes to https://github.com/docker/for-linux/issues/678
When using the BindTo directive, Docker is permanently stopped by systemd
when containerd is temporarily killed and restarted;
Using `Requires` achieves mostly the same, but defines a weaker dependency;
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Requires=
> Requires=
>
> .. If this unit gets activated, the units listed will be activated as well.
> If one of the other units fails to activate, and an ordering dependency
> After= on the failing unit is set, this unit will not be started. Besides,
> with or without specifying After=, this unit will be stopped if one of the
> other units is …
=> Do not "Bind" docker "To" containerd (carry #365)

systemd/docker.service
This reverts commit 36bb01538e1db523abf92232737cdc06903266b1, which caused the docker service to not be starting, or delayed starting the service in certain conditions.
relates to / introduced in https://github.com/moby/moby/pull/41297 / https://github.com/docker/docker-ce-packaging/pull/488 systemd: add multi-user.target to After list
fixes / addresses https://github.com/moby/moby/issues/41767 `systemctl docker start` get stuck in cloud-init
fixes / addresses https://github.com/docker/for-linux/issues/1161 Docker service not starting in centos 7.9
fixes / addresses https://github.com/docker/for-linux/issues/1162 Docker 20.10 daemon takes 5 minutes to start after reboot
fixes / addresses https://github.com/docker/machine/issues/4858 Latest docker release (20.10.0) doesn't work with …
=> Revert "systemd: add multi-user.target to After list"

plugins/buildx.installer
https://github.com/docker/buildx/releases/tag/v0.5.0
=> Bump buildx to v0.5.0

plugins/buildx.installer
Woopsies https://github.com/docker/buildx/releases/tag/v0.5.1
=> Bump buildx to v0.5.1

rpm/centos-8/Dockerfile
Backports of #470 and #513
Attempt to fix https://ci-next.docker.com/teams-core/blue/organizations/jenkins/release-packaging/detail/ce-19.03/86/pipeline
=> [19.03 backport] Backport CentOS 8 changes 

Jenkinsfile, README.md, deb/Makefile, deb/debian-bullseye/Dockerfile
=> deb: add support for building debian 11 "Bullseye"

Jenkinsfile, deb/Makefile, deb/raspbian-bullseye/Dockerfile
depends on:
This failed for me locally, but that was not on native arm, so adding a stage to the Jenkinsfile to test it in CI
```
---> Making bundle: dynbinary (in bundles/dynbinary)
/root/build-deb/engine/hack/make/.binary: line 6: /usr/local/go/bin/go: No such file or directory
/root/build-deb/engine/hack/make/.go-autogen: line 21: /usr/local/go/bin/go: No such file or directory
/root/build-deb/engine/hack/make/.binary: line 43: /usr/local/go/bin/go: No such file or directory
/root/build-deb/engine/hack/make/.binary: line 43: /usr/local/go/bin/go: No such file or directory
/root/build-deb/engine/hack/make/.binary: line 43: /usr/local/go/bin/go: No such file or directory
/root/build-deb/engine/hack/make/.binary: line 43: /usr/local/go/bin/go: No such file or directory …
```
=> deb: add support for building raspbian 11 "Bullseye"

deb/common/control
Seen this error from a bug-report (https://github.com/containerd/containerd/issues/5175);
dpkg: error processing package docker-ce (--configure):
installed docker-ce package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of docker-ce-rootless-extras:
docker-ce-rootless-extras depends on docker-ce; however:
Package docker-ce is not configured yet.
dpkg: error processing package docker-ce-rootless-extras (--configure):
dependency problems - leaving unconfigured
Errors were encountered while processing:
docker-ce
docker-ce-rootless-extras
E: Sub-process /usr/bin/dpkg returned an error code (1)
Looking through the possible options in the debian documantion:
https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-de …
=> deb: change rootless-extras to "enhance", not "depend" on docker-ce

deb/common/control
~~Hi!  This is adjusting the dependencies for `docker-ce` and `docker-ce-cli` -- moving `git` to `Recommends` on the latter (because these days, `dockerd` should only be shelling out to `git` as a not-recommended-for-use backwards compatibility measure) and~~ adding `procps` (which is needed for `docker top` and given it's only `Priority: important` not essential, might not be installed).
Both of these *do* belong in `Recommends:` (not `Depends:`) because they're both related to technically optional behavior of the CLI (although behavior that's common enough to warrant `Recommends:` instead of `Suggests:` so most users get them automatically).
I'm guessing there are more items in this list of `Recommends:` for `docker-ce` that should *also* move, but I'm not personally up-to-date enough …
=> Add "procps" to daemon "Recommends" (for "docker top")

common.mk, deb/Makefile, rpm/Makefile
This fixes a discrepancy between the rpmbuild and debbuild directory structure
and allows for a simple bundles archive target ready to be uploaded and consumed
by release-repo.
release-packaging could call these instead directly instead.
Example:
```
$ cd rpm && make rpmbuild/bundles-ce-centos-8-amd64.tar.gz
```
=> deb/rpm: add target for bundles archive as consumed by release-repo

common.mk, deb/Makefile, rpm/Makefile
See comment in common.mk
Related to https://github.com/docker/release-packaging/pull/569
=> deb/rpm: make bundles rule compatible with release-packaging arch format

deb/Makefile, rpm/Makefile
This is to fix a permissions issue with the release-packaging pipeline.
To fix issues in https://github.com/docker/release-packaging/pull/569.
Errors such as
```
tar (child): debbuild/bundles-ce-raspbian-buster-armhf.tar.gz: Cannot open: Permission denied
```
were because debbuild folder was created by docker run's `-v` giving it root ownership instead of current user.
This did not affect rpms because for some reason rpm/Makefile creates and chowns the folder correctly before calling docker run.
=> deb: create debbuild folder like it is done for rpm

rpm/fedora-34/Dockerfile
=> Fix Fedora 34 Dockerfile to exclude scan-plugin on non-x86

deb/Makefile, rpm/Makefile
Follow up to https://github.com/docker/docker-ce-packaging/pull/533
=> deb/rpm: add forgotten Ubuntu hirsute and fedora-34 distros

rpm/SPECS/docker-ce.spec
Fix https://github.com/moby/moby/issues/41799.
`docker/libnetwork` depends on `iptables` user-space executable, which is not provided by `nftables` package for EL.
Hence, with the current RPM spec, some CentOS 8 installations fail to start Docker daemon, unless server admins explicitly install iptables.
In order to address the issue, this PR attempts to change the spec for `docker-ce` to always require `iptables`.
=> Always require iptables for libnetwork

Makefile, deb/common/rules, plugins/app.installer, rpm/SPECS/docker-ce-cli.spec, static/Makefile
This PR uses golang 1.16 In order to build plugins for darwin/arm64.
However, docker app plugin does not build with go 1.16 (could not figure out how to disable go modules), and it was meant to be removed anyway.
ARM binaries had issues building with cgo, so as a workaround, this PR sets CGO_ENABLED=0 for arm (32 bit, aka armel/armhf) binaries only.
Related:
- https://github.com/docker/cli/pull/2993
- https://github.com/docker/release-packaging/pull/574
- https://github.com/docker/release-packaging/pull/568
- https://github.com/docker/release-repo/pull/575
=> mac: build arm64 binaries

Makefile, plugins/app.installer, static/Makefile
Bringing all commits from https://github.com/docker/docker-ce-packaging/pull/540 (except last one 5d5210745d3a566b4051eb6c92d675b52cc6be65) into 20.10 branch.
=> [20.10] mac: build arm64 binaries

common.mk, plugins/scan.installer.disabled
Version v0.8.0 of Docker Scan fixes several issue in the Linux version of the plugin.
https://github.com/docker/scan-cli-plugin/releases/tag/v0.8.0
=> Upgrade Docker Scan plugin to v0.8.0

common.mk, plugins/scan.installer.disabled
backport of https://github.com/docker/docker-ce-packaging/pull/544
=> [20.10 backport] Upgrade Docker Scan plugin to v0.8.0

rpm/Makefile, rpm/SPECS/docker-scan-plugin.spec
When building rpm (and deb) packages, binaries are built from a source tarball.
Source tarballs will only include the raw source code, but do not include the
git repository; https://github.com/docker/docker-ce-packaging/blob/c4c2d89b4e22ff484b08f138ca05b6098077590c/rpm/Makefile#L110-L116
tar -C / -c -z -f /v/scan-cli-plugin.tgz --exclude .git scan-cli-plugin
Because of this, the makefile used to build the scan-cli-plugin binaries will
not be able to determine the "commit" (and version) to set as build-time variable
to include in the `--version` output; https://github.com/docker/scan-cli-plugin/blob/3eaac3e88412543fb18767feb697e11dca21d20f/builder.Makefile#L5-L19
resulting in both `version` and `git commit` to be empty in the version output:
docker scan --version
Version:
Git commit: …
=> rpm: scan-cli-plugin: fix build-time "version" and "commit" variables

rpm/Makefile, rpm/SPECS/docker-scan-plugin.spec
backport of https://github.com/docker/docker-ce-packaging/pull/549
When building rpm (and deb) packages, binaries are built from a source tarball.
Source tarballs will only include the raw source code, but do not include the
git repository; https://github.com/docker/docker-ce-packaging/blob/c4c2d89b4e22ff484b08f138ca05b6098077590c/rpm/Makefile#L110-L116
tar -C / -c -z -f /v/scan-cli-plugin.tgz --exclude .git scan-cli-plugin
Because of this, the makefile used to build the scan-cli-plugin binaries will
not be able to determine the "commit" (and version) to set as build-time variable
to include in the `--version` output; https://github.com/docker/scan-cli-plugin/blob/3eaac3e88412543fb18767feb697e11dca21d20f/builder.Makefile#L5-L19
resulting in both `version` and `git commit` to be empty in …
=> [20.10 backport] rpm: scan-cli-plugin: fix build-time "version" and "commit" variables

deb/common/rules, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec, rpm/SPECS/docker-scan-plugin.spec
relates to https://github.com/docker/docker-ce-packaging/pull/549
Make sure that these versions are set, and match the expected versions
DEB:
debian/rules override_dh_auto_test
make[1]: Entering directory '/root/build-deb'
ver="$(engine/bundles/dynbinary-daemon/dockerd --version)"; \
test "$ver" = "Docker version 0.0.0-20210531142756-1c174ced, build 7c6a9484" && echo "PASS: daemon version OK" || echo "FAIL: daemon version ($ver) did not match"
PASS: daemon version OK
ver="$(cli/build/docker --version)"; \
test "$ver" = "Docker version 0.0.0-20210531142756-1c174ced, build 1c174ced" && echo "PASS: cli version OK" || echo "FAIL: cli version ($ver) did not match"
PASS: cli version OK
ver="$(/usr/libexec/docker/cli-plugins/docker-scan docker-cli-plugin-metadata | awk '{ gsub(/[",:]/,"")}; $1 …
=> Add checks for binary versions set through build-time variables

deb/common/rules, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec, rpm/SPECS/docker-scan-plugin.spec
Commit 928a8f2b578a782f902b64d223f06ff423afd736 (https://github.com/docker/docker-ce-packaging/pull/551) added a check for binary set through build-time variables, but I messed up, and forgot to add a non-zero exit code. As a result the exit code was the exit code of the "echo", which would always be successful.
This also revealed a missing check for "target architecture": the scan cli plugin is only built on x86, so the version check should not be performed on other architectures.
relates to https://github.com/docker/docker-ce-packaging/pull/553#issuecomment-873409190
=> Fix binary version checks masking failure exit code

rpm/SPECS/docker-ce.spec
taken from https://github.com/docker/docker-ce-packaging/pull/554
Trying to fix
+ echo 'Install tini version de40ad007797e0dcd8b7126f27bb87401d224240'
+ git clone https://github.com/krallin/tini.git /go/tini
Install tini version de40ad007797e0dcd8b7126f27bb87401d224240
Cloning into '/go/tini'...
+ cd /go/tini
+ git checkout -q de40ad007797e0dcd8b7126f27bb87401d224240
+ cmake .
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd
error: Bad exit status from /var/tmp/rpm-tmp.Dl5CDf (%build)
According to https://bugs.centos.org/view.php?id=18212, upgrading to libarchive-3.3.3-1.el8.x86_64
should resolve the problem.
(cherry picked from commit 78242140d7f85863e8a8e3a133f3ebf73b9596ca)
Signed-off-by: Sebastiaan …
=> [20.10] Add libarchive build-dep to fix missing archive_write_add_filter_zstd

deb/common/rules
follow-up to https://github.com/docker/docker-ce-packaging/pull/520#discussion_r555901971
=> deb: remove redundant "--with systemd" option

plugins/buildx.installer
release notes: https://github.com/docker/buildx/releases/tag/v0.6.0
=> [master] update buildx to v0.6.0

plugins/buildx.installer
release notes: https://github.com/docker/buildx/releases/tag/v0.6.1
cc @thaJeztah 
=> [master] update buildx to v0.6.1

plugins/buildx.installer
backport of https://github.com/docker/docker-ce-packaging/pull/561 and https://github.com/docker/docker-ce-packaging/pull/565
release notes: https://github.com/docker/buildx/releases/tag/v0.6.0
=> [20.10 backport] update buildx to v0.6.1

deb/common/control, rpm/SPECS/docker-ce-rootless-extras.spec
On Debian, `dbus-user-session` is not installed by default.
The lack of `dbus-user-session` results in a cryptic error on rootless+cgroup2+systemd: `read unix @->/run/systemd/private: read: connection reset by peer: unknown.`
ref: moby/moby#42793
=> Require `dbus-user-session` for rootless

plugins/scan.installer.disabled, rpm/SPECS/docker-ce-rootless-extras.spec, rpm/SPECS/docker-scan-plugin.spec
This fix was previously included in the rootlesskit install script
in moby, but should've been addressed by Go 1.14 and up. Unfortunately,
this does not appear the case, and go modules without proxy is still
broken on older versions of git, such as the version of git used by
CentOS 7.
relates to:
- https://github.com/docker/docker-ce-packaging/pull/553#issuecomment-913410815
- https://github.com/moby/moby/commit/3cec4b8cd42179e67dcfdda2adce03516c6a5cd1 (https://github.com/moby/moby/pull/42674)
- https://github.com/golang/go/issues/38373
=> Add workaround for CentOS 7 not working without GOPROXY

static/Makefile
This was introduced in 09541b553c2f7646626efcc2797bd92ee48a66d0 (https://github.com/docker/docker-ce-packaging/pull/554), which fixed the source-location of the docker-proxy binary, but accidentally used "dockerd.exe" as target.
fixes https://github.com/moby/moby/issues/42609
=> [master] static: windows: fix "docker-proxy.exe" being copied as "dockerd.exe"

plugins/buildx.installer
release notes: https://github.com/docker/buildx/releases/tag/v0.6.3
- Fix buildkit state volume location for Windows clients
=> [master] update buildx to v0.6.3

plugins/buildx.installer
cherry-pick of https://github.com/docker/docker-ce-packaging/pull/569 and https://github.com/docker/docker-ce-packaging/pull/579
release notes: https://github.com/docker/buildx/releases/tag/v0.6.2
- Fix connection error showing up in some SSH configurations
release notes: https://github.com/docker/buildx/releases/tag/v0.6.3
- Fix buildkit state volume location for Windows clients
=> [20.10 backport] update buildx to v0.6.3

Makefile, static/Makefile
This allows passing `CONTAINERD_VERSION` and `RUNC_VERSION` make vars to override the default version in the upstream repository's Dockerfile.
With this, it's easier to make the static packages match the latest released `containerd.io` deb/rpm (which are used by the .deb and .rpm docker-ce packages), without having to modify the upstream moby repository.
Currently, this uses the DOCKER_BUILD_OPTS make variable, which is available in the moby Makefile, but work is in progress to add `CONTAINERD_VERSION` and `RUNC_VERSION` make variables in the upstream repository. Once those changes are merged, we can update the makefile in this repository accordingly.
With this patch:
If `RUNC_VERSION` and `CONTAINERD_VERSION` are not passed, the defaults are used:
$ make \
DOCKER_BUILD_PKGS=static-linux …
=> [master] static: add option to specify containerd and runc version

Makefile, static/Makefile
backport of https://github.com/docker/docker-ce-packaging/pull/583
This allows passing `CONTAINERD_VERSION` and `RUNC_VERSION` make vars to override the default version in the upstream repository's Dockerfile.
With this, it's easier to make the static packages match the latest released `containerd.io` deb/rpm (which are used by the .deb and .rpm docker-ce packages), without having to modify the upstream moby repository.
Currently, this uses the DOCKER_BUILD_OPTS make variable, which is available in the moby Makefile, but work is in progress to add `CONTAINERD_VERSION` and `RUNC_VERSION` make variables in the upstream repository. Once those changes are merged, we can update the makefile in this repository accordingly.
With this patch:
If `RUNC_VERSION` and `CONTAINERD_VERSION` are not …
=> [20.10 backport] static: add option to specify containerd and runc version

deb/common/control, rpm/SPECS/docker-ce-rootless-extras.spec
Backport https://github.com/docker/docker-ce-packaging/pull/571
---
On Debian, `dbus-user-session` is not installed by default.
The lack of `dbus-user-session` results in a cryptic error on rootless+cgroup2+systemd:
`read unix @->/run/systemd/private: read: connection reset by peer: unknown.`
ref: moby/moby#42793
=> [20.10 backport] Require `dbus-user-session` for rootless

plugins/buildx.installer
release notes: https://github.com/docker/buildx/releases/tag/v0.7.0
=> [master] update buildx to v0.7.0

common.mk, plugins/scan.installer.disabled
backport of https://github.com/docker/docker-ce-packaging/pull/603
=> [20.10 backport] update Docker Scan version to 0.10.0

plugins/buildx.installer
backport of https://github.com/docker/docker-ce-packaging/pull/598 and https://github.com/docker/docker-ce-packaging/pull/602 for the 20.10 branch
release notes: https://github.com/docker/buildx/releases/tag/v0.7.1
=> [20.10 backport] update buildx to v0.7.1

common.mk, plugins/scan.installer.disabled
backport of https://github.com/docker/docker-ce-packaging/pull/614
(cherry picked from commit 0b78b5d3b27eba4a3b3e678a9491828403f0b91f)
=> [20.10 backport] upgrade Docker Scan to v0.15.0

systemd/docker.service
This applies the same fix as was added in https://github.com/docker/docker/commit/fe68df36fc9c85ae30af9bf53a13e8af0534e613, to address https://github.com/docker/for-linux/issues/989#issuecomment-911857268
The systemd unit only contained a `Requires=` for the `docker.socket`, but failed
to add it to `After=`. The `Requires=` option only defines that a dependency
must be present, but does not influence startup order. From the systemd docs:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Wants=
> Wants=
>
> (..)
> Note that requirement dependencies do not influence the order in which services
> are started or stopped. This has to be configured independently with the `After=`
> or `Before=` options. (...)
As a result, the `docker` service could start before the socket was …
=> [20.10] fix systemd startup order

common.mk, plugins/scan.installer.disabled
backport of https://github.com/docker/docker-ce-packaging/pull/616
(cherry picked from commit cad31fa6c8df25d9eb15c9951cdd7e448ce70487)
=> [20.10 backport] upgrade docker scan to v0.16.0

rpm/centos-8/Dockerfile
CentOS 8 reached EOL on December 31, 2021 (https://www.centos.org/centos-linux-eol/)
Repositories have moved to vault.centos.org, causing builds to fail;
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Update the Dockerfile to use quay.io/centos/centos:stream8
=> [master] CentOS 8: switch to use centos 8 stream (quay.io/centos/centos:stream8)

plugins/scan.installer.disabled, rpm/SPECS/docker-ce-rootless-extras.spec, rpm/SPECS/docker-scan-plugin.spec
backport of https://github.com/docker/docker-ce-packaging/pull/577
this is not needed (yet), but some changes may be back ported in upstream moby/moby that may cause this to be a problem, so let's prepare for that (https://github.com/moby/moby/pull/42674)
This fix was previously included in the rootlesskit install script
in moby, but should've been addressed by Go 1.14 and up. Unfortunately,
this does not appear the case, and go modules without proxy is still
broken on older versions of git, such as the version of git used by
CentOS 7.
(cherry picked from commit 9c363de294c6fe18116618428a518cbb980e01c7)
=> [20.10 backport] Add workaround for CentOS 7 not working without GOPROXY

rpm/centos-8/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/621
CentOS 8 reached EOL on December 31, 2021 (https://www.centos.org/centos-linux-eol/)
Repositories have moved to vault.centos.org, causing builds to fail;
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Update the Dockerfile to use quay.io/centos/centos:stream8
=> [20.10 backport] CentOS 8: switch to use centos 8 stream (quay.io/centos/centos:stream8)

Jenkinsfile, rpm/centos-8/Dockerfile
Some small fix-ups after https://github.com/docker/docker-ce-packaging/pull/621
This was a bit of an  oversight in https://github.com/docker/docker-ce-packaging/commit/49ff9113494665d7aff0496a6aacf54a96bc344a; when checking if the `$SUITE` variable was used elsewhere, I searched for `$SUITE`, and not for `${SUITE}`. While it looks like the variable is not used for any of the rpm-related build-scripts, it _is_ used in deb-related scripts.
Let's change it back to the previous value; just in case it will be used somewhere and causing side-effects.
The `image` field in the Jenkinsfile is not really used in this repository (other than to name the stage), but in our internal pipeline, the equivalent is used for some validation steps (to be upstreamed to this repository).
Let's update the …
=> [master] rpm/centos-8: some small fix-ups

plugins/scan.installer.disabled, rpm/SPECS/docker-ce-rootless-extras.spec, rpm/SPECS/docker-scan-plugin.spec, rpm/centos-7/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/635 for the 20.10 branch. Not strictly needed currently, but just in case go modules acts up again 🤣 
CentOS 7 comes with a very old (1.8) version of git, which is not compatible
with go modules. We previously applied this fix to individual build scripts
for rootless-extras and the scan-cli-plugin, but now that other bits are
failing as well, lets move this to the Dockerfile for this distro, so that
for other distros we can use "direct" and fetch from GitHub.
Without this, the build of docker/cli (master branch) failed with:
+ ./scripts/vendor init
+ go mod edit -modfile=vendor.mod -require=github.com/cpuguy83/go-md2man/v2@v2.0.1
+ cp man/tools.go .
+ ./scripts/vendor update
+ go mod tidy -modfile=vendor.mod
go: …
=> [20.10 backport] CentOS 7: use go-proxy to work around old git version

deb/common/rules, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec, rpm/SPECS/docker-scan-plugin.spec
relates to https://github.com/docker/docker-ce-packaging/pull/549, https://github.com/docker/docker-ce-packaging/pull/553#issuecomment-873409190
Backport of:
- https://github.com/docker/docker-ce-packaging/pull/551
- https://github.com/docker/docker-ce-packaging/pull/556
=> [20.10 backport] add checks for binary versions set through build-time variables

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
addresses one of the warnings/errors in https://github.com/docker/docker-ce-packaging/issues/639
Fixes an error reported by rpmlint:
docker-ce.x86_64: E: description-line-too-long they can run anywhere, from your laptop to the largest cloud compute instance and
docker-ce-cli.x86_64: E: description-line-too-long they can run anywhere, from your laptop to the largest cloud compute instance and
Your description lines must not exceed 80 characters. If a line is exceeding
this number, cut it to fit in two lines.
=> rpmlint: fix "E: description-line-too-long"

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
backport of https://github.com/docker/docker-ce-packaging/pull/640
addresses one of the warnings/errors in https://github.com/docker/docker-ce-packaging/issues/639
Fixes an error reported by rpmlint:
docker-ce.x86_64: E: description-line-too-long they can run anywhere, from your laptop to the largest cloud compute instance and
docker-ce-cli.x86_64: E: description-line-too-long they can run anywhere, from your laptop to the largest cloud compute instance and
Your description lines must not exceed 80 characters. If a line is exceeding
this number, cut it to fit in two lines.
=> [20.10 backport] rpmlint: fix "E: description-line-too-long"

Makefile, common.mk, deb/Makefile, deb/build-deb, deb/common/control, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-compose-plugin.spec
depends on:
Adds a package for the docker-compose cli plugin
with this:
```bash
dpkg -i ./docker-ce-cli_0.0.0-20210629140245-4a6fe51-0~ubuntu-focal_amd64.deb
dpkg -i ./docker-compose-plugin_2.0.0-beta.6~ubuntu-focal_amd64.deb
docker info --format '{{json .ClientInfo.Plugins}}' | jq .
[
{
"SchemaVersion": "0.1.0",
"Vendor": "Docker Inc.",
"Version": "v0.5.1-docker",
"ShortDescription": "Build with BuildKit",
"Name": "buildx",
"Path": "/usr/libexec/docker/cli-plugins/docker-buildx"
},
{
"SchemaVersion": "0.1.0",
"Vendor": "Docker Inc.",
"Version": "v2.0.0-beta.6",
"ShortDescription": "Docker Compose",
"Name": "compose",
"Path": "/usr/libexec/docker/cli-plugins/docker-compose"
}
]
```
```bash
rpm -i \
./docker-ce-cli-0.0.0.20210702143511.f782d13-0.el8.x86_64.rpm \ …
```
=> [master] add docker-compose-plugin package (deb, rpm)

Makefile, common.mk, deb/Makefile, deb/build-deb, deb/common/control, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-compose-plugin.spec
backport of https://github.com/docker/docker-ce-packaging/pull/553
depends on https://github.com/docker/docker-ce-packaging/pull/637
```bash
git cherry-pick -s -S -x \
d66f7a68c9cf5ecb42d7aa66c22287ea5f0241c3 \
276d806d084c0b11acf66ede0aef484049632449 \
cab7b567fdd3e7108af65ed2734820d3095d2e4d
```
Minor conflict in the first two commits, due to https://github.com/docker/docker-ce-packaging/pull/547 not being in the 20.10 branch
=> [20.10 backport] add docker-compose-plugin package (deb, rpm)

Jenkinsfile, deb/Makefile, deb/ubuntu-jammy/Dockerfile
Files are copied from Ubuntu impish, just replacing impish by jammy.
CI will be broken until a containerd.io package for jammy will be pushed in the official Docker deb repositories.
=> Add Ubuntu 22.04.

plugins/buildx.installer
backport of https://github.com/docker/docker-ce-packaging/pull/648
https://github.com/docker/buildx/releases/tag/v0.8.0
=> [20.10 backport] update buildx to v0.8.0

plugins/buildx.installer
https://github.com/docker/buildx/releases/tag/v0.8.1
=> update buildx to v0.8.1

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-scan-plugin.spec
This fixes a problem when installing the packages from local files instead of
from the package repository. The current packages had a strong dependency set
in both directions (`docker-ce-cli` requires `docker-scan-plugin`, and vice-
versa). This caused a circular dependency, which could not be resolved when
trying to install the packages offline (from downloaded rpm files);
yum install ./docker-scan-plugin-0.17.0-3.fc35.x86_64.rpm
Last metadata expiration check: 1:09:40 ago on Tue Mar  8 08:30:47 2022.
Error:
Problem: conflicting requests
- nothing provides docker-ce-cli needed by docker-scan-plugin-0.17.0-3.fc35.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
yum install ./docker-ce-cli-20.10.13-3.fc35.x86_64.rpm
Last metadata expiration check: 1:10:23 ago on Tue Mar …
=> [master] rpm: fix circular dependency between scan-cli-plugin and docker-ce-cli

common.mk
follow-up https://github.com/docker/cli/pull/3310 and https://github.com/moby/moby/pull/43431
=> [master] makefile: add PACKAGER_NAME common variable

Jenkinsfile, rpm/fedora-36/Dockerfile
addresses https://github.com/docker/for-linux/issues/1372
=> [master] rpm: add Fedora 36

deb/common/control, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-compose-plugin.spec
Follow-up to https://github.com/docker/docker-ce-packaging/pull/553
With this change, the compose-cli-plugin will automatically be installed as dependency of the cli.
This adds a "weak" dependency on the docker-compose-plugin, per the
recommendations in https://debian-handbook.info/browse/stable/sect.package-meta-information.html#id-1.8.6.7.10.10
The "recommends" dependency will be installed by default, but does allow users to opt-out
using `--no-install-recommends` to perform a lightweight installation for setups that only
need basic functionality of docker;
> (...) the “recommended” dependencies, the most important, considerably improve
> the functionality offered by the package but are not indispensable to its operation.
> (...) You should always install the “recommended” packages, …
=> [master]: deb/rpm define dependencies between docker-ce-cli and docker-compose-plugin

Jenkinsfile, rpm/fedora-36/Dockerfile
backport of https://github.com/docker/docker-ce-packaging/pull/658
(cherry picked from commit ef33edc77c304119a16ef6527b145bb6a1daca26)
=> [20.10 backport] rpm: add Fedora 36

plugins/buildx.installer
equivalent of ~https://github.com/docker/docker-ce-packaging/pull/673~ https://github.com/docker/docker-ce-packaging/pull/672 for the 20.10 branch
release notes: https://github.com/docker/buildx/releases/tag/v0.8.2
Notable changes:
- Update Compose spec used by buildx bake to v1.2.1 to fix parsing ports definition
- Fix possible crash on handling progress streams from BuildKit v0.10
- Fix parsing groups in buildx bake when already loaded by a parent group
=> [20.10] update buildx to v0.8.2

static/gen-static-ver
macOS uses the BSD flavor of `date`, which does not support the `--date` option
to set a custom time. Previously, we were using an alpine container to provide a
GNU flavor of date, which was a bit of a hack.
This patch rewrites the script to work on macOS directly, without the need of
a container:
./static/gen-static-ver . v1.2.3-dev
0.0.0-20220404154104-b815498
docker run --rm -v $(pwd):/src -w /src golang bash -c './static/gen-static-ver . v1.2.3-dev'
0.0.0-20220404154104-b815498
=> static: make gen-static-ver work natively on macOS

deb/Makefile, rpm/Makefile
The https://honnef.co/go/tools domain looks to be offline, causing projects that
do not use vendoring to fail:
go: downloading google.golang.org/protobuf v1.27.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: google.golang.org/grpc@v1.44.0 requires
google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
honnef.co/go/tools@v0.0.0-20190523083050-ea95bdfd59fc: unrecognized import path "honnef.co/go/tools": reading https://honnef.co/go/tools?go-get=1: 502 Bad Gateway
make: *** [Makefile:71: manpages] Error 1
For now, let's use the GOPROXY (we should look at making this a build-arg probably)
=> [master] Makefile: enable GOPROXY to work around vanity URL being offline

Jenkinsfile, rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/centos-9/Dockerfile
This shall be backported to branch 20.10 too.
=> [master] Build for CentOS 9.

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-scan-plugin.spec
backport of https://github.com/docker/docker-ce-packaging/pull/657
This fixes a problem when installing the packages from local files instead of
from the package repository. The current packages had a strong dependency set
in both directions (`docker-ce-cli` requires `docker-scan-plugin`, and vice-
versa). This caused a circular dependency, which could not be resolved when
trying to install the packages offline (from downloaded rpm files);
yum install ./docker-scan-plugin-0.17.0-3.fc35.x86_64.rpm
Last metadata expiration check: 1:09:40 ago on Tue Mar  8 08:30:47 2022.
Error:
Problem: conflicting requests
- nothing provides docker-ce-cli needed by docker-scan-plugin-0.17.0-3.fc35.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
yum install …
=> [20.10 backport] rpm: fix circular dependency between scan-cli-plugin and docker-ce-cli

static/Makefile
The Dockerfile for 20.10 and earlier used RUNC_COMMIT, later versions
use RUNC_VERSION. We can remove RUNC_COMMIT going forward.
=> [master] static: remove deprecated RUNC_COMMIT

deb/common/control, rpm/SPECS/docker-ce.spec
This is for the upcoming 22 release, which will ship when we have containerd.io 1.6 packages, so (as we did with previous releases), set the minimum version to the current version.
Similar to 3f2b79d15d9775302704ce3952c4ed1079fe4127 (https://github.com/docker/docker-ce-packaging/pull/506)
=> [master] set minimum containerd.io version to v1.6.4

Jenkinsfile, Makefile, common.mk, install-containerd-helpers, verify
This integrates one of the verify scripts from our internal pacakging repository
This verify step is primarily intended to verify that dependencies are defined
correctly, and available on the given distro.
Migrated from commit a712afb008b56c7572e87b2bca81f1c50022ad2b in our internal
repo (from the `ce-nightly` branch, which corresponds with `master` in the
`docker-ce-packaging` repository); https://github.com/docker/release-packaging/commit/a712afb008b56c7572e87b2bca81f1c50022ad2b
Strategy taken to preserve history:
brew install git-filter-repo
cd ~/projects
git clone https://github.com/docker/release-packaging.git release_packaging_verify
cd release_packaging_verify
git checkout ce-nightly
git filter-repo  --path verify --path install-containerd-helpers --force
cd …
=> [master] Makefile: add "verify" target to test install of packages

deb/gen-deb-ver, rpm/gen-rpm-ver
The script assumed that pre-release suffixes used the format `-tp<number>`,
`-beta<number>` or `-rc<number>`, however, it's more common (and standard
practice in SemVer) to delimit the `alpha/beta/rc` with a `.`, which allows
SemVer comparing to first sort by pre-release version (`alpha`, `beta`, `rc`),
then by the numeric suffix.
Altogether, we should consider removing this code; using `tp` as a pre-release
*before* `alpha` / `beta` is non-standard (pre-releases are named `alpha`, `beta`,
`rc`, so that they can be sorted alphabetically. Using `tp` violates that assumption,
and adds the complexity of having to add a numeric prefix to make it sort again.
Also see https://www.debian.org/doc/debian-policy/ch-controlfields.html#epochs-should-be-used-sparingly
Before:
./rpm/gen-rpm-ver . …
=> fix generating pre-release deb/rpm versions when using '.'

deb/build-deb, deb/gen-deb-ver, rpm/gen-rpm-ver, static/gen-static-ver
This unifies the logic/code for generating pseudo-versions for
nightly builds;
- Generate pseudo-version if the source repository has uncommitted changes
- Fix code to work on macOS
- Strip "v" prefix if the passed VERSION has one
The script had special handling for pre-releases, because at some point we
used `-tp` ("technical preview") as suffix for pre-releases instead of the
standard `-alpha`, `-beta`, `-rc`.
The problem arised because of that, was that comparing versions wouldn't work,
as these suffixes are compared in _alphabetical_ order (which meant that `tp`
would come "after" `beta` and `rc`). To work around this, some custom code
was added to insert a numeric version _before_ the `tp`, `beta`, and `rc`.
We no longer plan to use `-tp` for pre-releases, and instead to just use the …
=> Fix package version generation

rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce-rootless-extras.spec, rpm/SPECS/docker-ce.spec
Found this branch in my local fork, and looks like I didn't open a PR for it yet 😅 
Use the same options for creating the symlinks as for the deb packages, and
add the `-n` and `-f` options;
-n, --no-dereference        treat LINK_NAME as a normal file if
it is a symbolic link to a directory
-f, --force                 remove existing destination files
=> [master] rpm: use same options for creating symlinks as in the deb builds

static/Makefile
- relates to https://github.com/moby/moby/pull/43762
Upstream moby no longer includes the version in the built binaries, so remving it here.
=> [master] static: cross-win: remove version from bundles source

common.mk
=> [master] bump version of Compose to v2.9.0

common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.9.0
=> [master] update buildx to v0.9.0

verify
This was added as part of 6dfaf9cc43198e7f0d0f87b7bcc1d78525662882, which came
from our internal repositories, but the original commits from there didn't have
context why an upgrade was performed.
In general, it's best practice to not perform a (dist-)upgrade inside the image,
and just depend on the image maintainers to have the image being up-to-date, so
removing this step.
=> [master] verify: rpm: don't perform dnf upgrade

verify
- relates to https://github.com/docker/docker-ce-packaging/pull/729
On pre-releases of Fedora, the image may still have `rawhide` as distro-version,
which causes the verify script to fail (as download.docker.com does not have a
"rawhide" channel)
This patch forces the verify script to use the DIST_VERSION as specified in the
Dockerfile.
=> [master] verify: rpm: force release-version for Fedora pre-releases

plugins/buildx.installer
- equivalent of https://github.com/docker/docker-ce-packaging/pull/734
release notes: https://github.com/docker/buildx/releases/tag/v0.9.0
=> [20.10] update buildx to v0.9.0

Jenkinsfile, rpm/Makefile, rpm/fedora-37/Dockerfile
not yet released, but pre-release images are available
depends on:
=> [master] rpm: add Fedora 37

Jenkinsfile, rpm/Makefile, rpm/fedora-37/Dockerfile
- similar to https://github.com/docker/docker-ce-packaging/pull/729
not yet released, but pre-release images are available
similar to https://github.com/docker/docker-ce-packaging/commit/042e08aabc7669a4d544c9e451ff8ba50818f0a6, but with some differences for the 20.10 branch;
- added back DOCKER_BUILDTAGS, RUNC_BUILDTAGS
- removed `docker-b*.spec` in Dockerfile
=> [20.10 backport] rpm: add Fedora 37

common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.9.1
=> [master] update buildx to v0.9.1

static/scripts/build-cli-plugins
- relates to https://github.com/docker/docker-ce-packaging/pull/740
Docker App has been deprecated after the initial 20.10 release, and so far we
continued packaging it (to not remove features as part of a patch release).
However, the current code for docker app uses a version of golang.org/x/sys
that is incompatible with go1.18 on macOS, causing the build to fail;
go build -tags= -ldflags="-s -w -X github.com/docker/app/internal.GitCommit=9d2c67f8 -X github.com/docker/app/internal.Version=v0.9.1-beta3" -o bin/docker-app ./cmd/docker-app
vendor/golang.org/x/sys/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable …
=> [20.10] stop building deprecated docker app plugin for macOS

plugins/buildx.installer
- equivalent of https://github.com/docker/docker-ce-packaging/pull/738 for 20.10
release notes: https://github.com/docker/buildx/releases/tag/v0.9.1
=> [20.10] update buildx to v0.9.1

deb/common/rules, rpm/SPECS/docker-compose-plugin.spec
- relates to https://github.com/docker/compose/pull/9744
- relates to https://github.com/docker/compose/pull/9771
- relates to https://github.com/docker/docker-ce-packaging/pull/742
The build.Makefile was removed from the compose repository, so copying the code to build the plugin here.
=> deb, rpm: inline go build for compose

common.mk
release notes: https://github.com/docker/compose/releases/tag/v2.10.0
=> [master] update compose to v2.10.0

deb/common/rules, rpm/SPECS/docker-compose-plugin.spec
- backport of https://github.com/docker/docker-ce-packaging/pull/744
The build.Makefile was removed from the compose repository, so copying the code to build the plugin here.
(cherry picked from commit 1e3fdefd58fbc68ce97c42e33ced0b63f0a14bfb)
=> [20.10 backport] deb, rpm: inline go build for compose

deb/Makefile, deb/common/rules, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, rpm/Makefile, rpm/SPECS/docker-compose-plugin.spec, rpm/centos-7/Dockerfile, rpm/centos-8/Dockerfile, rpm/centos-9/Dockerfile, rpm/fedora-35/Dockerfile, rpm/fedora-36/Dockerfile, rpm/fedora-37/Dockerfile, rpm/rhel-7/Dockerfile
Use the default proxy, to assist with LTS distros that use old git versions but fallback on any error (instead of only on 404 and 410).
From the Go documentation; https://go.dev/ref/mod#goproxy-protocol
> List elements may be separated by commas (,) or pipes (|), which determine error
> fallback behavior. When a URL is followed by a comma, the go command falls back
> to later sources only after a 404 (Not Found) or 410 (Gone) response. When a URL
> is followed by a pipe, the go command falls back to later sources after any error,
> including non-HTTP errors such as timeouts. This error handling behavior lets a
> proxy act as a gatekeeper for unknown modules. For example, a proxy could respond
> with error 403 (Forbidden) for modules not on an approved list (see Private proxy
> serving …
=> [master] Update GOPROXY to use default with fallback

deb/Makefile, deb/common/rules, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, rpm/Makefile, rpm/SPECS/docker-compose-plugin.spec, rpm/centos-7/Dockerfile, rpm/centos-8/Dockerfile, rpm/centos-9/Dockerfile, rpm/fedora-35/Dockerfile, rpm/fedora-36/Dockerfile, rpm/fedora-37/Dockerfile, rpm/rhel-7/Dockerfile
- backport of https://github.com/docker/docker-ce-packaging/pull/745
Use the default proxy, to assist with LTS distros that use old git versions
but fallback on any error (instead of only on 404 and 410).
From the Go documentation; https://go.dev/ref/mod#goproxy-protocol
> List elements may be separated by commas (,) or pipes (|), which determine error
> fallback behavior. When a URL is followed by a comma, the go command falls back
> to later sources only after a 404 (Not Found) or 410 (Gone) response. When a URL
> is followed by a pipe, the go command falls back to later sources after any error,
> including non-HTTP errors such as timeouts. This error handling behavior lets a
> proxy act as a gatekeeper for unknown modules. For example, a proxy could respond
> with error 403 (Forbidden) …
=> [20.10 backport] Update GOPROXY to use default with fallback

verify
With this patch;
```
+ docker --version
Docker version 0.0.0-20220820144233-1163b46, build 1163b46
++ uname -m
+ '[' x86_64 = x86_64 ']'
+ docker scan --help
Usage:  docker scan [OPTIONS] IMAGE
A tool to scan your images
Options:
--accept-license    Accept using a third party scanning provider
--dependency-tree   Show dependency tree with scan results
--exclude-base      Exclude base image from vulnerability scanning
(requires --file)
-f, --file string       Dockerfile associated with image, provides more
detailed results
--group-issues      Aggregate duplicated vulnerabilities and group
them to a single one (requires --json)
--json              Output results in JSON format
--login             Authenticate to the scan provider using an
optional token (with --token), or web base
token if …
```
=> [master] verify: add minimal check for compose, buildx, scan

deb/common/rules, rpm/SPECS/docker-compose-plugin.spec
- testing https://github.com/docker/compose/pull/9776
=> [master] compose: use updated makefile

deb/Makefile, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-buildx-plugin.spec
- relates to https://github.com/docker/docker-ce-packaging/pull/749
The Makefile did not set a `%{_buildx_gitcommit}` variable, causing the version
output to show as:
docker buildx version
github.com/docker/buildx v0.9.1 %{_buildx_gitcommit}
The version output was missing the git-commit, because the deb build
tried to do a ``, but the source files used in the deb builds don't
include the git repository.
Before this:
+ docker buildx version
github.com/docker/buildx v0.9.1
With this patch
+ docker buildx version
github.com/docker/buildx v0.9.1 ed00243
Don't use bash to compile buildx, re-format the build script to match
other parts, and enable trimpath.
We could also consider enabling `-s -w` to strip debugging symbols, as
we do for other binaries.
=> [master] buildx: fix missing git-commit in version

deb/common/rules, rpm/SPECS/docker-compose-plugin.spec
- backport of https://github.com/docker/docker-ce-packaging/pull/748
compose v2.10.1 comes with an updated Makefile, allowing us again
to use the makefile for building as part of the rpm/deb scripts.
(cherry picked from commit b0621bde559156e37044da4d6f5d6f71ec739d9f)
=> [20.10 backport] compose: use updated makefile

common.mk
https://github.com/docker/compose/releases/tag/v2.11.2
=> compose: bump version to v2.11.2

common.mk
- closes #774
Supersedes #774 - v2.12.1 included a dependency that required Go 1.19 to build; v2.12.2 was released to use a fixed version of the dependency that retains Go 1.18 compatibility (needed by packaging for some versions).
https://github.com/docker/compose/releases/tag/v2.12.2
=> [master] compose: upgrade to v2.12.2

common.mk
- backport of https://github.com/docker/docker-ce-packaging/pull/770
full diff: https://github.com/docker/scan-cli-plugin/compare/v0.17.0...v0.21.0
(cherry picked from commit a41f520f22c21b2e9cffcc67f43b0d345fa953fe)
=> [20.10 backport] update scan-cli-plugin to v0.21.0

Jenkinsfile, deb/Makefile, deb/ubuntu-kinetic/Dockerfile
- backports https://github.com/docker/docker-ce-packaging/pull/779
- second commit is to sync with the other Dockerfiles in this branch (some build-tags may still be needed)
=> [20.10 backport] Add Ubuntu 22.10 Kinetic Kudu

common.mk
- backport of https://github.com/docker/docker-ce-packaging/pull/783
dep: bump snyk to v1.1054.0
full diff: https://github.com/docker/scan-cli-plugin/compare/v0.21.0...v0.22.0
(cherry picked from commit 6096cdbd5c70a3dbbdc8ed63f82d988db71861eb)
=> [20.10 backport] update scan-cli-plugin to v0.22.0

common.mk
- backport of https://github.com/docker/docker-ce-packaging/pull/787
dep: bump snyk to v1.1064.0
full diff: https://github.com/docker/scan-cli-plugin/compare/v0.22.0...v0.23.0
(cherry picked from commit bbe76c45672104781ed9411a2b0c11684ae39592)
=> [20.10 backport] update scan-cli-plugin to v0.23.0

common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.10.0-rc2
=> [master] update buildx to v0.10.0-rc2

common.mk
supersedes / closes https://github.com/docker/docker-ce-packaging/pull/806
=> bump Compose version to v2.15.1

common.mk
- release notes: https://github.com/docker/buildx/releases/tag/v0.10.0
- full diff: https://github.com/docker/buildx/compare/v0.10.0-rc2...v0.10.0
=> [master] update buildx to v0.10.0

plugins/buildx.installer
equivalent of https://github.com/docker/docker-ce-packaging/pull/812 for 20.10
- release notes: https://github.com/docker/buildx/releases/tag/v0.10.0
- full diff: https://github.com/docker/buildx/compare/v0.10.0-rc2...v0.10.0
=> [20.10] update buildx to v0.10.0

deb/Makefile, deb/build-deb, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, deb/ubuntu-kinetic/Dockerfile
- relates to https://github.com/docker/docker-ce-packaging/issues/814
It doesn't appear to be used anywhere
For easier comparing :)
We'll be using VERSION_ID in other places, so adding it in the Dockerfile makes
sure it's always present, without having to depend on /etc/os-release.
=> deb: cleanup makefile, remove unused GITCOMMIT, and pass VERSION_ID through Dockerfile

verify
This verification is still very "bare boned", but makes sure that the binaries are not completely defunct, and that installation of the package installs the expected binaries.
make IMAGE=ubuntu:jammy verify
+ verify_binaries
+ docker --version
Docker version 23.0.0-rc.2, build f163d24
++ uname -m
+ '[' aarch64 = x86_64 ']'
+ docker buildx version
github.com/docker/buildx v0.10.0 8764628
+ docker compose version
Docker Compose version v2.15.1
+ dockerd --version
Docker version 23.0.0-rc.2, build 9fd3a437
+ docker-proxy --version
docker-proxy (commit 9fd3a437) version 23.0.0-rc.2
+ containerd --version
containerd containerd.io 1.6.15 5b842e528e99d4d4c1686467debf2bd4b88ecd86
+ ctr --version
ctr containerd.io 1.6.15
+ containerd-shim --help
Usage of containerd-shim:
-address string
grpc …
=> verify: check more binaries

deb/Makefile, deb/common/rules
- relates to / addresses https://github.com/docker/docker-ce-packaging/issues/814
We already had code for this in the RPM packages, but were missing this in the deb variants. Because of this, pre-release packages used a hyphen (-) as separator for pre-releases, which get sorted as a "higher" version than a non-pre-release:
dpkg --compare-versions "0.10.0" ">>" "0.10.0-rc2" && echo "OK" || echo "KO"
KO
With this patch, the packages have a correctly formatted version, using a tilde (~) as separator for the pre-release suffix:
make DOCKER_CLI_REF=f163d2441e214176db89c63ffc557012113e28d8 DOCKER_ENGINE_REF=9fd3a437a6027637301b0952f7578644d7dff321 VERSION=23.0.0-rc.2 ubuntu-jammy
tree deb/debbuild/
deb/debbuild/
└── ubuntu-jammy
├── docker-buildx-plugin_0.10.0~rc2~ubuntu-jammy_arm64.deb
├── …
=> deb: fix plugin versions to have correct format for deb packages

deb/common/rules
- fixes https://github.com/docker/docker-ce-packaging/issues/814
This variable can be used as packaging-revision in package versions
Aligning the plugin's version with the format used for docker-ce and
docker-ce-cli, as updated in https://github.com/docker/docker-ce-packaging/commit/39772a761dfdf810cc23a1ec6084ea3100e6abf0
Before this patch:
tree deb/debbuild/
deb/debbuild/
└── ubuntu-jammy
├── docker-buildx-plugin_0.10.0~ubuntu-jammy_arm64.deb
├── docker-ce-cli_23.0.0~rc.2-1~ubuntu.22.04~jammy_arm64.deb
├── docker-ce-rootless-extras_23.0.0~rc.2-1~ubuntu.22.04~jammy_arm64.deb
├── docker-ce_23.0.0~rc.2-1~ubuntu.22.04~jammy_arm64.deb
└── docker-compose-plugin_2.15.1~ubuntu-jammy_arm64.deb
With this patch:
deb/debbuild/
└── ubuntu-jammy
├── …
=> [master] deb: buildx, compose: include packaging revision and distro version in version

deb/Makefile, deb/common/rules, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-bionic/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, deb/ubuntu-kinetic/Dockerfile
Partial (as buildx package is not built in this branch) backports of:
- https://github.com/docker/docker-ce-packaging/pull/817
- https://github.com/docker/docker-ce-packaging/pull/820
- https://github.com/docker/docker-ce-packaging/pull/822
- https://github.com/docker/docker-ce-packaging/pull/828
=> [20.10 backport] fix plugin package versioning for compose

deb/build-deb, deb/gen-deb-ver, rpm/gen-rpm-ver, static/gen-static-ver
Backports:
- https://github.com/docker/docker-ce-packaging/pull/677
- https://github.com/docker/docker-ce-packaging/pull/700
- https://github.com/docker/docker-ce-packaging/pull/701
- :warning: not including the last commit: https://github.com/docker/docker-ce-packaging//commit/f8299f20216a4e2def617f7d3605eab1d68132ee
=> [20.10 backport] [deb] fixes for version generating

plugins/buildx.installer
full diff: https://github.com/docker/buildx/compare/v0.10.0...v0.10.1
equivalent of b5546025934a5483171a590d79b7b09ae1b430eb (https://github.com/docker/docker-ce-packaging/pull/836) on master
=> [20.10] update buildx to v0.10.1

Jenkinsfile, deb/Makefile, deb/debian-bookworm/Dockerfile, deb/raspbian-bookworm/Dockerfile
Not yet released, but freeze was announced;
https://lists.debian.org/debian-devel-announce/2023/01/msg00004.html
=> deb: add Debian / Raspbian 12 "bookworm" (next stable)

common.mk
full diff: https://github.com/docker/buildx/compare/v0.10.1...v0.10.2
Signed-off-by: Romain Geissler <romain.geissler@amadeus.com>
=> [master] update buildx to v0.10.2

deb/common/docker-ce.dirs, rpm/SPECS/docker-ce.spec
- relates to https://github.com/jpetazzo/container.training/pull/625
- relates to https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/merge_requests/102
Previous versions of the engine created this directory as a side-effect of the (legacy) "key.json" file. With the removal of libtrust (and the key.json) file, that directory is no longer created.
While the precence of this directory is not needed for the daemon to function, users may expect it to be there, so it there should be no harm in creating it.
This patch adds a .dirs file to create the directory on installation for .deb; https://www.debian.org/doc/manuals/maint-guide/dother.en.html#dirs
And adds a `%dirs` directive for .rpm packages:
http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html#S3-RPM-INSIDE-DIR-DIRECTIVE
=> [master] deb, rpm: add /etc/docker directory

deb/common/docker-ce.dirs, rpm/SPECS/docker-ce.spec
- backport of https://github.com/docker/docker-ce-packaging/pull/841
- relates to https://github.com/jpetazzo/container.training/pull/625
- relates to https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/merge_requests/102
Previous versions of the engine created this directory as a side-effect of the (legacy) "key.json" file. With the removal of libtrust (and the key.json) file, that directory is no longer created.
While the precence of this directory is not needed for the daemon to function, users may expect it to be there, so it there should be no harm in creating it.
This patch adds a .dirs file to create the directory on installation for .deb; https://www.debian.org/doc/manuals/maint-guide/dother.en.html#dirs
And adds a %dirs directive for .rpm packages: …
=> [23.0 backport] deb, rpm: add /etc/docker directory

common.mk
(cherry picked from commit ea3720b0c0f8fd955dc9fddeeab411dc06bd0aa8)
=> [23.0 backport] bump compose version to v2.16.0

common.mk
backport of https://github.com/docker/docker-ce-packaging/pull/846
full diff: https://github.com/docker/buildx/compare/v0.10.2...v0.10.3
(cherry picked from commit ec8cadf15d30621e391126801dd3a19e641a24c6)
=> [23.0 backport] update buildx to v0.10.3

plugins/buildx.installer
"backport" of https://github.com/docker/docker-ce-packaging/pull/846 in case we need to do another 20.10 build
full diff: https://github.com/docker/buildx/compare/v0.10.2...v0.10.3
equivalent of ec8cadf15d30621e391126801dd3a19e641a24c6
=> [20.10 backport] update buildx to v0.10.3

common.mk
- backport of https://github.com/docker/docker-ce-packaging/pull/853
full diff: https://github.com/docker/buildx/compare/v0.10.3...v0.10.4
(cherry picked from commit d1ff577bfcf0bf9447220255504c6568b3ae5973)
=> [23.0 backport] update buildx to v0.10.4

plugins/buildx.installer
"backport" of https://github.com/docker/docker-ce-packaging/pull/853 in case we need to do another 20.10 build
full diff: https://github.com/docker/buildx/compare/v0.10.3...v0.10.4
(equivalent of commit d1ff577bfcf0bf9447220255504c6568b3ae5973)
=> [20.10 backport] update buildx to v0.10.4

common.mk
- backport of https://github.com/docker/docker-ce-packaging/pull/860
(cherry picked from commit f1df0f5f9b30dcb1be647c3558ede77e923a854f)
=> [23.0 backport] bump compose version to v2.17.0

common.mk
https://github.com/docker/compose/releases/tag/v2.17.1
=> [master] bump compose version to v2.17.1

common.mk
https://github.com/docker/compose/releases/tag/v2.17.1
see #863 
(cherry picked from commit 4e31bd971a5086ee47916224e80f511acca4c06f)
=> [23.0 backport] bump compose version to v2.17.1

common.mk
https://github.com/docker/compose/releases/tag/v2.17.2
=> [master] bump compose version to v2.17.2

deb/common/rules, rpm/SPECS/docker-ce.spec
See https://github.com/moby/moby/commit/6caaa8cadc9e4f1e122b7b2bb4451500bbec6086 / https://github.com/moby/moby/pull/45198
=> Move "docker-init" into appropriate "libexec" directory

Makefile, common.mk, deb/Makefile, deb/build-deb, rpm/centos-7/Dockerfile, rpm/centos-8/Dockerfile, rpm/centos-9/Dockerfile, rpm/fedora-36/Dockerfile, rpm/fedora-37/Dockerfile, rpm/rhel-7/Dockerfile
commit 7e0ffd93153a254b08c0d63b4941745adcbf5c93 (https://github.com/docker/docker-ce-packaging/pull/827) removed the code to build the plugins (which is now handled as part of the 23.0.x and 24.0.x releases), but I didn't remove other code related to plugins, such as checking out source.
Obviously that's a bit of a waste of time if we won't be building these, so let's remove that as well ':D
=> [20.10] remove leftovers for building plugins

deb/common/control, rpm/SPECS/docker-ce-cli.spec
The scan-cli-plugin has been deprecated, and will no longer receive updates, so we don't want it to be automatically installed as a dependency; https://github.com/docker/scan-cli-plugin/blob/b69ac460a6c23243b858326f0e26f6bd202ca781/internal/deprecation.go#L13-L15
=> [20.10] remove scan-cli-plugin as recommends/required dependency

deb/common/control, rpm/SPECS/docker-ce-cli.spec
The scan-cli-plugin has been deprecated, and will no longer receive updates, so we don't want it to be automatically installed as a dependency; https://github.com/docker/scan-cli-plugin/blob/b69ac460a6c23243b858326f0e26f6bd202ca781/internal/deprecation.go#L13-L15
=> [23.0] remove scan-cli-plugin as recommends/required dependency

Jenkinsfile, deb/Makefile, deb/ubuntu-lunar/Dockerfile
- relates to https://github.com/docker/containerd-packaging/pull/314
Ubuntu 23.04 is planned to be released on April 20, but final betas are available now.
=> [master] Add Ubuntu 23.04 "Lunar Lobster"

Jenkinsfile, deb/Makefile, deb/ubuntu-lunar/Dockerfile
- backport of https://github.com/docker/docker-ce-packaging/pull/875
Ubuntu 23.04 is planned to be released on April 20, but final betas are available now.
(cherry picked from commit e2990968104d18f7144de9526fe5a0a2e3b56a4b)
=> [23.0] Add Ubuntu 23.04 "Lunar Lobster"

Jenkinsfile, rpm/Makefile, rpm/fedora-38/Dockerfile
- supersedes / closes https://github.com/docker/docker-ce-packaging/pull/885
currently this is still the equivalent of "rawhide", but start testing builds in CI.
=> [master] Start testing builds for Fedora 38 (not yet released)

Jenkinsfile, rpm/Makefile, rpm/fedora-38/Dockerfile
- backport of https://github.com/docker/docker-ce-packaging/pull/885
- closes https://github.com/docker/docker-ce-packaging/issues/881
- supersedes / closes https://github.com/docker/docker-ce-packaging/pull/886
(cherry picked from commit cf2ab34b4fb05f024e7677528786b3273e5d7bff)
=> [23.0 backport] Add Fedora 38 (current stable).

common.mk
- Supersedes #892 
- closes #892
=> [master] bump compose to v2.18.1

common.mk
- See #896 
- Supersedes #893 
- closes #893
=> [23.0 backport] bump compose to v2.18.1

deb/Makefile, rpm/Makefile
While we only use the golang binaries from these images (which should be the same for both), Debian buster reached EOL. Update the Golang image to the current stable version of Debian (Debian 12 "bookworm")
=> [master] deb, rpm: update golang image to use bookworm instead of buster

deb/debian-bookworm/Dockerfile, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bookworm/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, deb/ubuntu-kinetic/Dockerfile, deb/ubuntu-lunar/Dockerfile, rpm/centos-7/Dockerfile, rpm/centos-8/Dockerfile, rpm/centos-9/Dockerfile, rpm/fedora-37/Dockerfile, rpm/fedora-38/Dockerfile, rpm/rhel-7/Dockerfile
I didn't update the Ubuntu bionic Dockerfile, as that will be removed in https://github.com/docker/docker-ce-packaging/pull/911
Use COPY --link for steps that don't depend on the base image or prior steps, to allow for better sharing of build-cache.
=> [master] Update dockerfiles to use COPY --link

common.mk
https://github.com/docker/compose/releases/tag/v2.19.1
=> bump compose version to v2.19.1

deb/Makefile, rpm/Makefile
- backport of https://github.com/docker/docker-ce-packaging/pull/909
While we only use the golang binaries from these images (which should be the same for both), Debian buster reached EOL. Update the Golang image to the current stable version of Debian (Debian 12 "bookworm")
(cherry picked from commit 46f56f2720c6f36650294e728079e21609353702)
=> [23.0 backport] deb, rpm: update golang image to use bookworm instead of buster

common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.11.2
=> update buildx to v0.11.2

common.mk
=> bump compose to v2.20.2

deb/debian-bookworm/Dockerfile, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bookworm/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, deb/ubuntu-kinetic/Dockerfile, deb/ubuntu-lunar/Dockerfile, rpm/centos-7/Dockerfile, rpm/centos-8/Dockerfile, rpm/centos-9/Dockerfile, rpm/fedora-37/Dockerfile, rpm/fedora-38/Dockerfile, rpm/rhel-7/Dockerfile
- backport https://github.com/docker/docker-ce-packaging/pull/913
Use COPY --link for steps that don't depend on the base image or prior steps, to allow for better sharing of build-cache.
(cherry picked from commit 297fa1524db43c36685218e271ea86d9955982fe)
=> [23.0 backport] Update dockerfiles to use COPY --link

rpm/SPECS/docker-ce.spec
- relates to https://github.com/docker/docker-ce-packaging/issues/915#issuecomment-1728187098
The deb pacakges have this dependency as "recommends", but older versions of yum (RHEL7 / CentOS 7) do not support this. and only support "requires".
This patch uses a similar approach as bb4bd31ab60fe5bc496021d2606882db913c5bad did for the CLI, and changes the dependency to be "recommends" where possible, falling back to "requires" for older rpm versions.
=> rpm: recommend, not require  "docker-ce-rootless-extras" where possible

deb/debian-bookworm/Dockerfile, deb/debian-bullseye/Dockerfile, deb/debian-buster/Dockerfile, deb/raspbian-bookworm/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/raspbian-buster/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, deb/ubuntu-lunar/Dockerfile, rpm/fedora-37/Dockerfile, rpm/fedora-38/Dockerfile, rpm/fedora-39/Dockerfile
- relates to https://github.com/docker-library/golang/issues/472
Make sure we don't get unexpected updates of the go toolchain when building.
=> deb, rpm: use GOTOOLCHAIN=local

rpm/SPECS/docker-ce.spec
This PR adds `docker.socket` to the `%preun` section of the `docker-ce` spec, in order to disable the socket upon uninstall.
Fixes #851
=> Add docker.socket to the %preun section

common.mk
https://github.com/docker/compose/releases/tag/v2.22.0
=> [master] bump compose version to v2.22.0

Jenkinsfile, deb/Makefile, deb/ubuntu-mantic/Dockerfile
- backport of https://github.com/docker/docker-ce-packaging/pull/954 / https://github.com/docker/docker-ce-packaging/pull/949
(cherry picked from commit f21c3860862f02b9c009fcefd03a344489bb965c)
=> [24.0 backport] Add Ubuntu 23.10 "Mantic Minotaur"

deb/common/control, rpm/SPECS/docker-ce.spec
relates to https://github.com/moby/moby/pull/46778
=> deb, rpm: set minimum containerd version to 1.6.24

rpm/Makefile, rpm/SPECS/docker-ce.spec, rpm/patches/01-rlimit_nofile-rhel7.patch
RLIMIT_NOFILE defaults to an unusable value on EL 7 systems, but more modern systems have sane defaults. As such, patch the systemd unit only on EL 7 systems to ensure correct behaviour.
=> rpm: patch RLIMIT_NOFILE for EL 7 systems

Jenkinsfile
The End of Standard Support is set to June, not April, in 2027. 
https://wiki.ubuntu.com/Releases
=> Jenkinsfile: fix Ubuntu 22.04 End of Standard Support

deb/common/rules
This is a quick band-aid; we need to overhaul how we handle architectures in these scripts (and use the Debian base images for Raspbian); but for now this should ensure we force ARMv6 for Raspbian targets.
=> debian: add explicit GOARM for raspbian

deb/common/rules
Debian armhf is armv7 and hard-float, and Raspbian is a rebuild of Debian with armv6 and hard-float. This is done to make use of the BCM2835 FPU, as while the Debian armel (armv5 and soft-float) port works, it does not make full use of the CPU's hardware.
By making this change, our 'armhf' binaries will work on both armv6 and armv7 systems.
=> debian: build armv6 binaries for armhf

deb/Makefile
- addresses https://github.com/docker/docker-ce-packaging/pull/1006#issuecomment-2006878743
tar is failing to apply permissions, but only on `armhf` if seccomp is enabled
docker run --rm -e PLATFORM -e EPOCH='5' -e DEB_VERSION=0.0.0~20240319100031.2356372 -e VERSION=0.0.0-20240319100031-2356372 -e CLI_GITCOMMIT=2356372 -e ENGINE_GITCOMMIT=23e1af4 -e BUILDX_VERSION=v0.13.1 -e BUILDX_DEB_VERSION=0.13.1 -e BUILDX_GITCOMMIT=7884339 -e COMPOSE_VERSION=v2.25.0 -e COMPOSE_DEB_VERSION=2.25.0 -v /home/ubuntu/workspace/docker-ce-packaging_PR-1006/deb/debbuild/ubuntu-noble:/build  debbuild-ubuntu-noble/aarch64
+ set -e
+ mkdir -p /root/build-deb/engine
+ tar -C /root/build-deb -xzf /sources/engine.tgz
tar: engine/daemon/config: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: …
=> [master] disable seccomp to prevent tar EPERM (Ubuntu 24.04 armhf on 20.04 host)

.github/workflows/ci.yml, Jenkinsfile, deb/Makefile, deb/ubuntu-noble/Dockerfile
- carries / closes https://github.com/docker/docker-ce-packaging/pull/994
=> [master] Add Ubuntu 24.04 "Noble Numbat" (carry 994)

common.mk
Update Compose to [v2.26.1](https://github.com/docker/compose/releases/tag/v2.26.1)
=> update Compose to v2.26.1

rpm/Makefile
- addresses / fixes https://github.com/docker/docker-ce-packaging/issues/1012
- relates to https://github.com/docker/docker-ce-packaging/pull/1007
commit 07b5d9031f18ad8317f23738c7ff4ce9f77e3ee3 disabled seccomp for the deb-builds because `chmod` failed tar was failing with an EPERM (Ubuntu 24.04 armhf on 20.04 host).
It looks like the same problem happens when running Fedora 40 on a Debian bookworm host on ppc64le.
That issue was confirmed to be related to `fchmodat2(2)`, which is a new syscall that's not supported on the host, and therefore gets the seccomp's default EPERM;
fchmodat2(AT_FDCWD, "docker", 0775, AT_SYMLINK_NOFOLLOW) = -1 EPERM (Operation not permitted)
tar: docker: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: Exiting with failure status due to previous …
=> [master] rpm: disable seccomp to prevent tar EPERM (Fedora 40 ppc64le on Debian)

static/Makefile
- relates to https://github.com/docker/docker-ce-packaging/pull/554
- relates to https://github.com/docker/docker-ce-packaging/pull/578
- slightly related to https://github.com/docker/docker-ce-packaging/pull/1037
- slightly related to https://github.com/moby/moby/pull/48132
The `docker-proxy.exe` binary was added to the static Windows packages through commit 09541b553c2f7646626efcc2797bd92ee48a66d0 (which introduced a bug, later fixed through fc5379fee869e8fa0e9a2569a66083e61e83de18).
It looks like that commit added the `docker-proxy.exe` binary with the assumption that it's used on Windows (given that its also built in upstream), but recent discussions revealed that's not the case.
This patch removes binary from the static packages for Windows, because it's not used.
A quick look at …
=> [master] static: remove unused docker-proxy.exe binary from Windows packages

verify
- relates to https://github.com/docker/docker-ce-packaging/pull/819
- relates to https://github.com/containerd/containerd/pull/6495
The containerd-shim binary that's shipped with containerd 1.6 did not provide a `-v` flag to show the version, so f1f6f220e6f6070f8e481d7b60101816526f8bf8 used `--help` as alternative.
Now that we package containerd 1.7, we can use the `-v` flag instead;
containerd-shim -v
containerd-shim
Version:  1.7.19
Revision: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
Go version: go1.21.12
=> [master] verify: remove workaround for containerd-shim 1.6's missing "-v" flag

deb/common/rules, rpm/SPECS/docker-ce-rootless-extras.spec, static/Makefile
Depends on:
- https://github.com/moby/moby/pull/48132
With that PR, `rootlesskit-docker-proxy` is no longer used or built.
Removed commands for installing `rootlesskit-docker-proxy`.
Interesting question!
The executable `rootlesskit-docker-proxy` is no longer required and has been removed.
=> Remove 'rootlesskit-docker-proxy'

common.mk
- carries https://github.com/docker/docker-ce-packaging/pull/1049
- closes https://github.com/docker/docker-ce-packaging/pull/1049
=> [master] Bump compose version to v2.29.2

common.mk
(cherry picked from commit e712fc4e40c52400b09d8bbcb0b5bc057e9b54f7)
cherry-pick from https://github.com/docker/docker-ce-packaging/pull/1050 to branch 27.x
=> Bump compose version to v2.29.2

common.mk
Make sure we run CI with the correct upstream branch.
- relates to https://github.com/docker/docker-ce-packaging/pull/1052#issuecomment-2293700151
=> [27.x] use upstream 27.x branch as default

Jenkinsfile, deb/Makefile, rpm/Makefile, rpm/rhel-8/Dockerfile, rpm/rhel-9/Dockerfile
- backport: https://github.com/docker/docker-ce-packaging/pull/991
=> [27.x] RHEL PoC

deb/debian-bookworm/Dockerfile, deb/debian-bullseye/Dockerfile, deb/raspbian-bookworm/Dockerfile, deb/raspbian-bullseye/Dockerfile, deb/ubuntu-focal/Dockerfile, deb/ubuntu-jammy/Dockerfile, deb/ubuntu-noble/Dockerfile
Replace legacy `ENV key value` syntax with `ENV key=value`.
This fixes the build linter warning LegacyKeyValueFormat.
Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>
=> Dockerfile: Fix legacy `ENV key value` format

install-containerd-helpers
- relates to https://github.com/docker/docker-ce-packaging/pull/1058
- relates to https://github.com/rpm-software-management/dnf5/issues/1603
- use command -v for detecting dnf instead of the --version
- quote repo-IDs to prevent globbing by the shell
Fedora 41 and up use the new dnf5 as default, which is a rewrite of
the dnf commands with different options;
+ dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.
make: *** [Makefile:95: verify] Error 2
script returned exit code 2
The addrepo command has a bug that causes it to fail if the `.repo` file
contains empty lines, causing it to fail;
dnf config-manager addrepo …
=> [master] install_rpm_containerd: add support for dnf5

install-containerd-helpers
- backport https://github.com/docker/docker-ce-packaging/pull/1059
- relates to https://github.com/docker/docker-ce-packaging/pull/1058
- relates to https://github.com/rpm-software-management/dnf5/issues/1603
- use command -v for detecting dnf instead of the --version
- quote repo-IDs to prevent globbing by the shell
Fedora 41 and up use the new dnf5 as default, which is a rewrite of
the dnf commands with different options;
+ dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.
make: *** [Makefile:95: verify] Error 2
script returned exit code 2
The addrepo command has a bug that causes it to fail if the `.repo` file
contains empty lines, …
=> [27.x backport] install_rpm_containerd: add support for dnf5

rpm/centos-9/Dockerfile, rpm/rhel-8/Dockerfile, rpm/rhel-9/Dockerfile
- relates to https://github.com/docker/docker-ce-packaging/pull/947
- relates to https://github.com/docker-library/golang/issues/472
Commit a4090a0e198517b9e7603db375a283c3df3ec4f7 added GOTOOLCHAIN=local, but for some reason missed the centos Dockerfiles.
The env-var is set to make sure we don't get unexpected updates of the go toolchain when building. We need to set this env-var, because we're not using the official golang image as base-image, but instead copy the binaries into a distro-image.
This patch adds the missing GOTOOLCHAIN env-vars.
=> [master] rpm: fix missing GOTOOLCHAIN=local in centos, rhel Dockerfiles

rpm/centos-9/Dockerfile, rpm/rhel-8/Dockerfile, rpm/rhel-9/Dockerfile
- backport https://github.com/docker/docker-ce-packaging/pull/1062
Commit a4090a0e198517b9e7603db375a283c3df3ec4f7 added GOTOOLCHAIN=local, but for some reason missed the centos Dockerfiles.
The env-var is set to make sure we don't get unexpected updates of the go toolchain when building. We need to set this env-var, because we're not using the official golang image as base-image, but instead copy the binaries into a distro-image.
This patch adds the missing GOTOOLCHAIN env-vars.
(cherry picked from commit dc175c09fd68aee12ca0752f83aff16a7a51fef2)
=> [27.x backport] rpm: fix missing GOTOOLCHAIN=local in centos, rhel Dockerfiles

Jenkinsfile, rpm/Makefile, rpm/fedora-41/Dockerfile
- carries https://github.com/docker/docker-ce-packaging/pull/1055
- closes https://github.com/docker/docker-ce-packaging/pull/1055
It's nearing that time again.  A new Fedora release.
This is part 2 of 2 for packaging Docker CE for Fedora 41.  [Part 1](https://github.com/docker/containerd-packaging/pull/388) is awaiting review in the [docker/containerd-packaging](https://github.com/docker/containerd-packaging) repository.
Fedora have not (yet) set a concrete date for the EOL of Fedora 41, however it will be in or around November 2025.
The same as the previous two releases - added a line for Fedora 41 in the Jenkinsfile, updated the list of OSes in the Makefile and created a new Dockerfile using the new Fedora 41 image.
I have ran …
=> [master] feat: build Fedora 41 RPM packages (carry #1055)

Jenkinsfile, rpm/Makefile, rpm/fedora-41/Dockerfile
- backport https://github.com/docker/docker-ce-packaging/pull/1058
=> [27.x backport] feat: build Fedora 41 RPM packages

.github/workflows/ci.yml, Jenkinsfile, deb/Makefile, deb/ubuntu-oracular/Dockerfile
- relates to https://github.com/docker/containerd-packaging/pull/392
Ubuntu 24.10 is planned to be released on October 10. https://discourse.ubuntu.com/t/oracular-oriole-release-schedule/36460
Add Ubuntu 24.10 "Oracular Oriole"
=> [master] Add Ubuntu 24.10 "Oracular Oriole"

.github/workflows/ci.yml, Jenkinsfile, deb/Makefile, deb/ubuntu-oracular/Dockerfile
- backport https://github.com/docker/docker-ce-packaging/pull/1070
Ubuntu 24.10 is planned to be released on October 10. https://discourse.ubuntu.com/t/oracular-oriole-release-schedule/36460
(cherry picked from commit a7c8523ab23777253966fe41f7cf2b97774b2493)
Add Ubuntu 24.10 "Oracular Oriole"
=> [27.x backport] Add Ubuntu 24.10 "Oracular Oriole"

common.mk
- backport https://github.com/docker/docker-ce-packaging/pull/1081
release-notes: https://github.com/docker/compose/releases/tag/v2.29.5
(cherry picked from commit 3497b371654642556e78565b40befff1ee39eaef)
```markdown
- Update compose [to v2.29.5](https://github.com/docker/compose/releases/tag/v2.29.5)
```
=> [27.x backport] bump compose to v2.29.5

common.mk
Backports: https://github.com/docker/docker-ce-packaging/pull/1085
=> [27.x backport] Bump compose to v2.29.7

common.mk
(cherry picked from commit 0f7dd44db47fbebaf0d2e0a94f30483b9eacd12a)
Backport bump of Compose to version `v2.30.1`
=> [27.x backport] bump Compose to version v2.30.1

common.mk
- backport: https://github.com/docker/docker-ce-packaging/pull/1101
(cherry picked from commit 50f8a21069a346996206645e7e7f1e004dd9b43e)
```
Update Compose to [v2.30.3](https://github.com/docker/compose/releases/tag/v2.30.3)
```
=> [27.x backport] bump Compose to version v2.30.3

rpm/centos-9/Dockerfile, rpm/fedora-39/Dockerfile, rpm/fedora-40/Dockerfile, rpm/fedora-41/Dockerfile, rpm/rhel-8/Dockerfile, rpm/rhel-9/Dockerfile
- backport https://github.com/docker/docker-ce-packaging/pull/1105
Commit 784a53cec5061e6a718acc3a7104c61215c15078 added `rpmlint` to the Dockerfiles and added a step in the Dockerfile to validate the SPEC files. The validation step was removed in c245ce12c1e0a092ef21094b287b8cb94a51ee1e, but didn't remove the step to install the package.
The `rpmlint` package is also being removed from CentOS Stream 10 ("CS10");
- https://issues.redhat.com/browse/CS-2451
- https://issues.redhat.com/browse/CS-2453
Remove the package as it's not used currently.
(cherry picked from commit 38309c1b6020246bdad19b14116c08b40c72c7c8)
=> [27.x backport] rpm: remove rpmlint from Dockerfiles as it's not used

Jenkinsfile, rpm/Makefile, rpm/centos-10/Dockerfile
- carries https://github.com/docker/docker-ce-packaging/pull/1103
- closes https://github.com/docker/docker-ce-packaging/pull/1103
Use image "stream10-development" for now, after the release we should remove the "-development" suffix.
=> [master] Add CentOS Stream 10.

Jenkinsfile, rpm/centos-10/Dockerfile
@thaJeztah Yesterday RHEL 10 Beta was officially released, and it seems at the same time Red Hat has renamed the CentOS Stream 10 image name to it's final name. See https://quay.io/repository/centos/centos?tab=tags&tag=latest
=> [27.x backport] Use the final CentOS Stream 10 OCI image.

Jenkinsfile, rpm/centos-10/Dockerfile
@thaJeztah Yesterday RHEL 10 Beta was officially released, and it seems at the same time Red Hat has renamed the CentOS Stream 10 image name to it's final name. See https://quay.io/repository/centos/centos?tab=tags&tag=latest
=> [master] Use the final CentOS Stream 10 OCI image.

common.mk
(cherry picked from commit 5e03b03a3493b97273e477f596e6d48fd2a27596)
Backport bump of Compose version to `v2.31.0`
=> [Backport] bump Compose to version v2.31.0

verify
=> verify: Remove `software-properties-common` package install

common.mk
Bump Compose v2.32.0
Compose v2.32.0
=> Bump Compose v2.32.0

verify
- backport: https://github.com/docker/docker-ce-packaging/pull/1127
=> [27.x backport] verify: Remove `software-properties-common` package install

common.mk
backport https://github.com/docker/docker-ce-packaging/pull/1125
=> [27.x backport] Bump Compose v2.32.0

common.mk
=> update buildx to v0.19.3

rpm/SPECS/docker-ce.spec
=> rpm: drop unnecessary build-deps

common.mk
Bump Docker Compose to version `v2.32.3`
=> [master] bump compose verstion to v2.32.3

common.mk
(cherry picked from commit 93a866aedbd4a8d0e537fa5e6c45eba00835a049)
Backport bump of Compose to version `v2.32.3`
=> [27.x] bump compose verstion to v2.32.3

common.mk
Bump Compose to version `v2.32.4`
=> [master] bump compose verstion to v2.32.4

common.mk
(cherry picked from commit 74cd8cf0c174f9a660c56cdd57f0222023f79fdf)
Backport bump of Compose `v2.32.4`
=> [27.x] bump compose verstion to v2.32.4

common.mk
* backport of https://github.com/docker/docker-ce-packaging/pull/1148
=> [27.x] update buildx to v0.20.0

common.mk
- backport: https://github.com/docker/docker-ce-packaging/pull/1151
=> [27.x] update buildx to v0.20.1

rpm/SPECS/docker-ce.spec
- reverts https://github.com/docker/docker-ce-packaging/pull/17
Remove the obsoletes for `docker-ce-selinux`, `docker-engine-selinux`, and `docker-engine`.
These were obsoleted in 2017 through 94943b47520aa81bbe30fbc4eb927c79047ef6d2
> Mark docker-*-selinux pkgs as obsolete
>
> These are replaced by `container-selinux` on fedora-25 and centos-7.
> Marking these packages as obsolete makes the installation process a bit
> smoother, otherwise the user will have to manually uninstall the older
> packages to install the new one.
>
> Also makes fedora24 use container-selinux which is now supports labeling
> the `dockerd` binary correctly.
Both CentOS 6/7 and Fedora 25 are EOL now, and these packages have not been published for a long time. Time to remove them, also to reduce some noise during …
=> rpm: remove Obsoletes for obsolete (selinux) packages

deb/common/docker-ce-cli.bash-completion, deb/common/rules, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
The "make dynbinary" target calls ./scripts/build/binary with the
right options set, and does not use docker to build (so can be
run as part of our deb/rpm build scripts.
The "-D" option creates parent directories if missing; we
can use it in most places, except for one where we're using
wildcards, as installing multiple files requires the target
directory to exist.
This unlikely makes a big difference, as some files may have timestamps
based on checkout date or being generated, but it doesn't hurt doing
either.
This unlikely makes a big difference, as some files may have timestamps
based on checkout date or being generated, but it doesn't hurt doing
either.
The dh_bash-completion debhelper provides an easy way to install the
shell-completion scripts for Bash. Unfortunately there is no …
=> [master] deb, rpm:  slight refactor / cleanup

deb/common/rules, rpm/SPECS/docker-buildx-plugin.spec, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-compose-plugin.spec
For make commands, we can just pass the directory through "-C", and for "install" we can pass the full path of the source.
There's some remaining uses for targets that build through a script or using "go build", which may still require changing.
=> [master]  deb, rpm: reduce uses of "cd", "popd", "pushd"

deb/common/rules, rpm/SPECS/docker-ce-cli.spec
- supersedes   / closes https://github.com/docker/docker-ce-packaging/pull/1156
- depends on https://github.com/docker/cli/pull/5770
Replace the CLI completions (located in `cli/contrib/completions` with cobra generated ones.
=> [master] deb,rpm: use cobra generated completions

deb/common/control, rpm/SPECS/docker-ce.spec
- updates, fixes https://github.com/docker/docker-ce-packaging/pull/1118#issuecomment-2611224201
This was added in deed8d9df8cd90139229748021efcc006900aba5, as the docker engine depended on modprobe to enable br_netfilter. Docker Engine no longer requires this since [moby/moby@4b8c720], and [moby/moby@8a8ab0d] (docker\ engine v27.4.1), so we can reduce this to a "suggests"
[moby/moby@4b8c720]: https://github.com/moby/moby/commit/4b8c72060d1089626e4ac9f5e0624e0cb567d4bc
[moby/moby@8a8ab0d]: https://github.com/moby/moby/commit/8a8ab0d5670dd4f499422120ea4585d07ab464c0
=> [master] deb, rpm: make kmod "suggests" instead of "recommends"

deb/common/control, deb/common/docker-ce.manpages, deb/common/rules, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-ce.spec
- relates to https://github.com/moby/moby/pull/48298
- relates to https://github.com/docker/cli/pull/5773
- relates to  https://github.com/docker/runtime-team/issues/161
The CLI currently builds man-pages for sections 1, 5, and 8, but this
list may change; for example, the dockerd man-page is currently built
from the CLI repository but intended to be removed.
This patch changes the code to check all (1..9) secions, and install the
man-pages found in them.
This patch also updates the %doc and %files section; from the Fedora packaging
guide (see [1]);
> The %files section holds a list of all the files that RPM should install
> from the package. **This list should be exhaustive**, so that the RPM system
> knows exactly what your package installs. There are some options, though,
> to name all …
=> [master] deb,rpm: include dockerd man-page in docker-ce package

common.mk, deb/common/control, rpm/SPECS/docker-compose-plugin.spec
Bump compose v2.33.0
Declare buildx as a recommended dependency as v2.33.0 introduces support for delegating build command to bake.
Compose v2.33.0
=> Bump compose v2.33.0

common.mk
Bump Compose version to `v2.34.0`
```markdown changelog
Update Compose to [v2.34.0](https://github.com/docker/compose/releases/tag/v2.34.0).
```
=> bump compose verstion to v2.34.0

.github/workflows/ci.yml, Jenkinsfile, rpm/Makefile, rpm/fedora-42/Dockerfile
Needs https://github.com/docker/containerd-packaging/pull/408
Enables docker-ce builds for Fedora 42.  This will be GA in a couple months, and like usual, has a lifespan of one year.
The workarounds required for Go on ARM are still required on this version, so have been left in.  The comments are still relevant.
I ran a `make fedora-42`, which currently fails due to a lack of containerd (I expect). 
=> feat: enable Fedora 42 packaging

.github/workflows/ci.yml
Add distros from Jenkinsfile to GHA
=> ci: Test more distros in GHA workflow

.github/workflows/ci.yml
- similar to https://github.com/docker/cli/pull/5310
- similar to https://github.com/docker/cli/pull/3744
We had a few "runaway jobs" in other repos, where the job got stuck, and kept
running for 6 hours (in one case even 24 hours, probably due some github
outage). Some of those jobs could not be terminated.
While running these actions on public repositories doesn't cost us, it's
still not desirable to have jobs running for that long (as they can still
hold up the queue).
This patch adds a blanket "1 hour" time-limit. We should look at tweaking
the limit to actually expected duration, but having a default at least is
a start.
=> gha:  various tweaks

common.mk
Bump Compose to version `v2.35.0`
```markdown changelog
Update Compose to [v2.35.0](https://github.com/docker/compose/releases/tag/v2.35.0)
```
=> bump compose version to v2.35.0

.github/workflows/ci.yml, Jenkinsfile, deb/Makefile, deb/debian-trixie/Dockerfile
Not yet released, but toolchain freeze has been announced https://lists.debian.org/debian-devel-announce/2025/03/msg00011.html
```markdown changelog
Add Debian "Trixie"
```
=> deb: Add Debian "Trixie"

Makefile, common.mk, deb/Makefile, deb/build-deb, deb/common/control, deb/common/rules, rpm/Makefile, rpm/SPECS/docker-ce-cli.spec, rpm/SPECS/docker-model-plugin.spec, verify
I added a `docker-model-plugin` package in support of [Docker Model Runner](https://docs.docker.com/model-runner/)'s upcoming support for Docker CE.
I tried to emulate the structure of the `docker-buildx-plugin` and `docker-compose-plugin` builds / specs (primarily compose).  One small ugly bit is that the source repo is called `model-cli`, and Go requires it retain that name, so I've had to use a `src/github.com/docker/model-cli` path for the code, but for all the variables and specs I've omitted the `-cli` suffix and just used `model`/`MODEL` nomenclature.
The package should build successfully on all supported target distros.
```
Add `docker-model-plugin` package to enable Docker Model Runner …
```
=> all: add rules for docker-model-plugin packages

rpm/SPECS/docker-ce.spec
- fixes https://github.com/docker/docker-ce-packaging/issues/1176
- relates to https://github.com/docker/docker-ce-packaging/pull/1159
commit 3ded61e6d77efa4759c2f9cf820299f4b7a1a16d moved the man-pages for dockerd to the docker-ce package, but used the wrong path for installing them, which resulted in the man-pages being installed in a "man" subdirectory with.
Before this patch:
make fedora-42
rpm -ql ./rpm/rpmbuild/fedora-42/RPMS/aarch64/docker-ce-*.rpm | grep dockerd.8
/usr/share/man/man/man8/dockerd.8.gz
After this patch:
make fedora-42
rpm -ql ./rpm/rpmbuild/fedora-42/RPMS/aarch64/docker-ce-*.rpm | grep dockerd.8
/usr/share/man/man8/dockerd.8.gz
```
Fix install location for RPM-based …
```
=> rpm: fix install location for docker-ce man-pages

deb/common/control
- relates to https://github.com/docker/docker-ce-packaging/issues/1197
Before this patch, lintian would complain about missing pre-depends:
lintian ./*.deb
...
W: docker-ce: skip-systemd-native-flag-missing-pre-depends (does not satisfy init-system-helpers:any) [postinst:51]
W: docker-ce: skip-systemd-native-flag-missing-pre-depends (does not satisfy init-system-helpers:any) [prerm:10]
=> deb: add missing pre-depends for init-system-helpers

deb/common/control
- relates to https://github.com/docker/docker-ce-packaging/issues/1197
Before this patch, some linting warnings were shown related to the descriptions
lintian ./*.deb
...
W: docker-ce: extended-description-line-too-long line 5
W: docker-ce-cli: extended-description-line-too-long line 5
W: docker-ce-rootless-extras: description-starts-with-leading-spaces line 1
E: docker-buildx-plugin: extended-description-is-empty
W: docker-compose-plugin: extended-description-contains-empty-paragraph
W: docker-model-plugin: extended-description-contains-empty-paragraph
=> deb: fix lintian errors/warnings for extended descriptions

Jenkinsfile
- related https://github.com/docker/containerd-packaging/pull/369
=> Jenkinsfile: update to use Ubuntu 22.04 agents

common.mk
Bump Compose to the `v2.36.2` version
```markdown changelog
Update Compose to [v2.36.2](https://github.com/docker/compose/releases/tag/v2.36.2)
```
=> bump compose version to v2.36.2

deb/common/docker-ce.postinst, deb/common/rules, rpm/SPECS/docker-ce.spec
Reverted the systemd-sysusers change.
```markdown changelog
```
=> fix(all): revert sysusers

deb/common/rules, rpm/SPECS/docker-buildx-plugin.spec
This disables DWARF generation, which dramatically decreases the size of the binary.
Notably, this does *not* include `-s` which disables the symbol table, as doing so would *also* make it so that `govulncheck` cannot be run on the resulting binary with meaningful results.
Before is ~90M and after is ~72M.
If we add `-s` as well, that ~72M drops to ~63M, but we also lose `govulncheck` so again, IMO, that's not worth doing.
See also:
- https://github.com/docker/compose/pull/10325
- https://github.com/docker/buildx/blob/c45185fde0c9e596afb9044be3328b6d39b3d7ca/Dockerfile#L86
=> Add `-w` to buildx ldflags

common.mk
I bumped the Model CLI to v0.1.34.
Includes multiline support in the chat, improved pull messages, show untagged and removed information on `rm`, allow implicit registry on `tag` and `--backend` tag for `run` and `list`. https://github.com/docker/model-cli/releases/tag/v0.1.34.
```markdown changelog
Update Docker Model CLI plugin to [v0.1.34](https://github.com/docker/model-cli/releases/tag/v0.1.34)
```
=> Bump Docker Model CLI version to v0.1.34

common.mk
https://github.com/docker/buildx/releases/tag/v0.26.0
```markdown changelog
Update Buildx to [v0.26.0](https://github.com/docker/buildx/releases/tag/v0.26.0)
```
=> update buildx to v0.26.0

common.mk
I bumped the Model CLI to v0.1.36.
Include support for `docker model package` without `--push` and a fix for context detection from within WSL2 (https://github.com/docker/model-runner/issues/118). From https://github.com/docker/model-cli/releases/tag/v0.1.36.
```markdown changelog
Update Docker Model CLI plugin to [v0.1.36](https://github.com/docker/model-cli/releases/tag/v0.1.36)
```
=> Bump Docker Model CLI version to v0.1.36

common.mk
https://github.com/docker/buildx/releases/tag/v0.28.0
```markdown changelog
Update Buildx to [v0.28.0](https://github.com/docker/buildx/releases/tag/v0.28.0)
```
=> update buildx to v0.28.0

distros.json, rpm/Makefile, rpm/fedora-43/Dockerfile
Blindly copy the fedora 42 Dockerfile for fedora 43, just change the version number.
```markdown changelog
Add Fedora 43 packages
```
=> Add Fedora 43.

rpm/SPECS/docker-compose-plugin.spec
It's no longer a part of the compose source code
https://github.com/docker/compose/commit/a429c09dfa84d22262a9a69406eff5841fd9bdb3
=> rpm/compose: Remove MAINTAINERS docs file

common.mk
https://github.com/docker/buildx/releases/tag/v0.29.1
```markdown changelog
Update Buildx to [v0.29.1](https://github.com/docker/buildx/releases/tag/v0.29.1)
```
=> update buildx to v0.29.1

common.mk
bump compose to v2.40.0
```markdown changelog
Docker Compose v2.40.0
```
=> bump compose to v2.40.0

rpm/SPECS/docker-ce.spec
Rather than requiring iptables-nft for RHEL10/Fedora43 and iptables for other versions and CentOS, use "(iptables-nft or iptables)".
Newer OSs will have iptables-nft, if anything - and making people install iptables-legacy isn't great if it's not needed.
(When neither dependency is available - dnf seems to install both if they're available, but doesn't mind if it can only find one of them. And, if one's already installed, it doesn't try to install the other.)
```markdown changelog
```
=> RPM: require "iptables-nft or iptables"

verify
- backport: https://github.com/docker/docker-ce-packaging/pull/1260
containerd v2 no longer ships `containerd-shim` and `containerd-shim-runc-v1` binaries.
```markdown changelog
```
=> [28.x backport] verify: fix containerd v2 verification

common.mk
This reverts commit cf4e3a6b20bc79e13d6dfeae431ea82dac64b2bb.
Accidentally opened against `master` instead of `28.x` 🤦🏻
=> Revert "[28.x] use 28.x branch by default"
