- rpm/centos-7/Dockerfile.x86_64
- rpm/fedora-24/Dockerfile.x86_64
- rpm/fedora-25/Dockerfile.x86_64
Signed-off-by: Roberto Gandolfo Hashioka <roberto_hashioka@hotmail.com>
> Add DISTRO/SUITE env. variables to the RPM dockerfiles

- deb/Makefile
- deb/build-deb
- deb/common/rules
- deb/debian-jessie/Dockerfile.armhf
- deb/debian-stretch/Dockerfile.armhf
- deb/debian-wheezy/Dockerfile.armhf
- deb/ubuntu-trusty/Dockerfile.armhf
- deb/ubuntu-xenial/Dockerfile.armhf
- deb/ubuntu-yakkety/Dockerfile.armhf
- deb/ubuntu-zesty/Dockerfile.armhf
- detect_alpine_image
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>
> Add armhf dockerfiles for deb building

- deb/Makefile
- deb/common/rules
- deb/debian-jessie/Dockerfile.armv7l
- deb/debian-jessie/Dockerfile.x86_64
- deb/debian-stretch/Dockerfile.armv7l
- deb/debian-stretch/Dockerfile.x86_64
- deb/debian-wheezy/Dockerfile.armv7l
- deb/debian-wheezy/Dockerfile.x86_64
- deb/ubuntu-trusty/Dockerfile.armv7l
- deb/ubuntu-trusty/Dockerfile.x86_64
- deb/ubuntu-xenial/Dockerfile.armv7l
- deb/ubuntu-xenial/Dockerfile.x86_64
- deb/ubuntu-yakkety/Dockerfile.armv7l
- deb/ubuntu-yakkety/Dockerfile.x86_64
- deb/ubuntu-zesty/Dockerfile.armv7l
- deb/ubuntu-zesty/Dockerfile.x86_64
- rpm/Makefile
- rpm/centos-7/Dockerfile.x86_64
- rpm/centos-7/docker-ce.spec
- rpm/fedora-24/Dockerfile.x86_64
- rpm/fedora-24/docker-ce.spec
- rpm/fedora-25/Dockerfile.x86_64
- rpm/fedora-25/docker-ce.spec
Generates man pages for rpm and deb packages.
> generate man pages

- deb/ubuntu-xenial/Dockerfile.s390x
- deb/ubuntu-yakkety/Dockerfile.s390x
- deb/ubuntu-zesty/Dockerfile.s390x
Needed for building man pages. This change was missed in PR #12 
> set $GOPATH/bin for s390x

- rpm/centos-7/docker-ce.spec
- rpm/fedora-24/docker-ce.spec
- rpm/fedora-25/docker-ce.spec
to fix rpmbuild error:
```
01:32:15 error: no description in %changelog
```
> update rpm changelog

- deb/common/control
- rpm/centos-7/docker-ce.spec
- rpm/fedora-24/docker-ce.spec
- rpm/fedora-25/docker-ce.spec
> Add conflicts with docker-ee

- rpm/centos-7/docker-ce.spec
- rpm/fedora-24/docker-ce.spec
- rpm/fedora-25/docker-ce.spec
> bump Version to 17.06.0-ce-rc5

- deb/README.md
- rpm/README.md
> Adds operating instructions

- rpm/centos-7/docker-ce.spec
- rpm/fedora-24/docker-ce.spec
- rpm/fedora-25/docker-ce.spec
> Increment RPM changelog to docker-ce 17.06.0-ce

- Makefile
- common/load-telemetry-plugin
- deb/Makefile
- deb/common/docker-ce.docker.init
- deb/common/docker-ce.docker.upstart
- deb/common/rules
- deb/systemd/docker.service
- rpm/Makefile
- rpm/centos-7/docker-ce.spec
- rpm/fedora-24/docker-ce.spec
- rpm/fedora-25/docker-ce.spec
- rpm/systemd/docker.service
**Packages:**
- centos
- fedora
- ubuntu
- debian
**the plugin is disabled by default**
Signed-off-by: Roberto Gandolfo Hashioka <roberto_hashioka@hotmail.com>
> Added the metrics plugin to the RPM/DEB packages

- Makefile
- rpm/Makefile
- rpm/fedora-26/Dockerfile.x86_64
- rpm/fedora-26/docker-ce.spec
Just released: https://docs.fedoraproject.org/en-US/Fedora/26/html/Release_Notes/
> build fedora 26 packages

- deb/common/rules
- rpm/centos-7/docker-ce.spec
- rpm/fedora-25/docker-ce.spec
- rpm/fedora-26/docker-ce.spec
- static/Makefile
Depends on:
* https://github.com/moby/moby/pull/34685
* https://github.com/moby/moby/pull/34704
ping @dnephin
> Removes engine VERSION dependency

- Makefile
- deb/Makefile
- deb/debian-buster/Dockerfile.armv7l
- deb/debian-buster/Dockerfile.x86_64
addresses https://github.com/moby/moby/issues/34854
ping @andrewhsu @seemethere
> Add builds for debian buster

- Jenkinsfile
> Make Jenkinsfile actually function

- Makefile
- deb/Makefile
- rpm/Makefile
- static/Makefile
Was getting annoying to have to write it into one spot so moved them to
above the targets that they specify.
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>
> Move .PHONY targets above actual targets

- deb/debian-buster/Dockerfile.armv7l
- deb/debian-buster/Dockerfile.x86_64
- deb/debian-jessie/Dockerfile.aarch64
- deb/debian-jessie/Dockerfile.armv7l
- deb/debian-jessie/Dockerfile.x86_64
- deb/debian-stretch/Dockerfile.aarch64
- deb/debian-stretch/Dockerfile.armv7l
- deb/debian-stretch/Dockerfile.x86_64
- deb/debian-wheezy/Dockerfile.x86_64
- deb/raspbian-jessie/Dockerfile.armv7l
- deb/raspbian-stretch/Dockerfile.armv7l
- deb/ubuntu-artful/Dockerfile.armv7l
- deb/ubuntu-artful/Dockerfile.ppc64le
- deb/ubuntu-artful/Dockerfile.s390x
- deb/ubuntu-artful/Dockerfile.x86_64
- deb/ubuntu-trusty/Dockerfile.armv7l
- deb/ubuntu-trusty/Dockerfile.x86_64
- deb/ubuntu-xenial/Dockerfile.aarch64
- deb/ubuntu-xenial/Dockerfile.armv7l
- deb/ubuntu-xenial/Dockerfile.ppc64le
- deb/ubuntu-xenial/Dockerfile.s390x
- deb/ubuntu-xenial/Dockerfile.x86_64
- rpm/centos-7/Dockerfile.aarch64
- rpm/centos-7/Dockerfile.x86_64
- rpm/fedora-26/Dockerfile.aarch64
- rpm/fedora-26/Dockerfile.x86_64
- rpm/fedora-27/Dockerfile.aarch64
- rpm/fedora-27/Dockerfile.x86_64
ping @andrewhsu @seemethere - we probably also need to vendor this / update in docker ce
> Update to go 1.9.3

- README.md
Signed-off-by: Kyle Spiers <kyle@spiers.me>
> Update readme to supported packages

- deb/build-deb
> Be less restrictive when moving packages

- README.md
> Add Bionic to README

- deb/debian-buster/Dockerfile.aarch64
Closes: https://github.com/docker/for-linux/issues/271
> Add aarch64 builder for debian-buster

- deb/common/control
- rpm/centos-7/docker-ce.spec
- rpm/fedora-27/docker-ce.spec
- rpm/fedora-28/docker-ce.spec
update homepage link and touch up description of the packages
> [18.06] update package descriptions and info

- .unir.yml
> Add unir yml

- Makefile
- image/Dockerfile
- image/Makefile
This adds a new packaging variant for engine with an image
> Add support for image build

- deb/Makefile
- image/Makefile
- rpm/Makefile
> Add tar targets for engine image

- Makefile
> [develop] Add top level make target

- deb/ubuntu-xenial/Dockerfile
Going to merge as soon as green.
> Build this on xenial instead

- rpm/Makefile
Makes it so that you can overwrite them better if you include this
makefile in another makefile...
> Make the build variables eval at reference

- Jenkinsfile
- common/dockerd.json
- deb/Makefile
- rpm/Makefile
> Make IMAGE_TAG configurable for dockerd.json

- common/dockerd.json
- deb/Makefile
- rpm/Makefile
> Make ENGINE_IMAGE configurable for dockerd.json

- systemd/docker.service
The daemon won't actually start without containerd now
> Set containerd to be a systemd bind for docker

- containerd.mk
update to the proxy codeline https://github.com/crosbymichael/containerd-proxy/tree/afca176
> [18.09] update containerd proxy commit to afca176

- systemd/docker.service
set to 2
https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartSec=
> [18.09] added RestartSec

- systemd/docker.service
Brings in #168
Cherry pick 5f4b9c0:
```
$ git cherry-pick -s -x 5f4b9c0
[ps 89d7846] Add post-stop
Author: Michael Crosby <crosbymichael@gmail.com>
Date: Tue Aug 28 13:51:21 2018 -0400
1 file changed, 1 insertion(+)
```
No conflicts.
> [18.09] Add post-stop

- containerd.mk
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
https://github.com/crosbymichael/containerd-proxy/compare/afca176...9a227f7
> Update proxy commit for shutdown timeouts

- deb/common/control
Backport of #189 
Cherry pick was **clean**
(cherry picked from commit 193a6be5de72509679c8729c8d4e3a81de4f1e8e)
> [18.09] Fix docker-ce-cli replacing files

- deb/Makefile
- rpm/SPECS/docker-ce-cli.spec
- rpm/SPECS/docker-ce.spec
- rpm/centos-7/docker-ce.spec
- rpm/fedora-27/docker-ce.spec
- rpm/fedora-28/docker-ce.spec
This should accomodate the new versioning fix
(cherry picked from commit be00095e1d0d5674665a63b6e5932178632feb0e)
> Bump packaging epoch

- deb/Makefile
- rpm/SPECS/docker-ce-cli.spec
- rpm/SPECS/docker-ce.spec
- rpm/centos-7/docker-ce.spec
- rpm/fedora-27/docker-ce.spec
- rpm/fedora-28/docker-ce.spec
This should accomodate the new versioning fix
> [18.09] Bump packaging epoch

- deb/Makefile
- image/Makefile
- rpm/Makefile
Making these changes to the `master` branch. 
Can then close this PR: https://github.com/docker/docker-ce-packaging/pull/188
and cherry-pick the changes from this branch on to the 18.09 branch.
> [master] move tar targets

- .gitignore
- image/Makefile
docker load doesn't support OCI based tar files so we have to make 2
different ones.
>  Have the tar target make a docker compat one too

- .gitignore
- image/Makefile
Cherry pick of #202 
Cherry pick was *clean*
> [18.09] Have the tar target make a docker compat one too

- deb/common/control
> [18.09] type fix on deb package recommends aufs-tools

- image/Dockerfile.engine
> Dynamically compile the docker daemon

- image/Dockerfile.engine-dm
- image/Makefile
> Make base for Dockerfile.engine-dm configurable

- image/Dockerfile.engine
Cherry pick of #217 
Cherry pick was **clean**
Will merge on green.
(cherry picked from commit 4f18a1969510930b98b4ad4375297ea4db3298f3)
> [18.09] Dynamically compile the docker daemon

- image/Dockerfile.engine-dm
- image/Makefile
Cherry pick of #218
Cherry pick was **clean**
(cherry picked from commit 605df1abcb4c432ebb1b73c29bfa0d5d3d48c0ce)
> [18.09] Make base for Dockerfile.engine-dm configurable

- rpm/SPECS/docker-ce-cli.spec
- rpm/SPECS/docker-ce.spec
- rpm/centos-7/docker-ce.spec
- rpm/fedora-27/docker-ce.spec
- rpm/fedora-28/docker-ce.spec
Porting https://github.com/docker/docker-ce-packaging/pull/226 to master
```
git checkout -b more_updates_to_package_description
git cherry-pick -s -S -x eb89f3ebd68033fe49b12016ad07f28cfc33d874
```
> [master] more updates to package descriptions

- image/Makefile
> switch to not be tag based but image based

- deb/Makefile
- deb/common/control
- deb/common/docker-ce.postinst
- deb/common/docker-ce.prerm
- deb/common/rules
- deb/debian-buster/Dockerfile
- deb/debian-jessie/Dockerfile
- deb/debian-stretch/Dockerfile
- deb/raspbian-jessie/Dockerfile
- deb/raspbian-stretch/Dockerfile
- deb/ubuntu-bionic/Dockerfile
- deb/ubuntu-trusty/Dockerfile
- deb/ubuntu-xenial/Dockerfile
- image/Dockerfile.engine
- image/Dockerfile.engine-dm
- image/Makefile
- rpm/Makefile
- rpm/SPECS/docker-ce.spec
- rpm/centos-7/Dockerfile
- rpm/fedora-27/Dockerfile
- rpm/fedora-28/Dockerfile
- systemd/docker.service
Cherry pick of #223 
Cherry pick was not clean, conflicts centered around `image/Dockerfile.engine` were resolved and tested.
Will merge on green
(cherry picked from commit 944fa7137c02ec56907b26fccfd3a363cd741890)
> [18.09] Use image artifacts as daemon and dependencies

- deb/Makefile
> Bump debian epoch to 5

- static/Makefile
Fixes static builds after https://github.com/moby/moby/pull/37907
> Fix static builds relying on docker-* prefix

- static/Makefile
> [18.09] Fix static builds relying on the docker-* prefix

- systemd/docker.service
Fixes https://github.com/docker/docker-core-backlog/issues/359
> Remove Environment, not needed anymore

- deb/common/control
Epoch needs to be included in the Replaces / Breaks sections
> Fix debian package upgrade scenarios

- systemd/docker.service
See rationale in moby/moby#37990
> Restore `Type=notify` in Systemd unit

- systemd/docker.service
backport of #275
```
$ git cherry-pick -s -x 88885d1
[sock 93f125a] Add docker.socket requirement for docker.service
Author: Eli Uriegas <eli.uriegas@docker.com>
Date: Mon Dec 3 19:14:10 2018 +0000
1 file changed, 1 insertion(+)
```
> [18.09] Add docker.socket requirement for docker.service

- static/Makefile
@seemethere @akihirosuda @tiborvass 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> static: bundle extra binaries for rootless

- rpm/centos-7/docker-ce.spec
- rpm/fedora-27/docker-ce.spec
- rpm/fedora-28/docker-ce.spec
> [18.06] rpm: Symlink engine source to GOPATH

- Jenkinsfile
This commit ensures that we test the correct branches of Docker
when making packaging changes.
> [TAR-465] Jenkinsfile: Test the correct branch

- deb/Makefile
> [master] Add a way to inject run flags if need be

- deb/Makefile
- deb/ubuntu-disco/Dockerfile
It was annoying to have to explicitly state a new ubuntu target every
time.
Relates to https://github.com/docker/for-linux/issues/533
> [master] [TAR-492] Add Ubuntu disco, make ubuntu building generic

- Jenkinsfile
This commit ensures that we test the correct branches of Docker
when making packaging changes.
(cherry picked from commit 1ef9fb3f0b2b8016b50c6c71f2d14bea16faff35)
> [18.06] [TAR-465] Jenkinsfile: Test the correct branch

- static/Makefile
> static: Use CURDIR as PWD in not well defined

- plugins/app.installer
- static/Makefile
- static/scripts/build-cli-plugins
Adds rigging to do cross building for windows, simplify mac building.
> [master] [TAR-577] Add rigging to cross build cli plugins for windows

- deb/debian-buster/Dockerfile
- deb/debian-stretch/Dockerfile
- deb/raspbian-stretch/Dockerfile
- deb/ubuntu-bionic/Dockerfile
- deb/ubuntu-cosmic/Dockerfile
- deb/ubuntu-disco/Dockerfile
- deb/ubuntu-xenial/Dockerfile
- rpm/centos-7/Dockerfile
- rpm/fedora-27/Dockerfile
- rpm/fedora-28/Dockerfile
- rpm/fedora-29/Dockerfile
- rpm/fedora-30/Dockerfile
> [master] Remove the pkcs11 tag, was a holdover from cli

- plugins/app.installer
bring it to the latest on master branch https://github.com/docker/app/tree/baf0b24
cc @vdemeester
> bump docker app commit to baf0b24

- static/Makefile
For https://github.com/moby/moby/pull/38913
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> add rootlesskit-docker-proxy

- plugins/buildx.installer
For the freshest of the fresh new hotness.
> [master] get the latest buildx from master branch

- plugins/app.installer
Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>
> Bump docker app to v0.8.0-beta2

- .unir.yml
> [master] add thaJeztah to unir

- plugins/buildx.installer
Pending on https://github.com/docker/buildx/pull/81
> make buildx experimental in Docker CE

- plugins/buildx.installer
File taken from master at afa39785444d4cb4c6871b313d14a48fbb204d2e
> [19.03] Add buildx plugin as experimental

- plugins/app.installer
Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>
> [19.03] Bump docker-app to v0.8.0-rc1

- plugins/app.installer
Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>
> [19.03] Bump docker-app to v0.8.0

- plugins/app.installer
Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>
> Bump docker-app to v0.8.0

- rpm/Makefile
- rpm/fedora-31/Dockerfile
**Description:** Added fedora-31 for ce-packaging.  It's based on the request here: 665, this PR provides a way for people to download and get the docker packages for fedora-31
Reference: [TAR-849](https://docker.atlassian.net/browse/TAR-849)
> [TAR-849] ADDED Dockerfile for fedora-31

- static/Makefile
Fixing error with pathing issue
> FIX pathing issue with cli dir

- deb/debian-buster/Dockerfile
- deb/debian-stretch/Dockerfile
- deb/raspbian-buster/Dockerfile
- deb/raspbian-stretch/Dockerfile
- deb/ubuntu-bionic/Dockerfile
- deb/ubuntu-cosmic/Dockerfile
- deb/ubuntu-disco/Dockerfile
- deb/ubuntu-xenial/Dockerfile
don't think these were actually used
> Dockerfiles: remove unused GO_VERSION

- deb/Makefile
- rpm/Makefile
Cherry-picked from: https://github.com/docker/docker-ce-packaging/pull/383
Signed-off-by: Zuhayr Elahi <elahi.zuhayr@gmail.com>
> [19.03] [backport changes] realpath for plugins directory

- plugins/buildx.installer
> plugins: pin buildx to v0.3.1

- deb/gen-deb-ver
- rpm/gen-rpm-ver
- static/gen-static-ver
In linux, this check always return 0:
```
$ [[ $(uname) -eq "Darwin" ]] && echo yes
yes
$ uname
Linux
```
Signed-off-by: Xiang Dai <764524258@qq.com>
> fix eq issue

- plugins/app.installer
Signed-off-by: Yves Brissaud <yves.brissaud@docker.com>
> bump docker-app to 0.9.0-beta1

- rpm/SPECS/docker-ce.spec
fix SPEC file declaration for boolean dependency
> RHEL8 build fix

- .unir.yml
@silvin-lubecki @StefanScherer PTAL
> update list of reviewers in unir config

- deb/gen-deb-ver
- rpm/gen-rpm-ver
- static/gen-static-ver
Backport of https://github.com/docker/docker-ce-packaging/pull/397
> [19.03 backport] fix eq issue

- rpm/Makefile
- rpm/rhel-7/Dockerfile
Add needed files to build a rhel 7 based s390x rpm using `dockereng/rhel:7-s390x`  helper image.
> [master] Add rhel for s390x

- plugins/buildx.installer
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> [master] buildx: use v0.4.1

- Jenkinsfile
- rpm/centos-8/Dockerfile
see individual commits for details
> [master] Build CentOS 8 on PR builds and fix GPG errors

- README.md
- rpm/Makefile
- rpm/fedora-33/Dockerfile
addresses https://github.com/docker/for-linux/issues/1114
> Add Fedora 33 (beta)

- rpm/centos-8/Dockerfile
Attempt to fix https://ci-next.docker.com/teams-core/blue/organizations/jenkins/release-packaging/detail/ce-20.10/16/pipeline/79
> centos-8: work around CentOS repo bug preventing to enable PowerTools

- Jenkinsfile
Make sure that cross-compile doesn't break on changes
> Jenkinsfile: also test cross-compile for Mac, Windows

- Jenkinsfile
backport of https://github.com/docker/docker-ce-packaging/pull/483
> [20.10 backport] Jenkinsfile: use Ubuntu 20.04 nodes for building

- Jenkinsfile
- Makefile
backport of https://github.com/docker/docker-ce-packaging/pull/594
> [20.10 backport] Jenkinsfile: run builds in parallel, and build all distro/arches

- common.mk
- plugins/scan.installer.disabled
> update Docker Scan version to 0.10.0

- plugins/buildx.installer
https://github.com/docker/buildx/releases/tag/v0.7.1
> update buildx to v0.7.1

- common.mk
- plugins/scan.installer.disabled
> update docker-scan to version 0.11.0

- common.mk
- plugins/scan.installer.disabled
(cherry picked from commit 15a8d1221e9fda004367d1278073421e4db25c61)
> [20.10 backport] update docker-scan to version 0.11.0

- common.mk
- plugins/scan.installer.disabled
> bump version of Docker Scan to v0.12.0

- common.mk
- plugins/scan.installer.disabled
> upgrade Docker Scan to v0.14.0

- common.mk
- plugins/scan.installer.disabled
(cherry picked from commit cc6e6ffb5cea04984347b40602d3cc908e5bab78)
> [20.10] backport upgrade Docker Scan to v0.14.0

- common.mk
- plugins/scan.installer.disabled
> upgrade Docker Scan to v0.15.0

- common.mk
- plugins/scan.installer.disabled
> [master] upgrade docker scan to v0.17.0

- Jenkinsfile
- deb/Makefile
- deb/ubuntu-jammy/Dockerfile
Signed-off-by: Romain Geissler <romain.geissler@amadeus.com>
> [20.10 backport] Add Ubuntu 22.04

- plugins/buildx.installer
https://github.com/docker/buildx/releases/tag/v0.8.0
> [master] update buildx to v0.8.0

- plugins/buildx.installer
#650
(cherry picked from commit 4f63c5394c01a0471293975e2b7b47e2c99f3469)
> [20.10 backport] update buildx to v0.8.1

- .github/workflows/ci.yml
initial workflow to warm GitHub Actions in this repo so further pull requests could use it.
> ci: init github actions

- rpm/Makefile
follow-up to https://github.com/docker/docker-ce-packaging/pull/658
> [master] rpm: add fedora-36 to makefile

- Jenkinsfile
- rpm/Makefile
- rpm/SPECS/docker-ce.spec
- rpm/centos-9/Dockerfile
Same as PR #634 but for branch 20.10.
> [20.10] Build for CentOS 9.

- common.mk
> [master] bump version of Compose to v2.6.0

- common.mk
> upgrade compose version to v2.6.1

- common.mk
> [master] bump version of Compose to v2.7.0

- common.mk
release notes: https://github.com/docker/compose/releases/tag/v2.10.1
once this is merged, I'll rebase https://github.com/docker/docker-ce-packaging/pull/748
> [master] update compose to v2.10.1

- common.mk
release notes: https://github.com/docker/compose/releases/tag/v2.10.2
> [master] update compose to v2.10.2

- common.mk
> bump compose version to v2.11.0

- common.mk
full diff: https://github.com/docker/scan-cli-plugin/compare/v0.17.0...v0.21.0
> update scan-cli-plugin to v0.21.0

- common.mk
> [master] bump Compose version to v2.12.0

- Jenkinsfile
- deb/Makefile
- deb/ubuntu-kinetic/Dockerfile
Release information: https://wiki.ubuntu.com/Releases
containerd-packaging PR:
- https://github.com/docker/containerd-packaging/pull/295
> [master] Add Ubuntu 22.10 Kinetic Kudu

- common.mk
dep: bump snyk to v1.1054.0
full diff: https://github.com/docker/scan-cli-plugin/compare/v0.21.0...v0.22.0
> [master] update scan-cli-plugin to v0.22.0

- common.mk
> bump compose version to v2.13.0

- common.mk
dep: bump snyk to v1.1064.0
full diff: https://github.com/docker/scan-cli-plugin/compare/v0.22.0...v0.23.0
> [master] update scan-cli-plugin to v0.23.0

- common.mk
https://github.com/docker/compose/releases/tag/v2.14.0
> [master] compose: bump version to v2.14.0

- common.mk
> bump compose version to v2.14.1

- common.mk
- static/Makefile
release notes: https://github.com/docker/buildx/releases/tag/v0.10.0-rc1
> [master] update buildx to v0.10.0-rc1

- common.mk
> bump Compose version to v2.14.2

- static/Makefile
follow-up https://github.com/moby/moby/pull/44546
closes #801 
> static: update with latest changes from moby

- deb/common/rules
- fixes https://github.com/docker/docker-ce-packaging/pull/822#discussion_r1067544238
> [master] deb: fix hyphen instead of tilde in buildx and compose

- common.mk
full diff: https://github.com/docker/buildx/compare/v0.10.0...v0.10.1
> [master] update buildx to v0.10.1

- plugins/buildx.installer
full diff: https://github.com/docker/buildx/compare/v0.10.1...v0.10.2
Signed-off-by: Romain Geissler <romain.geissler@amadeus.com>
> [20.10] update buildx to v0.10.2

- common.mk
full diff: https://github.com/docker/buildx/compare/v0.10.2...v0.10.3
> update buildx to v0.10.3

- common.mk
full diff: https://github.com/docker/buildx/compare/v0.10.3...v0.10.4
> [master] update buildx to v0.10.4

- common.mk
https://docker.atlassian.net/browse/ENV-168
> bump compose to v2.17.3

- common.mk
full diff: https://github.com/docker/buildx/compare/v0.10.4...v0.10.5
> [master] update buildx to v0.10.5

- common.mk
> [23.0 backport] update buildx to v0.10.5

- common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.11.0
> [master] update buildx to v0.11.0

- common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.11.1
cc @thaJeztah @neersighted @crazy-max
> [master] update buildx to v0.11.1

- common.mk
https://github.com/docker/compose/releases/tag/v2.20.1
> [master] update compose to v2.20.1

- common.mk
https://github.com/docker/compose/releases/tag/v2.21.0
> bump compose version to v2.21.0

- common.mk
> fix default value for VERIFY_PACKAGE_REPO

- Jenkinsfile
- deb/Makefile
- deb/ubuntu-mantic/Dockerfile
- carries / closes https://github.com/docker/docker-ce-packaging/pull/949
pushing https://github.com/docker/docker-ce-packaging/pull/949 with my account, otherwise Jenkins won't run the job.
> [Master] Add Ubuntu 23.10 "Mantic Minotaur" (test in CI)

- Jenkinsfile
- follow-up to https://github.com/docker/docker-ce-packaging/pull/954
> [master] Jenkinsfile: fix version and eol-date for Ubuntu mantic (23.10)

- common.mk
Upgrade version of Compose to `v2.23.0`
> bump compose version to v2.23.0

- common.mk
https://github.com/docker/buildx/releases/tag/v0.12.0
> update buildx to v0.12.0

- common.mk
release notes: https://github.com/docker/buildx/releases/tag/v0.12.1
> [master] update buildx to v0.12.1

- common.mk
https://github.com/docker/compose/releases/tag/v2.24.5
> update to Compose v2.24.5

- common.mk
Everything is in the PR title 😅 
link to https://docker.atlassian.net/browse/COMP-434
> bump compose to version v2.24.6

- common.mk
https://github.com/docker/compose/releases/tag/v2.24.7
> [master] update to Compose v2.24.7

- Jenkinsfile
- rpm/Makefile
- rpm/fedora-40/Dockerfile
- carry / closes https://github.com/docker/docker-ce-packaging/pull/992 to make Jenkins run the builds
- addresses https://github.com/docker/for-linux/issues/1491
> [master] Enable Fedora 40 builds (carry 992)

- common.mk
> Bump compose v2.26.0

- common.mk
https://github.com/docker/buildx/compare/v0.13.1...v0.14.0
> update buildx to v0.14.0

- common.mk
Bump Compose to version `v2.27.0`
Update Docker Compose to `v2.27.0`
> bump compose to version v2.27.0

- common.mk
https://github.com/docker/buildx/releases/tag/v0.15.0
> update buildx to v0.15.0

- common.mk
Bump Compose to version `v2.27.2`
[Compose v2.27.2](https://github.com/docker/compose/releases/tag/v2.27.2)
> bump Compose to version v2.27.2

- common.mk
Bump Compose to `v2.28.0` using engine & cli `v27.0.0-rc.1`
[Compose v2.28.0](https://github.com/docker/compose/releases/tag/v2.28.0)
> bump Compose to version v2.28.0

- common.mk
Bump Compose to version `v2.28.1`
> bump Compose to version v2.28.1

- common.mk
Update Compose to the last release `v2.29.0`
> bump Compose to version v2.29.0

- common.mk
https://github.com/docker/buildx/releases/tag/v0.16.1
> update buildx to v0.16.1

- common.mk
Bump compose v2.29.1
Docker Compose v2.29.1
> Bump compose v2.29.1

- common.mk
https://github.com/docker/buildx/releases/tag/v0.16.2
> [master] update buildx to v0.16.2

- common.mk
https://github.com/docker/buildx/releases/tag/v0.17.0
> update buildx to v0.17.0

- common.mk
- backport https://github.com/docker/docker-ce-packaging/pull/1071
(cherry picked from commit 9467f0c67b8a93ea7e00875a79e32248d37aa517)
> [27.x backport] update buildx to v0.17.0

- common.mk
bump compose to v2.29.3
Compose v2.29.3
> bump compose to v2.29.3

- common.mk
(cherry picked from commit 857cd70fb2e286c5ba646ce6137b38f629e49920)
Backport bump version of Compose v2.29.3
> bump compose to version v2.29.3

- common.mk
https://github.com/docker/buildx/releases/tag/v0.17.1
> [master] update buildx to v0.17.1

- common.mk
Bump compose to version `v2.29.4`
> [master] bump compose to version v2.29.4

- common.mk
(cherry picked from commit 17c8893f946fc13f2c409bde7932a7a797e8b0a4)
Backport Bump compose to version `v2.29.4`
> [27.x backport] bump compose to version v2.29.4

- common.mk
- backport https://github.com/docker/docker-ce-packaging/pull/1077
(cherry picked from commit 523d5dbdcb0e99a4ae78428383fdeb73b58be41a)
```markdown
- Update buildx [to v0.17.1](https://github.com/docker/buildx/releases/tag/v0.17.1)
```
> [27.x backport] update buildx to v0.17.1

- common.mk
release-notes: https://github.com/docker/compose/releases/tag/v2.29.5
```markdown
- Update compose [to v2.29.5](https://github.com/docker/compose/releases/tag/v2.29.5)
```
> [master] bump compose to v2.29.5

- common.mk
Bump compose for latest release
Docker Compose v2.29.7
> Bump compose to v2.29.7

- common.mk
Bump Compose to version `v2.30.0`
> bump Compose to version v2.30.0

- common.mk
(cherry picked from commit 1d14711ab3b6d2513b04fc880df68a703d852eec)
Backport of the bump Compose to version v2.30.0
> [Backport] bump Compose to version v2.30.0

- common.mk
Bump Compose to version `v2.30.1`
> bump Compose to version v2.30.1

- common.mk
> update buildx to v0.18.0

- common.mk
Backport bump of Compose `v2.30.2`
> [Backport] bump compose v2.30.2

- common.mk
```
Update Compose to [v2.30.3](https://github.com/docker/compose/releases/tag/v2.30.3)
```
> [master] bump Compose to version v2.30.3

- common.mk
> update buildx to v0.19.0

- common.mk
> update buildx to v0.19.1

- common.mk
Bump Compose to version `v2.31.0`
> bump Compose to version v2.31.0

- common.mk
> update buildx to v0.19.2

- common.mk
- backport https://github.com/docker/docker-ce-packaging/pull/1122
Update buildx to v0.19.2
> [27.x backport] update buildx to v0.19.2

- common.mk
Bump compose to v2.32.1 to fix a regression found in v2.32.0
Bump compose to v2.32.1
> Bump compose to v2.32.1

- common.mk
- backport: https://github.com/docker/docker-ce-packaging/pull/1131
(cherry picked from commit 0275e8974ef03b24dcfc65ba2107f89ceebc467c)
```markdown changelog
Update buildx to v0.19.3
```
> [27.x backport] update buildx to v0.19.3

- Jenkinsfile
see https://wiki.debian.org/DebianReleases
> [master] Jenkinsfile: update Debian EOL dates

- common.mk
> [master] update buildx to v0.20.1

- common.mk
> [master] Bump buildx to v0.21.0-rc2

- common.mk
> bump compose verstion to v2.33.1

- common.mk
https://github.com/docker/buildx/releases/tag/v0.21.2
```markdown changelog
Update Buildx to [v0.21.2](https://github.com/docker/buildx/releases/tag/v0.21.2)
```
> update buildx to v0.21.2

- common.mk
https://github.com/docker/buildx/releases/tag/v0.21.3
```markdown changelog
Update Buildx to [v0.21.3](https://github.com/docker/buildx/releases/tag/v0.21.3)
```
> update buildx to v0.21.3

- common.mk
> bump compose version to v2.35.1

- common.mk
https://github.com/docker/buildx/releases/tag/v0.23.0
```markdown changelog
Update Buildx to [v0.23.0](https://github.com/docker/buildx/releases/tag/v0.23.0)
```
> [master] update buildx to v0.23.0

- common.mk
https://github.com/docker/buildx/releases/tag/v0.24.0
```markdown changelog
Update Buildx to [v0.24.0](https://github.com/docker/buildx/releases/tag/v0.24.0)
```
> [master] update buildx to v0.24.0

- .github/PULL_REQUEST_TEMPLATE.md
Simplified PR template
Adjusted changelog section so it's picked up by the release note tool
> github: Simplify PR template and adjust changelog section

- common.mk
Bump Compose to version `v2.37.0`
```markdown changelog
Update Compose to [v2.37.0](https://github.com/docker/compose/releases/tag/v2.37.0)
```
> bump compose version to v2.37.0

- common.mk
Bump Compose to version `v2.37.1`
```markdown changelog
Update Compose to [v2.37.1](https://github.com/docker/compose/releases/tag/v2.37.1)
```
> bump compose version to v2.37.1

- common.mk
```markdown changelog
Bump Docker Compose to v2.37.2
```
> bump compose to v2.37.2

- common.mk
Bump Compose to the latest `v2.39.0` release
```markdown changelog
Update Compose to [v2.39.0](https://github.com/docker/compose/releases/tag/v2.39.0)
```
> bump Compose to version v2.39.0

- common.mk
Bump Compose version to `v2.39.2`
```markdown changelog
Update Compose to [v2.39.2](https://github.com/docker/compose/releases/tag/v2.39.2)
```
> bump Compose to version v2.39.2

- common.mk
https://github.com/docker/buildx/releases/tag/v0.27.0
```markdown changelog
Update Buildx to [v0.27.0](https://github.com/docker/buildx/releases/tag/v0.27.0)
```
> update buildx to v0.27.0

- common.mk
I bumped the Model CLI version to v0.1.39, which aligns with the upcoming Docker Desktop 4.45 release.
```markdown changelog
- `docker model`: Add support for sharded GGUF models
```
> Bump Docker Model CLI version to v0.1.39

- common.mk
Use latest released version of Compose `v2.39.3`
```markdown changelog
Update Compose to [v2.39.3](https://github.com/docker/compose/releases/tag/v2.39.3)
```
> bump compose to version v2.39.3

- common.mk
Bump Compose to latest `v2.39.4` version
```markdown changelog
Update Compose to [v2.39.4](https://github.com/docker/compose/releases/tag/v2.39.4)
```
> bump compose to version v2.39.4
